// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// AdminProblemSet is the predicate function for adminproblemset builders.
type AdminProblemSet func(*sql.Selector)

// Announcement is the predicate function for announcement builders.
type Announcement func(*sql.Selector)

// JudgeRecord is the predicate function for judgerecord builders.
type JudgeRecord func(*sql.Selector)

// Problem is the predicate function for problem builders.
type Problem func(*sql.Selector)

// ProblemSet is the predicate function for problemset builders.
type ProblemSet func(*sql.Selector)

// ProblemSet_Problem is the predicate function for problemset_problem builders.
type ProblemSet_Problem func(*sql.Selector)

// ProblemSet_User is the predicate function for problemset_user builders.
type ProblemSet_User func(*sql.Selector)

// SubmissionRecord is the predicate function for submissionrecord builders.
type SubmissionRecord func(*sql.Selector)

// SystemLog is the predicate function for systemlog builders.
type SystemLog func(*sql.Selector)

// TestCase is the predicate function for testcase builders.
type TestCase func(*sql.Selector)

// User is the predicate function for user builders.
type User func(*sql.Selector)
