// Code generated by ent, DO NOT EDIT.

package user

import (
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

const (
	// Label holds the string label denoting the user type in the database.
	Label = "user"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldUsername holds the string denoting the username field in the database.
	FieldUsername = "username"
	// FieldEmail holds the string denoting the email field in the database.
	FieldEmail = "email"
	// FieldPasswordHash holds the string denoting the password_hash field in the database.
	FieldPasswordHash = "password_hash"
	// FieldRole holds the string denoting the role field in the database.
	FieldRole = "role"
	// EdgeProblems holds the string denoting the problems edge name in mutations.
	EdgeProblems = "problems"
	// EdgeJudgeRecords holds the string denoting the judge_records edge name in mutations.
	EdgeJudgeRecords = "judge_records"
	// EdgeAnnouncements holds the string denoting the announcements edge name in mutations.
	EdgeAnnouncements = "announcements"
	// EdgeAdminProblemSets holds the string denoting the admin_problem_sets edge name in mutations.
	EdgeAdminProblemSets = "admin_problem_sets"
	// EdgeProblemSetUsers holds the string denoting the problem_set_users edge name in mutations.
	EdgeProblemSetUsers = "problem_set_users"
	// Table holds the table name of the user in the database.
	Table = "Users"
	// ProblemsTable is the table that holds the problems relation/edge.
	ProblemsTable = "Problems"
	// ProblemsInverseTable is the table name for the Problem entity.
	// It exists in this package in order to avoid circular dependency with the "problem" package.
	ProblemsInverseTable = "Problems"
	// ProblemsColumn is the table column denoting the problems relation/edge.
	ProblemsColumn = "creator_id"
	// JudgeRecordsTable is the table that holds the judge_records relation/edge.
	JudgeRecordsTable = "JudgeRecords"
	// JudgeRecordsInverseTable is the table name for the JudgeRecord entity.
	// It exists in this package in order to avoid circular dependency with the "judgerecord" package.
	JudgeRecordsInverseTable = "JudgeRecords"
	// JudgeRecordsColumn is the table column denoting the judge_records relation/edge.
	JudgeRecordsColumn = "user_id"
	// AnnouncementsTable is the table that holds the announcements relation/edge.
	AnnouncementsTable = "Announcements"
	// AnnouncementsInverseTable is the table name for the Announcement entity.
	// It exists in this package in order to avoid circular dependency with the "announcement" package.
	AnnouncementsInverseTable = "Announcements"
	// AnnouncementsColumn is the table column denoting the announcements relation/edge.
	AnnouncementsColumn = "publisher_id"
	// AdminProblemSetsTable is the table that holds the admin_problem_sets relation/edge.
	AdminProblemSetsTable = "Admin_ProblemSet"
	// AdminProblemSetsInverseTable is the table name for the AdminProblemSet entity.
	// It exists in this package in order to avoid circular dependency with the "adminproblemset" package.
	AdminProblemSetsInverseTable = "Admin_ProblemSet"
	// AdminProblemSetsColumn is the table column denoting the admin_problem_sets relation/edge.
	AdminProblemSetsColumn = "admin_id"
	// ProblemSetUsersTable is the table that holds the problem_set_users relation/edge.
	ProblemSetUsersTable = "ProblemSet_Users"
	// ProblemSetUsersInverseTable is the table name for the ProblemSetUser entity.
	// It exists in this package in order to avoid circular dependency with the "problemsetuser" package.
	ProblemSetUsersInverseTable = "ProblemSet_Users"
	// ProblemSetUsersColumn is the table column denoting the problem_set_users relation/edge.
	ProblemSetUsersColumn = "user_id"
)

// Columns holds all SQL columns for user fields.
var Columns = []string{
	FieldID,
	FieldUsername,
	FieldEmail,
	FieldPasswordHash,
	FieldRole,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// UsernameValidator is a validator for the "username" field. It is called by the builders before save.
	UsernameValidator func(string) error
	// EmailValidator is a validator for the "email" field. It is called by the builders before save.
	EmailValidator func(string) error
	// PasswordHashValidator is a validator for the "password_hash" field. It is called by the builders before save.
	PasswordHashValidator func(string) error
	// IDValidator is a validator for the "id" field. It is called by the builders before save.
	IDValidator func(int) error
)

// Role defines the type for the "role" enum field.
type Role string

// RoleCompetitor is the default value of the Role enum.
const DefaultRole = RoleCompetitor

// Role values.
const (
	RoleCompetitor Role = "competitor"
	RoleCreator    Role = "creator"
	RoleAdmin      Role = "admin"
)

func (r Role) String() string {
	return string(r)
}

// RoleValidator is a validator for the "role" field enum values. It is called by the builders before save.
func RoleValidator(r Role) error {
	switch r {
	case RoleCompetitor, RoleCreator, RoleAdmin:
		return nil
	default:
		return fmt.Errorf("user: invalid enum value for role field: %q", r)
	}
}

// OrderOption defines the ordering options for the User queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByUsername orders the results by the username field.
func ByUsername(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUsername, opts...).ToFunc()
}

// ByEmail orders the results by the email field.
func ByEmail(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldEmail, opts...).ToFunc()
}

// ByPasswordHash orders the results by the password_hash field.
func ByPasswordHash(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPasswordHash, opts...).ToFunc()
}

// ByRole orders the results by the role field.
func ByRole(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldRole, opts...).ToFunc()
}

// ByProblemsCount orders the results by problems count.
func ByProblemsCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newProblemsStep(), opts...)
	}
}

// ByProblems orders the results by problems terms.
func ByProblems(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newProblemsStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}

// ByJudgeRecordsCount orders the results by judge_records count.
func ByJudgeRecordsCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newJudgeRecordsStep(), opts...)
	}
}

// ByJudgeRecords orders the results by judge_records terms.
func ByJudgeRecords(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newJudgeRecordsStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}

// ByAnnouncementsCount orders the results by announcements count.
func ByAnnouncementsCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newAnnouncementsStep(), opts...)
	}
}

// ByAnnouncements orders the results by announcements terms.
func ByAnnouncements(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newAnnouncementsStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}

// ByAdminProblemSetsCount orders the results by admin_problem_sets count.
func ByAdminProblemSetsCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newAdminProblemSetsStep(), opts...)
	}
}

// ByAdminProblemSets orders the results by admin_problem_sets terms.
func ByAdminProblemSets(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newAdminProblemSetsStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}

// ByProblemSetUsersCount orders the results by problem_set_users count.
func ByProblemSetUsersCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newProblemSetUsersStep(), opts...)
	}
}

// ByProblemSetUsers orders the results by problem_set_users terms.
func ByProblemSetUsers(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newProblemSetUsersStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}
func newProblemsStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(ProblemsInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2M, false, ProblemsTable, ProblemsColumn),
	)
}
func newJudgeRecordsStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(JudgeRecordsInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2M, false, JudgeRecordsTable, JudgeRecordsColumn),
	)
}
func newAnnouncementsStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(AnnouncementsInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2M, false, AnnouncementsTable, AnnouncementsColumn),
	)
}
func newAdminProblemSetsStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(AdminProblemSetsInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2M, false, AdminProblemSetsTable, AdminProblemSetsColumn),
	)
}
func newProblemSetUsersStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(ProblemSetUsersInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2M, false, ProblemSetUsersTable, ProblemSetUsersColumn),
	)
}
