// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        (unknown)
// source: public/auth/v1/auth.proto

package v1

import (
	_ "github.com/go-kratos/kratos/v2/errors"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ErrorReason int32

const (
	ErrorReason_NOT_REGISTERED ErrorReason = 0
)

// Enum value maps for ErrorReason.
var (
	ErrorReason_name = map[int32]string{
		0: "NOT_REGISTERED",
	}
	ErrorReason_value = map[string]int32{
		"NOT_REGISTERED": 0,
	}
)

func (x ErrorReason) Enum() *ErrorReason {
	p := new(ErrorReason)
	*p = x
	return p
}

func (x ErrorReason) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ErrorReason) Descriptor() protoreflect.EnumDescriptor {
	return file_public_auth_v1_auth_proto_enumTypes[0].Descriptor()
}

func (ErrorReason) Type() protoreflect.EnumType {
	return &file_public_auth_v1_auth_proto_enumTypes[0]
}

func (x ErrorReason) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ErrorReason.Descriptor instead.
func (ErrorReason) EnumDescriptor() ([]byte, []int) {
	return file_public_auth_v1_auth_proto_rawDescGZIP(), []int{0}
}

type LoginRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Username      string                 `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	Password      string                 `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoginRequest) Reset() {
	*x = LoginRequest{}
	mi := &file_public_auth_v1_auth_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginRequest) ProtoMessage() {}

func (x *LoginRequest) ProtoReflect() protoreflect.Message {
	mi := &file_public_auth_v1_auth_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginRequest.ProtoReflect.Descriptor instead.
func (*LoginRequest) Descriptor() ([]byte, []int) {
	return file_public_auth_v1_auth_proto_rawDescGZIP(), []int{0}
}

func (x *LoginRequest) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *LoginRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

type LoginReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Token         string                 `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoginReply) Reset() {
	*x = LoginReply{}
	mi := &file_public_auth_v1_auth_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginReply) ProtoMessage() {}

func (x *LoginReply) ProtoReflect() protoreflect.Message {
	mi := &file_public_auth_v1_auth_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginReply.ProtoReflect.Descriptor instead.
func (*LoginReply) Descriptor() ([]byte, []int) {
	return file_public_auth_v1_auth_proto_rawDescGZIP(), []int{1}
}

func (x *LoginReply) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

type LogoutRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LogoutRequest) Reset() {
	*x = LogoutRequest{}
	mi := &file_public_auth_v1_auth_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogoutRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogoutRequest) ProtoMessage() {}

func (x *LogoutRequest) ProtoReflect() protoreflect.Message {
	mi := &file_public_auth_v1_auth_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogoutRequest.ProtoReflect.Descriptor instead.
func (*LogoutRequest) Descriptor() ([]byte, []int) {
	return file_public_auth_v1_auth_proto_rawDescGZIP(), []int{2}
}

type LogoutReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LogoutReply) Reset() {
	*x = LogoutReply{}
	mi := &file_public_auth_v1_auth_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogoutReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogoutReply) ProtoMessage() {}

func (x *LogoutReply) ProtoReflect() protoreflect.Message {
	mi := &file_public_auth_v1_auth_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogoutReply.ProtoReflect.Descriptor instead.
func (*LogoutReply) Descriptor() ([]byte, []int) {
	return file_public_auth_v1_auth_proto_rawDescGZIP(), []int{3}
}

func (x *LogoutReply) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type SignupRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Username      string                 `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	Password      string                 `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	Email         string                 `protobuf:"bytes,3,opt,name=email,proto3" json:"email,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SignupRequest) Reset() {
	*x = SignupRequest{}
	mi := &file_public_auth_v1_auth_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SignupRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SignupRequest) ProtoMessage() {}

func (x *SignupRequest) ProtoReflect() protoreflect.Message {
	mi := &file_public_auth_v1_auth_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SignupRequest.ProtoReflect.Descriptor instead.
func (*SignupRequest) Descriptor() ([]byte, []int) {
	return file_public_auth_v1_auth_proto_rawDescGZIP(), []int{4}
}

func (x *SignupRequest) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *SignupRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *SignupRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

type SignupReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SignupReply) Reset() {
	*x = SignupReply{}
	mi := &file_public_auth_v1_auth_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SignupReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SignupReply) ProtoMessage() {}

func (x *SignupReply) ProtoReflect() protoreflect.Message {
	mi := &file_public_auth_v1_auth_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SignupReply.ProtoReflect.Descriptor instead.
func (*SignupReply) Descriptor() ([]byte, []int) {
	return file_public_auth_v1_auth_proto_rawDescGZIP(), []int{5}
}

func (x *SignupReply) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

var File_public_auth_v1_auth_proto protoreflect.FileDescriptor

const file_public_auth_v1_auth_proto_rawDesc = "" +
	"\n" +
	"\x19public/auth/v1/auth.proto\x12\x1aapi.cascade.public.auth.v1\x1a\x1cgoogle/api/annotations.proto\x1a\x13errors/errors.proto\"F\n" +
	"\fLoginRequest\x12\x1a\n" +
	"\busername\x18\x01 \x01(\tR\busername\x12\x1a\n" +
	"\bpassword\x18\x02 \x01(\tR\bpassword\"\"\n" +
	"\n" +
	"LoginReply\x12\x14\n" +
	"\x05token\x18\x01 \x01(\tR\x05token\"\x0f\n" +
	"\rLogoutRequest\"'\n" +
	"\vLogoutReply\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"]\n" +
	"\rSignupRequest\x12\x1a\n" +
	"\busername\x18\x01 \x01(\tR\busername\x12\x1a\n" +
	"\bpassword\x18\x02 \x01(\tR\bpassword\x12\x14\n" +
	"\x05email\x18\x03 \x01(\tR\x05email\"'\n" +
	"\vSignupReply\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess*-\n" +
	"\vErrorReason\x12\x18\n" +
	"\x0eNOT_REGISTERED\x10\x00\x1a\x04\xa8E\x91\x03\x1a\x04\xa0E\xf4\x032\xdf\x02\n" +
	"\vAuthService\x12l\n" +
	"\x05Login\x12(.api.cascade.public.auth.v1.LoginRequest\x1a&.api.cascade.public.auth.v1.LoginReply\"\x11\x82\xd3\xe4\x93\x02\v:\x01*\"\x06/login\x12p\n" +
	"\x06Logout\x12).api.cascade.public.auth.v1.LogoutRequest\x1a'.api.cascade.public.auth.v1.LogoutReply\"\x12\x82\xd3\xe4\x93\x02\f:\x01*\"\a/logout\x12p\n" +
	"\x06Signup\x12).api.cascade.public.auth.v1.SignupRequest\x1a'.api.cascade.public.auth.v1.SignupReply\"\x12\x82\xd3\xe4\x93\x02\f:\x01*\"\a/signupB\xe4\x01\n" +
	"\x1ecom.api.cascade.public.auth.v1B\tAuthProtoP\x01Z(cascade-oj/api/cascade/public/auth/v1;v1\xa2\x02\x04ACPA\xaa\x02\x1aApi.Cascade.Public.Auth.V1\xca\x02\x1bApi\\Cascade\\Public_\\Auth\\V1\xe2\x02'Api\\Cascade\\Public_\\Auth\\V1\\GPBMetadata\xea\x02\x1eApi::Cascade::Public::Auth::V1b\x06proto3"

var (
	file_public_auth_v1_auth_proto_rawDescOnce sync.Once
	file_public_auth_v1_auth_proto_rawDescData []byte
)

func file_public_auth_v1_auth_proto_rawDescGZIP() []byte {
	file_public_auth_v1_auth_proto_rawDescOnce.Do(func() {
		file_public_auth_v1_auth_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_public_auth_v1_auth_proto_rawDesc), len(file_public_auth_v1_auth_proto_rawDesc)))
	})
	return file_public_auth_v1_auth_proto_rawDescData
}

var file_public_auth_v1_auth_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_public_auth_v1_auth_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_public_auth_v1_auth_proto_goTypes = []any{
	(ErrorReason)(0),      // 0: api.cascade.public.auth.v1.ErrorReason
	(*LoginRequest)(nil),  // 1: api.cascade.public.auth.v1.LoginRequest
	(*LoginReply)(nil),    // 2: api.cascade.public.auth.v1.LoginReply
	(*LogoutRequest)(nil), // 3: api.cascade.public.auth.v1.LogoutRequest
	(*LogoutReply)(nil),   // 4: api.cascade.public.auth.v1.LogoutReply
	(*SignupRequest)(nil), // 5: api.cascade.public.auth.v1.SignupRequest
	(*SignupReply)(nil),   // 6: api.cascade.public.auth.v1.SignupReply
}
var file_public_auth_v1_auth_proto_depIdxs = []int32{
	1, // 0: api.cascade.public.auth.v1.AuthService.Login:input_type -> api.cascade.public.auth.v1.LoginRequest
	3, // 1: api.cascade.public.auth.v1.AuthService.Logout:input_type -> api.cascade.public.auth.v1.LogoutRequest
	5, // 2: api.cascade.public.auth.v1.AuthService.Signup:input_type -> api.cascade.public.auth.v1.SignupRequest
	2, // 3: api.cascade.public.auth.v1.AuthService.Login:output_type -> api.cascade.public.auth.v1.LoginReply
	4, // 4: api.cascade.public.auth.v1.AuthService.Logout:output_type -> api.cascade.public.auth.v1.LogoutReply
	6, // 5: api.cascade.public.auth.v1.AuthService.Signup:output_type -> api.cascade.public.auth.v1.SignupReply
	3, // [3:6] is the sub-list for method output_type
	0, // [0:3] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_public_auth_v1_auth_proto_init() }
func file_public_auth_v1_auth_proto_init() {
	if File_public_auth_v1_auth_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_public_auth_v1_auth_proto_rawDesc), len(file_public_auth_v1_auth_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_public_auth_v1_auth_proto_goTypes,
		DependencyIndexes: file_public_auth_v1_auth_proto_depIdxs,
		EnumInfos:         file_public_auth_v1_auth_proto_enumTypes,
		MessageInfos:      file_public_auth_v1_auth_proto_msgTypes,
	}.Build()
	File_public_auth_v1_auth_proto = out.File
	file_public_auth_v1_auth_proto_goTypes = nil
	file_public_auth_v1_auth_proto_depIdxs = nil
}
