// Code generated by ent, DO NOT EDIT.

package casegroupresult

import (
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

const (
	// Label holds the string label denoting the casegroupresult type in the database.
	Label = "case_group_result"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldSubmissionID holds the string denoting the submission_id field in the database.
	FieldSubmissionID = "submission_id"
	// FieldStatus holds the string denoting the status field in the database.
	FieldStatus = "status"
	// FieldTotalTimeCostMs holds the string denoting the total_time_cost_ms field in the database.
	FieldTotalTimeCostMs = "total_time_cost_ms"
	// FieldMaxMemoryCostKB holds the string denoting the max_memory_cost_kb field in the database.
	FieldMaxMemoryCostKB = "max_memory_cost_kb"
	// FieldScore holds the string denoting the score field in the database.
	FieldScore = "score"
	// EdgeProblem holds the string denoting the problem edge name in mutations.
	EdgeProblem = "problem"
	// EdgeCaseResults holds the string denoting the case_results edge name in mutations.
	EdgeCaseResults = "case_results"
	// EdgeSubmissionRecord holds the string denoting the submission_record edge name in mutations.
	EdgeSubmissionRecord = "submission_record"
	// Table holds the table name of the casegroupresult in the database.
	Table = "CaseGroup_Results"
	// ProblemTable is the table that holds the problem relation/edge.
	ProblemTable = "Problems"
	// ProblemInverseTable is the table name for the Problem entity.
	// It exists in this package in order to avoid circular dependency with the "problem" package.
	ProblemInverseTable = "Problems"
	// ProblemColumn is the table column denoting the problem relation/edge.
	ProblemColumn = "case_group_result_problem"
	// CaseResultsTable is the table that holds the case_results relation/edge.
	CaseResultsTable = "Case_Results"
	// CaseResultsInverseTable is the table name for the CaseResult entity.
	// It exists in this package in order to avoid circular dependency with the "caseresult" package.
	CaseResultsInverseTable = "Case_Results"
	// CaseResultsColumn is the table column denoting the case_results relation/edge.
	CaseResultsColumn = "case_group_result_id"
	// SubmissionRecordTable is the table that holds the submission_record relation/edge.
	SubmissionRecordTable = "CaseGroup_Results"
	// SubmissionRecordInverseTable is the table name for the SubmissionRecord entity.
	// It exists in this package in order to avoid circular dependency with the "submissionrecord" package.
	SubmissionRecordInverseTable = "SubmissionRecords"
	// SubmissionRecordColumn is the table column denoting the submission_record relation/edge.
	SubmissionRecordColumn = "submission_id"
)

// Columns holds all SQL columns for casegroupresult fields.
var Columns = []string{
	FieldID,
	FieldSubmissionID,
	FieldStatus,
	FieldTotalTimeCostMs,
	FieldMaxMemoryCostKB,
	FieldScore,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultStatus holds the default value on creation for the "status" field.
	DefaultStatus int16
	// DefaultScore holds the default value on creation for the "score" field.
	DefaultScore int
	// IDValidator is a validator for the "id" field. It is called by the builders before save.
	IDValidator func(int64) error
)

// OrderOption defines the ordering options for the CaseGroupResult queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// BySubmissionID orders the results by the submission_id field.
func BySubmissionID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSubmissionID, opts...).ToFunc()
}

// ByStatus orders the results by the status field.
func ByStatus(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldStatus, opts...).ToFunc()
}

// ByTotalTimeCostMs orders the results by the total_time_cost_ms field.
func ByTotalTimeCostMs(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldTotalTimeCostMs, opts...).ToFunc()
}

// ByMaxMemoryCostKB orders the results by the max_memory_cost_kb field.
func ByMaxMemoryCostKB(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldMaxMemoryCostKB, opts...).ToFunc()
}

// ByScore orders the results by the score field.
func ByScore(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldScore, opts...).ToFunc()
}

// ByProblemCount orders the results by problem count.
func ByProblemCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newProblemStep(), opts...)
	}
}

// ByProblem orders the results by problem terms.
func ByProblem(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newProblemStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}

// ByCaseResultsCount orders the results by case_results count.
func ByCaseResultsCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newCaseResultsStep(), opts...)
	}
}

// ByCaseResults orders the results by case_results terms.
func ByCaseResults(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newCaseResultsStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}

// BySubmissionRecordField orders the results by submission_record field.
func BySubmissionRecordField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newSubmissionRecordStep(), sql.OrderByField(field, opts...))
	}
}
func newProblemStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(ProblemInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2M, false, ProblemTable, ProblemColumn),
	)
}
func newCaseResultsStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(CaseResultsInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2M, false, CaseResultsTable, CaseResultsColumn),
	)
}
func newSubmissionRecordStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(SubmissionRecordInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, SubmissionRecordTable, SubmissionRecordColumn),
	)
}
