// Code generated by ent, DO NOT EDIT.

package adminproblemset

import (
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

const (
	// Label holds the string label denoting the adminproblemset type in the database.
	Label = "admin_problem_set"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldAdminID holds the string denoting the admin_id field in the database.
	FieldAdminID = "admin_id"
	// FieldProblemSetID holds the string denoting the problem_set_id field in the database.
	FieldProblemSetID = "problem_set_id"
	// EdgeAdmin holds the string denoting the admin edge name in mutations.
	EdgeAdmin = "admin"
	// EdgeProblemSet holds the string denoting the problem_set edge name in mutations.
	EdgeProblemSet = "problem_set"
	// Table holds the table name of the adminproblemset in the database.
	Table = "Admin_ProblemSet"
	// AdminTable is the table that holds the admin relation/edge.
	AdminTable = "Admin_ProblemSet"
	// AdminInverseTable is the table name for the User entity.
	// It exists in this package in order to avoid circular dependency with the "user" package.
	AdminInverseTable = "Users"
	// AdminColumn is the table column denoting the admin relation/edge.
	AdminColumn = "admin_id"
	// ProblemSetTable is the table that holds the problem_set relation/edge.
	ProblemSetTable = "Admin_ProblemSet"
	// ProblemSetInverseTable is the table name for the ProblemSet entity.
	// It exists in this package in order to avoid circular dependency with the "problemset" package.
	ProblemSetInverseTable = "ProblemSets"
	// ProblemSetColumn is the table column denoting the problem_set relation/edge.
	ProblemSetColumn = "problem_set_id"
)

// Columns holds all SQL columns for adminproblemset fields.
var Columns = []string{
	FieldID,
	FieldAdminID,
	FieldProblemSetID,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// AdminIDValidator is a validator for the "admin_id" field. It is called by the builders before save.
	AdminIDValidator func(int) error
	// ProblemSetIDValidator is a validator for the "problem_set_id" field. It is called by the builders before save.
	ProblemSetIDValidator func(int) error
	// IDValidator is a validator for the "id" field. It is called by the builders before save.
	IDValidator func(int) error
)

// OrderOption defines the ordering options for the AdminProblemSet queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByAdminID orders the results by the admin_id field.
func ByAdminID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldAdminID, opts...).ToFunc()
}

// ByProblemSetID orders the results by the problem_set_id field.
func ByProblemSetID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldProblemSetID, opts...).ToFunc()
}

// ByAdminField orders the results by admin field.
func ByAdminField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newAdminStep(), sql.OrderByField(field, opts...))
	}
}

// ByProblemSetField orders the results by problem_set field.
func ByProblemSetField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newProblemSetStep(), sql.OrderByField(field, opts...))
	}
}
func newAdminStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(AdminInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, AdminTable, AdminColumn),
	)
}
func newProblemSetStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(ProblemSetInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, ProblemSetTable, ProblemSetColumn),
	)
}
