// Code generated by ent, DO NOT EDIT.

package adminproblemset

import (
	"cascade-oj/ent/predicate"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

// ID filters vertices based on their ID field.
func ID(id int64) predicate.AdminProblemSet {
	return predicate.AdminProblemSet(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int64) predicate.AdminProblemSet {
	return predicate.AdminProblemSet(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int64) predicate.AdminProblemSet {
	return predicate.AdminProblemSet(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int64) predicate.AdminProblemSet {
	return predicate.AdminProblemSet(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int64) predicate.AdminProblemSet {
	return predicate.AdminProblemSet(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int64) predicate.AdminProblemSet {
	return predicate.AdminProblemSet(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int64) predicate.AdminProblemSet {
	return predicate.AdminProblemSet(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int64) predicate.AdminProblemSet {
	return predicate.AdminProblemSet(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int64) predicate.AdminProblemSet {
	return predicate.AdminProblemSet(sql.FieldLTE(FieldID, id))
}

// AdminID applies equality check predicate on the "admin_id" field. It's identical to AdminIDEQ.
func AdminID(v int64) predicate.AdminProblemSet {
	return predicate.AdminProblemSet(sql.FieldEQ(FieldAdminID, v))
}

// ProblemSetID applies equality check predicate on the "problem_set_id" field. It's identical to ProblemSetIDEQ.
func ProblemSetID(v int64) predicate.AdminProblemSet {
	return predicate.AdminProblemSet(sql.FieldEQ(FieldProblemSetID, v))
}

// AdminIDEQ applies the EQ predicate on the "admin_id" field.
func AdminIDEQ(v int64) predicate.AdminProblemSet {
	return predicate.AdminProblemSet(sql.FieldEQ(FieldAdminID, v))
}

// AdminIDNEQ applies the NEQ predicate on the "admin_id" field.
func AdminIDNEQ(v int64) predicate.AdminProblemSet {
	return predicate.AdminProblemSet(sql.FieldNEQ(FieldAdminID, v))
}

// AdminIDIn applies the In predicate on the "admin_id" field.
func AdminIDIn(vs ...int64) predicate.AdminProblemSet {
	return predicate.AdminProblemSet(sql.FieldIn(FieldAdminID, vs...))
}

// AdminIDNotIn applies the NotIn predicate on the "admin_id" field.
func AdminIDNotIn(vs ...int64) predicate.AdminProblemSet {
	return predicate.AdminProblemSet(sql.FieldNotIn(FieldAdminID, vs...))
}

// ProblemSetIDEQ applies the EQ predicate on the "problem_set_id" field.
func ProblemSetIDEQ(v int64) predicate.AdminProblemSet {
	return predicate.AdminProblemSet(sql.FieldEQ(FieldProblemSetID, v))
}

// ProblemSetIDNEQ applies the NEQ predicate on the "problem_set_id" field.
func ProblemSetIDNEQ(v int64) predicate.AdminProblemSet {
	return predicate.AdminProblemSet(sql.FieldNEQ(FieldProblemSetID, v))
}

// ProblemSetIDIn applies the In predicate on the "problem_set_id" field.
func ProblemSetIDIn(vs ...int64) predicate.AdminProblemSet {
	return predicate.AdminProblemSet(sql.FieldIn(FieldProblemSetID, vs...))
}

// ProblemSetIDNotIn applies the NotIn predicate on the "problem_set_id" field.
func ProblemSetIDNotIn(vs ...int64) predicate.AdminProblemSet {
	return predicate.AdminProblemSet(sql.FieldNotIn(FieldProblemSetID, vs...))
}

// HasAdmin applies the HasEdge predicate on the "admin" edge.
func HasAdmin() predicate.AdminProblemSet {
	return predicate.AdminProblemSet(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, AdminTable, AdminColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasAdminWith applies the HasEdge predicate on the "admin" edge with a given conditions (other predicates).
func HasAdminWith(preds ...predicate.User) predicate.AdminProblemSet {
	return predicate.AdminProblemSet(func(s *sql.Selector) {
		step := newAdminStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasProblemSet applies the HasEdge predicate on the "problem_set" edge.
func HasProblemSet() predicate.AdminProblemSet {
	return predicate.AdminProblemSet(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, ProblemSetTable, ProblemSetColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasProblemSetWith applies the HasEdge predicate on the "problem_set" edge with a given conditions (other predicates).
func HasProblemSetWith(preds ...predicate.ProblemSet) predicate.AdminProblemSet {
	return predicate.AdminProblemSet(func(s *sql.Selector) {
		step := newProblemSetStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.AdminProblemSet) predicate.AdminProblemSet {
	return predicate.AdminProblemSet(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.AdminProblemSet) predicate.AdminProblemSet {
	return predicate.AdminProblemSet(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.AdminProblemSet) predicate.AdminProblemSet {
	return predicate.AdminProblemSet(sql.NotPredicates(p))
}
