// Code generated by ent, DO NOT EDIT.

package problemjudgeconfig

import (
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

const (
	// Label holds the string label denoting the problemjudgeconfig type in the database.
	Label = "problem_judge_config"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldConfigName holds the string denoting the config_name field in the database.
	FieldConfigName = "config_name"
	// FieldDescription holds the string denoting the description field in the database.
	FieldDescription = "description"
	// FieldSubmissionQueueName holds the string denoting the submission_queue_name field in the database.
	FieldSubmissionQueueName = "submission_queue_name"
	// FieldSelfTestQueueName holds the string denoting the self_test_queue_name field in the database.
	FieldSelfTestQueueName = "self_test_queue_name"
	// FieldJudgeEngine holds the string denoting the judge_engine field in the database.
	FieldJudgeEngine = "judge_engine"
	// EdgeJudgeConfig holds the string denoting the judge_config edge name in mutations.
	EdgeJudgeConfig = "judge_config"
	// Table holds the table name of the problemjudgeconfig in the database.
	Table = "Problem_JudgeConfigs"
	// JudgeConfigTable is the table that holds the judge_config relation/edge.
	JudgeConfigTable = "Problems"
	// JudgeConfigInverseTable is the table name for the Problem entity.
	// It exists in this package in order to avoid circular dependency with the "problem" package.
	JudgeConfigInverseTable = "Problems"
	// JudgeConfigColumn is the table column denoting the judge_config relation/edge.
	JudgeConfigColumn = "judge_config_id"
)

// Columns holds all SQL columns for problemjudgeconfig fields.
var Columns = []string{
	FieldID,
	FieldConfigName,
	FieldDescription,
	FieldSubmissionQueueName,
	FieldSelfTestQueueName,
	FieldJudgeEngine,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultDescription holds the default value on creation for the "description" field.
	DefaultDescription string
	// DefaultSubmissionQueueName holds the default value on creation for the "submission_queue_name" field.
	DefaultSubmissionQueueName string
	// DefaultSelfTestQueueName holds the default value on creation for the "self_test_queue_name" field.
	DefaultSelfTestQueueName string
	// DefaultJudgeEngine holds the default value on creation for the "judge_engine" field.
	DefaultJudgeEngine string
	// IDValidator is a validator for the "id" field. It is called by the builders before save.
	IDValidator func(int64) error
)

// OrderOption defines the ordering options for the ProblemJudgeConfig queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByConfigName orders the results by the config_name field.
func ByConfigName(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldConfigName, opts...).ToFunc()
}

// ByDescription orders the results by the description field.
func ByDescription(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDescription, opts...).ToFunc()
}

// BySubmissionQueueName orders the results by the submission_queue_name field.
func BySubmissionQueueName(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSubmissionQueueName, opts...).ToFunc()
}

// BySelfTestQueueName orders the results by the self_test_queue_name field.
func BySelfTestQueueName(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSelfTestQueueName, opts...).ToFunc()
}

// ByJudgeEngine orders the results by the judge_engine field.
func ByJudgeEngine(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldJudgeEngine, opts...).ToFunc()
}

// ByJudgeConfigCount orders the results by judge_config count.
func ByJudgeConfigCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newJudgeConfigStep(), opts...)
	}
}

// ByJudgeConfig orders the results by judge_config terms.
func ByJudgeConfig(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newJudgeConfigStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}
func newJudgeConfigStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(JudgeConfigInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2M, false, JudgeConfigTable, JudgeConfigColumn),
	)
}
