// Code generated by ent, DO NOT EDIT.

package ent

import (
	"cascade-oj/ent/adminproblemset"
	"cascade-oj/ent/predicate"
	"context"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// AdminProblemSetDelete is the builder for deleting a AdminProblemSet entity.
type AdminProblemSetDelete struct {
	config
	hooks    []Hook
	mutation *AdminProblemSetMutation
}

// Where appends a list predicates to the AdminProblemSetDelete builder.
func (_d *AdminProblemSetDelete) Where(ps ...predicate.AdminProblemSet) *AdminProblemSetDelete {
	_d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (_d *AdminProblemSetDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, _d.sqlExec, _d.mutation, _d.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *AdminProblemSetDelete) ExecX(ctx context.Context) int {
	n, err := _d.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (_d *AdminProblemSetDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(adminproblemset.Table, sqlgraph.NewFieldSpec(adminproblemset.FieldID, field.TypeInt64))
	if ps := _d.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, _d.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	_d.mutation.done = true
	return affected, err
}

// AdminProblemSetDeleteOne is the builder for deleting a single AdminProblemSet entity.
type AdminProblemSetDeleteOne struct {
	_d *AdminProblemSetDelete
}

// Where appends a list predicates to the AdminProblemSetDelete builder.
func (_d *AdminProblemSetDeleteOne) Where(ps ...predicate.AdminProblemSet) *AdminProblemSetDeleteOne {
	_d._d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query.
func (_d *AdminProblemSetDeleteOne) Exec(ctx context.Context) error {
	n, err := _d._d.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{adminproblemset.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *AdminProblemSetDeleteOne) ExecX(ctx context.Context) {
	if err := _d.Exec(ctx); err != nil {
		panic(err)
	}
}
