// Code generated by ent, DO NOT EDIT.

package ent

import (
	"cascade-oj/ent/alertreport"
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
)

// AlertReport is the model entity for the AlertReport schema.
type AlertReport struct {
	config `json:"-"`
	// ID of the ent.
	ID int64 `json:"id,omitempty"`
	// report title summarizing the analysis period
	Title string `json:"title,omitempty"`
	// executive summary of findings
	Summary string `json:"summary,omitempty"`
	// JSON array of identified root causes
	RootCauses string `json:"root_causes,omitempty"`
	// JSON array of suggested remediation actions
	SuggestedActions string `json:"suggested_actions,omitempty"`
	// number of alerts classified as noise
	NoiseCount int `json:"noise_count,omitempty"`
	// number of alerts classified as real risks
	RealRiskCount int `json:"real_risk_count,omitempty"`
	// Status holds the value of the "status" field.
	Status alertreport.Status `json:"status,omitempty"`
	// complete markdown report for OCEs
	FullReportMarkdown string `json:"full_report_markdown,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// time when an OCE acknowledged the report
	AcknowledgedAt *time.Time `json:"acknowledged_at,omitempty"`
	selectValues   sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*AlertReport) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case alertreport.FieldID, alertreport.FieldNoiseCount, alertreport.FieldRealRiskCount:
			values[i] = new(sql.NullInt64)
		case alertreport.FieldTitle, alertreport.FieldSummary, alertreport.FieldRootCauses, alertreport.FieldSuggestedActions, alertreport.FieldStatus, alertreport.FieldFullReportMarkdown:
			values[i] = new(sql.NullString)
		case alertreport.FieldCreatedAt, alertreport.FieldAcknowledgedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the AlertReport fields.
func (_m *AlertReport) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case alertreport.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int64(value.Int64)
		case alertreport.FieldTitle:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field title", values[i])
			} else if value.Valid {
				_m.Title = value.String
			}
		case alertreport.FieldSummary:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field summary", values[i])
			} else if value.Valid {
				_m.Summary = value.String
			}
		case alertreport.FieldRootCauses:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field root_causes", values[i])
			} else if value.Valid {
				_m.RootCauses = value.String
			}
		case alertreport.FieldSuggestedActions:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field suggested_actions", values[i])
			} else if value.Valid {
				_m.SuggestedActions = value.String
			}
		case alertreport.FieldNoiseCount:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field noise_count", values[i])
			} else if value.Valid {
				_m.NoiseCount = int(value.Int64)
			}
		case alertreport.FieldRealRiskCount:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field real_risk_count", values[i])
			} else if value.Valid {
				_m.RealRiskCount = int(value.Int64)
			}
		case alertreport.FieldStatus:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field status", values[i])
			} else if value.Valid {
				_m.Status = alertreport.Status(value.String)
			}
		case alertreport.FieldFullReportMarkdown:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field full_report_markdown", values[i])
			} else if value.Valid {
				_m.FullReportMarkdown = value.String
			}
		case alertreport.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case alertreport.FieldAcknowledgedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field acknowledged_at", values[i])
			} else if value.Valid {
				_m.AcknowledgedAt = new(time.Time)
				*_m.AcknowledgedAt = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the AlertReport.
// This includes values selected through modifiers, order, etc.
func (_m *AlertReport) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// Update returns a builder for updating this AlertReport.
// Note that you need to call AlertReport.Unwrap() before calling this method if this AlertReport
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *AlertReport) Update() *AlertReportUpdateOne {
	return NewAlertReportClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the AlertReport entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *AlertReport) Unwrap() *AlertReport {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: AlertReport is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *AlertReport) String() string {
	var builder strings.Builder
	builder.WriteString("AlertReport(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("title=")
	builder.WriteString(_m.Title)
	builder.WriteString(", ")
	builder.WriteString("summary=")
	builder.WriteString(_m.Summary)
	builder.WriteString(", ")
	builder.WriteString("root_causes=")
	builder.WriteString(_m.RootCauses)
	builder.WriteString(", ")
	builder.WriteString("suggested_actions=")
	builder.WriteString(_m.SuggestedActions)
	builder.WriteString(", ")
	builder.WriteString("noise_count=")
	builder.WriteString(fmt.Sprintf("%v", _m.NoiseCount))
	builder.WriteString(", ")
	builder.WriteString("real_risk_count=")
	builder.WriteString(fmt.Sprintf("%v", _m.RealRiskCount))
	builder.WriteString(", ")
	builder.WriteString("status=")
	builder.WriteString(fmt.Sprintf("%v", _m.Status))
	builder.WriteString(", ")
	builder.WriteString("full_report_markdown=")
	builder.WriteString(_m.FullReportMarkdown)
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	if v := _m.AcknowledgedAt; v != nil {
		builder.WriteString("acknowledged_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteByte(')')
	return builder.String()
}

// AlertReports is a parsable slice of AlertReport.
type AlertReports []*AlertReport
