// Code generated by ent, DO NOT EDIT.

package ent

import (
	"cascade-oj/ent/alertreport"
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// AlertReportCreate is the builder for creating a AlertReport entity.
type AlertReportCreate struct {
	config
	mutation *AlertReportMutation
	hooks    []Hook
}

// SetTitle sets the "title" field.
func (_c *AlertReportCreate) SetTitle(v string) *AlertReportCreate {
	_c.mutation.SetTitle(v)
	return _c
}

// SetSummary sets the "summary" field.
func (_c *AlertReportCreate) SetSummary(v string) *AlertReportCreate {
	_c.mutation.SetSummary(v)
	return _c
}

// SetRootCauses sets the "root_causes" field.
func (_c *AlertReportCreate) SetRootCauses(v string) *AlertReportCreate {
	_c.mutation.SetRootCauses(v)
	return _c
}

// SetSuggestedActions sets the "suggested_actions" field.
func (_c *AlertReportCreate) SetSuggestedActions(v string) *AlertReportCreate {
	_c.mutation.SetSuggestedActions(v)
	return _c
}

// SetNoiseCount sets the "noise_count" field.
func (_c *AlertReportCreate) SetNoiseCount(v int) *AlertReportCreate {
	_c.mutation.SetNoiseCount(v)
	return _c
}

// SetNillableNoiseCount sets the "noise_count" field if the given value is not nil.
func (_c *AlertReportCreate) SetNillableNoiseCount(v *int) *AlertReportCreate {
	if v != nil {
		_c.SetNoiseCount(*v)
	}
	return _c
}

// SetRealRiskCount sets the "real_risk_count" field.
func (_c *AlertReportCreate) SetRealRiskCount(v int) *AlertReportCreate {
	_c.mutation.SetRealRiskCount(v)
	return _c
}

// SetNillableRealRiskCount sets the "real_risk_count" field if the given value is not nil.
func (_c *AlertReportCreate) SetNillableRealRiskCount(v *int) *AlertReportCreate {
	if v != nil {
		_c.SetRealRiskCount(*v)
	}
	return _c
}

// SetStatus sets the "status" field.
func (_c *AlertReportCreate) SetStatus(v alertreport.Status) *AlertReportCreate {
	_c.mutation.SetStatus(v)
	return _c
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_c *AlertReportCreate) SetNillableStatus(v *alertreport.Status) *AlertReportCreate {
	if v != nil {
		_c.SetStatus(*v)
	}
	return _c
}

// SetFullReportMarkdown sets the "full_report_markdown" field.
func (_c *AlertReportCreate) SetFullReportMarkdown(v string) *AlertReportCreate {
	_c.mutation.SetFullReportMarkdown(v)
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *AlertReportCreate) SetCreatedAt(v time.Time) *AlertReportCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *AlertReportCreate) SetNillableCreatedAt(v *time.Time) *AlertReportCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetAcknowledgedAt sets the "acknowledged_at" field.
func (_c *AlertReportCreate) SetAcknowledgedAt(v time.Time) *AlertReportCreate {
	_c.mutation.SetAcknowledgedAt(v)
	return _c
}

// SetNillableAcknowledgedAt sets the "acknowledged_at" field if the given value is not nil.
func (_c *AlertReportCreate) SetNillableAcknowledgedAt(v *time.Time) *AlertReportCreate {
	if v != nil {
		_c.SetAcknowledgedAt(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *AlertReportCreate) SetID(v int64) *AlertReportCreate {
	_c.mutation.SetID(v)
	return _c
}

// Mutation returns the AlertReportMutation object of the builder.
func (_c *AlertReportCreate) Mutation() *AlertReportMutation {
	return _c.mutation
}

// Save creates the AlertReport in the database.
func (_c *AlertReportCreate) Save(ctx context.Context) (*AlertReport, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *AlertReportCreate) SaveX(ctx context.Context) *AlertReport {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *AlertReportCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *AlertReportCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *AlertReportCreate) defaults() {
	if _, ok := _c.mutation.NoiseCount(); !ok {
		v := alertreport.DefaultNoiseCount
		_c.mutation.SetNoiseCount(v)
	}
	if _, ok := _c.mutation.RealRiskCount(); !ok {
		v := alertreport.DefaultRealRiskCount
		_c.mutation.SetRealRiskCount(v)
	}
	if _, ok := _c.mutation.Status(); !ok {
		v := alertreport.DefaultStatus
		_c.mutation.SetStatus(v)
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := alertreport.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *AlertReportCreate) check() error {
	if _, ok := _c.mutation.Title(); !ok {
		return &ValidationError{Name: "title", err: errors.New(`ent: missing required field "AlertReport.title"`)}
	}
	if v, ok := _c.mutation.Title(); ok {
		if err := alertreport.TitleValidator(v); err != nil {
			return &ValidationError{Name: "title", err: fmt.Errorf(`ent: validator failed for field "AlertReport.title": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Summary(); !ok {
		return &ValidationError{Name: "summary", err: errors.New(`ent: missing required field "AlertReport.summary"`)}
	}
	if v, ok := _c.mutation.Summary(); ok {
		if err := alertreport.SummaryValidator(v); err != nil {
			return &ValidationError{Name: "summary", err: fmt.Errorf(`ent: validator failed for field "AlertReport.summary": %w`, err)}
		}
	}
	if _, ok := _c.mutation.RootCauses(); !ok {
		return &ValidationError{Name: "root_causes", err: errors.New(`ent: missing required field "AlertReport.root_causes"`)}
	}
	if _, ok := _c.mutation.SuggestedActions(); !ok {
		return &ValidationError{Name: "suggested_actions", err: errors.New(`ent: missing required field "AlertReport.suggested_actions"`)}
	}
	if _, ok := _c.mutation.NoiseCount(); !ok {
		return &ValidationError{Name: "noise_count", err: errors.New(`ent: missing required field "AlertReport.noise_count"`)}
	}
	if _, ok := _c.mutation.RealRiskCount(); !ok {
		return &ValidationError{Name: "real_risk_count", err: errors.New(`ent: missing required field "AlertReport.real_risk_count"`)}
	}
	if _, ok := _c.mutation.Status(); !ok {
		return &ValidationError{Name: "status", err: errors.New(`ent: missing required field "AlertReport.status"`)}
	}
	if v, ok := _c.mutation.Status(); ok {
		if err := alertreport.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "AlertReport.status": %w`, err)}
		}
	}
	if _, ok := _c.mutation.FullReportMarkdown(); !ok {
		return &ValidationError{Name: "full_report_markdown", err: errors.New(`ent: missing required field "AlertReport.full_report_markdown"`)}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "AlertReport.created_at"`)}
	}
	if v, ok := _c.mutation.ID(); ok {
		if err := alertreport.IDValidator(v); err != nil {
			return &ValidationError{Name: "id", err: fmt.Errorf(`ent: validator failed for field "AlertReport.id": %w`, err)}
		}
	}
	return nil
}

func (_c *AlertReportCreate) sqlSave(ctx context.Context) (*AlertReport, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != _node.ID {
		id := _spec.ID.Value.(int64)
		_node.ID = int64(id)
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *AlertReportCreate) createSpec() (*AlertReport, *sqlgraph.CreateSpec) {
	var (
		_node = &AlertReport{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(alertreport.Table, sqlgraph.NewFieldSpec(alertreport.FieldID, field.TypeInt64))
	)
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = id
	}
	if value, ok := _c.mutation.Title(); ok {
		_spec.SetField(alertreport.FieldTitle, field.TypeString, value)
		_node.Title = value
	}
	if value, ok := _c.mutation.Summary(); ok {
		_spec.SetField(alertreport.FieldSummary, field.TypeString, value)
		_node.Summary = value
	}
	if value, ok := _c.mutation.RootCauses(); ok {
		_spec.SetField(alertreport.FieldRootCauses, field.TypeString, value)
		_node.RootCauses = value
	}
	if value, ok := _c.mutation.SuggestedActions(); ok {
		_spec.SetField(alertreport.FieldSuggestedActions, field.TypeString, value)
		_node.SuggestedActions = value
	}
	if value, ok := _c.mutation.NoiseCount(); ok {
		_spec.SetField(alertreport.FieldNoiseCount, field.TypeInt, value)
		_node.NoiseCount = value
	}
	if value, ok := _c.mutation.RealRiskCount(); ok {
		_spec.SetField(alertreport.FieldRealRiskCount, field.TypeInt, value)
		_node.RealRiskCount = value
	}
	if value, ok := _c.mutation.Status(); ok {
		_spec.SetField(alertreport.FieldStatus, field.TypeEnum, value)
		_node.Status = value
	}
	if value, ok := _c.mutation.FullReportMarkdown(); ok {
		_spec.SetField(alertreport.FieldFullReportMarkdown, field.TypeString, value)
		_node.FullReportMarkdown = value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(alertreport.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.AcknowledgedAt(); ok {
		_spec.SetField(alertreport.FieldAcknowledgedAt, field.TypeTime, value)
		_node.AcknowledgedAt = &value
	}
	return _node, _spec
}

// AlertReportCreateBulk is the builder for creating many AlertReport entities in bulk.
type AlertReportCreateBulk struct {
	config
	err      error
	builders []*AlertReportCreate
}

// Save creates the AlertReport entities in the database.
func (_c *AlertReportCreateBulk) Save(ctx context.Context) ([]*AlertReport, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*AlertReport, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*AlertReportMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil && nodes[i].ID == 0 {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int64(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *AlertReportCreateBulk) SaveX(ctx context.Context) []*AlertReport {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *AlertReportCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *AlertReportCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
