// Code generated by ent, DO NOT EDIT.

package ent

import (
	"cascade-oj/ent/casegroupresult"
	"cascade-oj/ent/caseresult"
	"cascade-oj/ent/predicate"
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// CaseResultUpdate is the builder for updating CaseResult entities.
type CaseResultUpdate struct {
	config
	hooks    []Hook
	mutation *CaseResultMutation
}

// Where appends a list predicates to the CaseResultUpdate builder.
func (_u *CaseResultUpdate) Where(ps ...predicate.CaseResult) *CaseResultUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetCaseGroupResultID sets the "case_group_result_id" field.
func (_u *CaseResultUpdate) SetCaseGroupResultID(v int64) *CaseResultUpdate {
	_u.mutation.SetCaseGroupResultID(v)
	return _u
}

// SetNillableCaseGroupResultID sets the "case_group_result_id" field if the given value is not nil.
func (_u *CaseResultUpdate) SetNillableCaseGroupResultID(v *int64) *CaseResultUpdate {
	if v != nil {
		_u.SetCaseGroupResultID(*v)
	}
	return _u
}

// SetStatus sets the "status" field.
func (_u *CaseResultUpdate) SetStatus(v int16) *CaseResultUpdate {
	_u.mutation.ResetStatus()
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *CaseResultUpdate) SetNillableStatus(v *int16) *CaseResultUpdate {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// AddStatus adds value to the "status" field.
func (_u *CaseResultUpdate) AddStatus(v int16) *CaseResultUpdate {
	_u.mutation.AddStatus(v)
	return _u
}

// SetTimeCostMs sets the "time_cost_ms" field.
func (_u *CaseResultUpdate) SetTimeCostMs(v uint64) *CaseResultUpdate {
	_u.mutation.ResetTimeCostMs()
	_u.mutation.SetTimeCostMs(v)
	return _u
}

// SetNillableTimeCostMs sets the "time_cost_ms" field if the given value is not nil.
func (_u *CaseResultUpdate) SetNillableTimeCostMs(v *uint64) *CaseResultUpdate {
	if v != nil {
		_u.SetTimeCostMs(*v)
	}
	return _u
}

// AddTimeCostMs adds value to the "time_cost_ms" field.
func (_u *CaseResultUpdate) AddTimeCostMs(v int64) *CaseResultUpdate {
	_u.mutation.AddTimeCostMs(v)
	return _u
}

// SetMemoryCostKB sets the "memory_cost_kb" field.
func (_u *CaseResultUpdate) SetMemoryCostKB(v uint64) *CaseResultUpdate {
	_u.mutation.ResetMemoryCostKB()
	_u.mutation.SetMemoryCostKB(v)
	return _u
}

// SetNillableMemoryCostKB sets the "memory_cost_kb" field if the given value is not nil.
func (_u *CaseResultUpdate) SetNillableMemoryCostKB(v *uint64) *CaseResultUpdate {
	if v != nil {
		_u.SetMemoryCostKB(*v)
	}
	return _u
}

// AddMemoryCostKB adds value to the "memory_cost_kb" field.
func (_u *CaseResultUpdate) AddMemoryCostKB(v int64) *CaseResultUpdate {
	_u.mutation.AddMemoryCostKB(v)
	return _u
}

// SetStdout sets the "stdout" field.
func (_u *CaseResultUpdate) SetStdout(v string) *CaseResultUpdate {
	_u.mutation.SetStdout(v)
	return _u
}

// SetNillableStdout sets the "stdout" field if the given value is not nil.
func (_u *CaseResultUpdate) SetNillableStdout(v *string) *CaseResultUpdate {
	if v != nil {
		_u.SetStdout(*v)
	}
	return _u
}

// SetStderr sets the "stderr" field.
func (_u *CaseResultUpdate) SetStderr(v string) *CaseResultUpdate {
	_u.mutation.SetStderr(v)
	return _u
}

// SetNillableStderr sets the "stderr" field if the given value is not nil.
func (_u *CaseResultUpdate) SetNillableStderr(v *string) *CaseResultUpdate {
	if v != nil {
		_u.SetStderr(*v)
	}
	return _u
}

// SetScore sets the "score" field.
func (_u *CaseResultUpdate) SetScore(v int) *CaseResultUpdate {
	_u.mutation.ResetScore()
	_u.mutation.SetScore(v)
	return _u
}

// SetNillableScore sets the "score" field if the given value is not nil.
func (_u *CaseResultUpdate) SetNillableScore(v *int) *CaseResultUpdate {
	if v != nil {
		_u.SetScore(*v)
	}
	return _u
}

// AddScore adds value to the "score" field.
func (_u *CaseResultUpdate) AddScore(v int) *CaseResultUpdate {
	_u.mutation.AddScore(v)
	return _u
}

// SetCaseGroupResult sets the "case_group_result" edge to the CaseGroupResult entity.
func (_u *CaseResultUpdate) SetCaseGroupResult(v *CaseGroupResult) *CaseResultUpdate {
	return _u.SetCaseGroupResultID(v.ID)
}

// Mutation returns the CaseResultMutation object of the builder.
func (_u *CaseResultUpdate) Mutation() *CaseResultMutation {
	return _u.mutation
}

// ClearCaseGroupResult clears the "case_group_result" edge to the CaseGroupResult entity.
func (_u *CaseResultUpdate) ClearCaseGroupResult() *CaseResultUpdate {
	_u.mutation.ClearCaseGroupResult()
	return _u
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *CaseResultUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *CaseResultUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *CaseResultUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *CaseResultUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *CaseResultUpdate) check() error {
	if _u.mutation.CaseGroupResultCleared() && len(_u.mutation.CaseGroupResultIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "CaseResult.case_group_result"`)
	}
	return nil
}

func (_u *CaseResultUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(caseresult.Table, caseresult.Columns, sqlgraph.NewFieldSpec(caseresult.FieldID, field.TypeInt64))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(caseresult.FieldStatus, field.TypeInt16, value)
	}
	if value, ok := _u.mutation.AddedStatus(); ok {
		_spec.AddField(caseresult.FieldStatus, field.TypeInt16, value)
	}
	if value, ok := _u.mutation.TimeCostMs(); ok {
		_spec.SetField(caseresult.FieldTimeCostMs, field.TypeUint64, value)
	}
	if value, ok := _u.mutation.AddedTimeCostMs(); ok {
		_spec.AddField(caseresult.FieldTimeCostMs, field.TypeUint64, value)
	}
	if value, ok := _u.mutation.MemoryCostKB(); ok {
		_spec.SetField(caseresult.FieldMemoryCostKB, field.TypeUint64, value)
	}
	if value, ok := _u.mutation.AddedMemoryCostKB(); ok {
		_spec.AddField(caseresult.FieldMemoryCostKB, field.TypeUint64, value)
	}
	if value, ok := _u.mutation.Stdout(); ok {
		_spec.SetField(caseresult.FieldStdout, field.TypeString, value)
	}
	if value, ok := _u.mutation.Stderr(); ok {
		_spec.SetField(caseresult.FieldStderr, field.TypeString, value)
	}
	if value, ok := _u.mutation.Score(); ok {
		_spec.SetField(caseresult.FieldScore, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedScore(); ok {
		_spec.AddField(caseresult.FieldScore, field.TypeInt, value)
	}
	if _u.mutation.CaseGroupResultCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   caseresult.CaseGroupResultTable,
			Columns: []string{caseresult.CaseGroupResultColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(casegroupresult.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.CaseGroupResultIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   caseresult.CaseGroupResultTable,
			Columns: []string{caseresult.CaseGroupResultColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(casegroupresult.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{caseresult.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// CaseResultUpdateOne is the builder for updating a single CaseResult entity.
type CaseResultUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *CaseResultMutation
}

// SetCaseGroupResultID sets the "case_group_result_id" field.
func (_u *CaseResultUpdateOne) SetCaseGroupResultID(v int64) *CaseResultUpdateOne {
	_u.mutation.SetCaseGroupResultID(v)
	return _u
}

// SetNillableCaseGroupResultID sets the "case_group_result_id" field if the given value is not nil.
func (_u *CaseResultUpdateOne) SetNillableCaseGroupResultID(v *int64) *CaseResultUpdateOne {
	if v != nil {
		_u.SetCaseGroupResultID(*v)
	}
	return _u
}

// SetStatus sets the "status" field.
func (_u *CaseResultUpdateOne) SetStatus(v int16) *CaseResultUpdateOne {
	_u.mutation.ResetStatus()
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *CaseResultUpdateOne) SetNillableStatus(v *int16) *CaseResultUpdateOne {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// AddStatus adds value to the "status" field.
func (_u *CaseResultUpdateOne) AddStatus(v int16) *CaseResultUpdateOne {
	_u.mutation.AddStatus(v)
	return _u
}

// SetTimeCostMs sets the "time_cost_ms" field.
func (_u *CaseResultUpdateOne) SetTimeCostMs(v uint64) *CaseResultUpdateOne {
	_u.mutation.ResetTimeCostMs()
	_u.mutation.SetTimeCostMs(v)
	return _u
}

// SetNillableTimeCostMs sets the "time_cost_ms" field if the given value is not nil.
func (_u *CaseResultUpdateOne) SetNillableTimeCostMs(v *uint64) *CaseResultUpdateOne {
	if v != nil {
		_u.SetTimeCostMs(*v)
	}
	return _u
}

// AddTimeCostMs adds value to the "time_cost_ms" field.
func (_u *CaseResultUpdateOne) AddTimeCostMs(v int64) *CaseResultUpdateOne {
	_u.mutation.AddTimeCostMs(v)
	return _u
}

// SetMemoryCostKB sets the "memory_cost_kb" field.
func (_u *CaseResultUpdateOne) SetMemoryCostKB(v uint64) *CaseResultUpdateOne {
	_u.mutation.ResetMemoryCostKB()
	_u.mutation.SetMemoryCostKB(v)
	return _u
}

// SetNillableMemoryCostKB sets the "memory_cost_kb" field if the given value is not nil.
func (_u *CaseResultUpdateOne) SetNillableMemoryCostKB(v *uint64) *CaseResultUpdateOne {
	if v != nil {
		_u.SetMemoryCostKB(*v)
	}
	return _u
}

// AddMemoryCostKB adds value to the "memory_cost_kb" field.
func (_u *CaseResultUpdateOne) AddMemoryCostKB(v int64) *CaseResultUpdateOne {
	_u.mutation.AddMemoryCostKB(v)
	return _u
}

// SetStdout sets the "stdout" field.
func (_u *CaseResultUpdateOne) SetStdout(v string) *CaseResultUpdateOne {
	_u.mutation.SetStdout(v)
	return _u
}

// SetNillableStdout sets the "stdout" field if the given value is not nil.
func (_u *CaseResultUpdateOne) SetNillableStdout(v *string) *CaseResultUpdateOne {
	if v != nil {
		_u.SetStdout(*v)
	}
	return _u
}

// SetStderr sets the "stderr" field.
func (_u *CaseResultUpdateOne) SetStderr(v string) *CaseResultUpdateOne {
	_u.mutation.SetStderr(v)
	return _u
}

// SetNillableStderr sets the "stderr" field if the given value is not nil.
func (_u *CaseResultUpdateOne) SetNillableStderr(v *string) *CaseResultUpdateOne {
	if v != nil {
		_u.SetStderr(*v)
	}
	return _u
}

// SetScore sets the "score" field.
func (_u *CaseResultUpdateOne) SetScore(v int) *CaseResultUpdateOne {
	_u.mutation.ResetScore()
	_u.mutation.SetScore(v)
	return _u
}

// SetNillableScore sets the "score" field if the given value is not nil.
func (_u *CaseResultUpdateOne) SetNillableScore(v *int) *CaseResultUpdateOne {
	if v != nil {
		_u.SetScore(*v)
	}
	return _u
}

// AddScore adds value to the "score" field.
func (_u *CaseResultUpdateOne) AddScore(v int) *CaseResultUpdateOne {
	_u.mutation.AddScore(v)
	return _u
}

// SetCaseGroupResult sets the "case_group_result" edge to the CaseGroupResult entity.
func (_u *CaseResultUpdateOne) SetCaseGroupResult(v *CaseGroupResult) *CaseResultUpdateOne {
	return _u.SetCaseGroupResultID(v.ID)
}

// Mutation returns the CaseResultMutation object of the builder.
func (_u *CaseResultUpdateOne) Mutation() *CaseResultMutation {
	return _u.mutation
}

// ClearCaseGroupResult clears the "case_group_result" edge to the CaseGroupResult entity.
func (_u *CaseResultUpdateOne) ClearCaseGroupResult() *CaseResultUpdateOne {
	_u.mutation.ClearCaseGroupResult()
	return _u
}

// Where appends a list predicates to the CaseResultUpdate builder.
func (_u *CaseResultUpdateOne) Where(ps ...predicate.CaseResult) *CaseResultUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *CaseResultUpdateOne) Select(field string, fields ...string) *CaseResultUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated CaseResult entity.
func (_u *CaseResultUpdateOne) Save(ctx context.Context) (*CaseResult, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *CaseResultUpdateOne) SaveX(ctx context.Context) *CaseResult {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *CaseResultUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *CaseResultUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *CaseResultUpdateOne) check() error {
	if _u.mutation.CaseGroupResultCleared() && len(_u.mutation.CaseGroupResultIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "CaseResult.case_group_result"`)
	}
	return nil
}

func (_u *CaseResultUpdateOne) sqlSave(ctx context.Context) (_node *CaseResult, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(caseresult.Table, caseresult.Columns, sqlgraph.NewFieldSpec(caseresult.FieldID, field.TypeInt64))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "CaseResult.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, caseresult.FieldID)
		for _, f := range fields {
			if !caseresult.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != caseresult.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(caseresult.FieldStatus, field.TypeInt16, value)
	}
	if value, ok := _u.mutation.AddedStatus(); ok {
		_spec.AddField(caseresult.FieldStatus, field.TypeInt16, value)
	}
	if value, ok := _u.mutation.TimeCostMs(); ok {
		_spec.SetField(caseresult.FieldTimeCostMs, field.TypeUint64, value)
	}
	if value, ok := _u.mutation.AddedTimeCostMs(); ok {
		_spec.AddField(caseresult.FieldTimeCostMs, field.TypeUint64, value)
	}
	if value, ok := _u.mutation.MemoryCostKB(); ok {
		_spec.SetField(caseresult.FieldMemoryCostKB, field.TypeUint64, value)
	}
	if value, ok := _u.mutation.AddedMemoryCostKB(); ok {
		_spec.AddField(caseresult.FieldMemoryCostKB, field.TypeUint64, value)
	}
	if value, ok := _u.mutation.Stdout(); ok {
		_spec.SetField(caseresult.FieldStdout, field.TypeString, value)
	}
	if value, ok := _u.mutation.Stderr(); ok {
		_spec.SetField(caseresult.FieldStderr, field.TypeString, value)
	}
	if value, ok := _u.mutation.Score(); ok {
		_spec.SetField(caseresult.FieldScore, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedScore(); ok {
		_spec.AddField(caseresult.FieldScore, field.TypeInt, value)
	}
	if _u.mutation.CaseGroupResultCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   caseresult.CaseGroupResultTable,
			Columns: []string{caseresult.CaseGroupResultColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(casegroupresult.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.CaseGroupResultIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   caseresult.CaseGroupResultTable,
			Columns: []string{caseresult.CaseGroupResultColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(casegroupresult.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &CaseResult{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{caseresult.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
