// Code generated by ent, DO NOT EDIT.

package ent

import (
	"cascade-oj/ent/casegroupresult"
	"cascade-oj/ent/caseresult"
	"cascade-oj/ent/predicate"
	"cascade-oj/ent/problem"
	"cascade-oj/ent/submissionrecord"
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// CaseGroupResultUpdate is the builder for updating CaseGroupResult entities.
type CaseGroupResultUpdate struct {
	config
	hooks    []Hook
	mutation *CaseGroupResultMutation
}

// Where appends a list predicates to the CaseGroupResultUpdate builder.
func (_u *CaseGroupResultUpdate) Where(ps ...predicate.CaseGroupResult) *CaseGroupResultUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetSubmissionID sets the "submission_id" field.
func (_u *CaseGroupResultUpdate) SetSubmissionID(v int64) *CaseGroupResultUpdate {
	_u.mutation.SetSubmissionID(v)
	return _u
}

// SetNillableSubmissionID sets the "submission_id" field if the given value is not nil.
func (_u *CaseGroupResultUpdate) SetNillableSubmissionID(v *int64) *CaseGroupResultUpdate {
	if v != nil {
		_u.SetSubmissionID(*v)
	}
	return _u
}

// SetStatus sets the "status" field.
func (_u *CaseGroupResultUpdate) SetStatus(v int16) *CaseGroupResultUpdate {
	_u.mutation.ResetStatus()
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *CaseGroupResultUpdate) SetNillableStatus(v *int16) *CaseGroupResultUpdate {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// AddStatus adds value to the "status" field.
func (_u *CaseGroupResultUpdate) AddStatus(v int16) *CaseGroupResultUpdate {
	_u.mutation.AddStatus(v)
	return _u
}

// SetTotalTimeCostMs sets the "total_time_cost_ms" field.
func (_u *CaseGroupResultUpdate) SetTotalTimeCostMs(v uint64) *CaseGroupResultUpdate {
	_u.mutation.ResetTotalTimeCostMs()
	_u.mutation.SetTotalTimeCostMs(v)
	return _u
}

// SetNillableTotalTimeCostMs sets the "total_time_cost_ms" field if the given value is not nil.
func (_u *CaseGroupResultUpdate) SetNillableTotalTimeCostMs(v *uint64) *CaseGroupResultUpdate {
	if v != nil {
		_u.SetTotalTimeCostMs(*v)
	}
	return _u
}

// AddTotalTimeCostMs adds value to the "total_time_cost_ms" field.
func (_u *CaseGroupResultUpdate) AddTotalTimeCostMs(v int64) *CaseGroupResultUpdate {
	_u.mutation.AddTotalTimeCostMs(v)
	return _u
}

// SetMaxMemoryCostKB sets the "max_memory_cost_kb" field.
func (_u *CaseGroupResultUpdate) SetMaxMemoryCostKB(v uint64) *CaseGroupResultUpdate {
	_u.mutation.ResetMaxMemoryCostKB()
	_u.mutation.SetMaxMemoryCostKB(v)
	return _u
}

// SetNillableMaxMemoryCostKB sets the "max_memory_cost_kb" field if the given value is not nil.
func (_u *CaseGroupResultUpdate) SetNillableMaxMemoryCostKB(v *uint64) *CaseGroupResultUpdate {
	if v != nil {
		_u.SetMaxMemoryCostKB(*v)
	}
	return _u
}

// AddMaxMemoryCostKB adds value to the "max_memory_cost_kb" field.
func (_u *CaseGroupResultUpdate) AddMaxMemoryCostKB(v int64) *CaseGroupResultUpdate {
	_u.mutation.AddMaxMemoryCostKB(v)
	return _u
}

// SetScore sets the "score" field.
func (_u *CaseGroupResultUpdate) SetScore(v int) *CaseGroupResultUpdate {
	_u.mutation.ResetScore()
	_u.mutation.SetScore(v)
	return _u
}

// SetNillableScore sets the "score" field if the given value is not nil.
func (_u *CaseGroupResultUpdate) SetNillableScore(v *int) *CaseGroupResultUpdate {
	if v != nil {
		_u.SetScore(*v)
	}
	return _u
}

// AddScore adds value to the "score" field.
func (_u *CaseGroupResultUpdate) AddScore(v int) *CaseGroupResultUpdate {
	_u.mutation.AddScore(v)
	return _u
}

// AddProblemIDs adds the "problem" edge to the Problem entity by IDs.
func (_u *CaseGroupResultUpdate) AddProblemIDs(ids ...int64) *CaseGroupResultUpdate {
	_u.mutation.AddProblemIDs(ids...)
	return _u
}

// AddProblem adds the "problem" edges to the Problem entity.
func (_u *CaseGroupResultUpdate) AddProblem(v ...*Problem) *CaseGroupResultUpdate {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddProblemIDs(ids...)
}

// AddCaseResultIDs adds the "case_results" edge to the CaseResult entity by IDs.
func (_u *CaseGroupResultUpdate) AddCaseResultIDs(ids ...int64) *CaseGroupResultUpdate {
	_u.mutation.AddCaseResultIDs(ids...)
	return _u
}

// AddCaseResults adds the "case_results" edges to the CaseResult entity.
func (_u *CaseGroupResultUpdate) AddCaseResults(v ...*CaseResult) *CaseGroupResultUpdate {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddCaseResultIDs(ids...)
}

// SetSubmissionRecordID sets the "submission_record" edge to the SubmissionRecord entity by ID.
func (_u *CaseGroupResultUpdate) SetSubmissionRecordID(id int64) *CaseGroupResultUpdate {
	_u.mutation.SetSubmissionRecordID(id)
	return _u
}

// SetSubmissionRecord sets the "submission_record" edge to the SubmissionRecord entity.
func (_u *CaseGroupResultUpdate) SetSubmissionRecord(v *SubmissionRecord) *CaseGroupResultUpdate {
	return _u.SetSubmissionRecordID(v.ID)
}

// Mutation returns the CaseGroupResultMutation object of the builder.
func (_u *CaseGroupResultUpdate) Mutation() *CaseGroupResultMutation {
	return _u.mutation
}

// ClearProblem clears all "problem" edges to the Problem entity.
func (_u *CaseGroupResultUpdate) ClearProblem() *CaseGroupResultUpdate {
	_u.mutation.ClearProblem()
	return _u
}

// RemoveProblemIDs removes the "problem" edge to Problem entities by IDs.
func (_u *CaseGroupResultUpdate) RemoveProblemIDs(ids ...int64) *CaseGroupResultUpdate {
	_u.mutation.RemoveProblemIDs(ids...)
	return _u
}

// RemoveProblem removes "problem" edges to Problem entities.
func (_u *CaseGroupResultUpdate) RemoveProblem(v ...*Problem) *CaseGroupResultUpdate {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveProblemIDs(ids...)
}

// ClearCaseResults clears all "case_results" edges to the CaseResult entity.
func (_u *CaseGroupResultUpdate) ClearCaseResults() *CaseGroupResultUpdate {
	_u.mutation.ClearCaseResults()
	return _u
}

// RemoveCaseResultIDs removes the "case_results" edge to CaseResult entities by IDs.
func (_u *CaseGroupResultUpdate) RemoveCaseResultIDs(ids ...int64) *CaseGroupResultUpdate {
	_u.mutation.RemoveCaseResultIDs(ids...)
	return _u
}

// RemoveCaseResults removes "case_results" edges to CaseResult entities.
func (_u *CaseGroupResultUpdate) RemoveCaseResults(v ...*CaseResult) *CaseGroupResultUpdate {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveCaseResultIDs(ids...)
}

// ClearSubmissionRecord clears the "submission_record" edge to the SubmissionRecord entity.
func (_u *CaseGroupResultUpdate) ClearSubmissionRecord() *CaseGroupResultUpdate {
	_u.mutation.ClearSubmissionRecord()
	return _u
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *CaseGroupResultUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *CaseGroupResultUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *CaseGroupResultUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *CaseGroupResultUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *CaseGroupResultUpdate) check() error {
	if _u.mutation.SubmissionRecordCleared() && len(_u.mutation.SubmissionRecordIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "CaseGroupResult.submission_record"`)
	}
	return nil
}

func (_u *CaseGroupResultUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(casegroupresult.Table, casegroupresult.Columns, sqlgraph.NewFieldSpec(casegroupresult.FieldID, field.TypeInt64))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(casegroupresult.FieldStatus, field.TypeInt16, value)
	}
	if value, ok := _u.mutation.AddedStatus(); ok {
		_spec.AddField(casegroupresult.FieldStatus, field.TypeInt16, value)
	}
	if value, ok := _u.mutation.TotalTimeCostMs(); ok {
		_spec.SetField(casegroupresult.FieldTotalTimeCostMs, field.TypeUint64, value)
	}
	if value, ok := _u.mutation.AddedTotalTimeCostMs(); ok {
		_spec.AddField(casegroupresult.FieldTotalTimeCostMs, field.TypeUint64, value)
	}
	if value, ok := _u.mutation.MaxMemoryCostKB(); ok {
		_spec.SetField(casegroupresult.FieldMaxMemoryCostKB, field.TypeUint64, value)
	}
	if value, ok := _u.mutation.AddedMaxMemoryCostKB(); ok {
		_spec.AddField(casegroupresult.FieldMaxMemoryCostKB, field.TypeUint64, value)
	}
	if value, ok := _u.mutation.Score(); ok {
		_spec.SetField(casegroupresult.FieldScore, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedScore(); ok {
		_spec.AddField(casegroupresult.FieldScore, field.TypeInt, value)
	}
	if _u.mutation.ProblemCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   casegroupresult.ProblemTable,
			Columns: []string{casegroupresult.ProblemColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(problem.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedProblemIDs(); len(nodes) > 0 && !_u.mutation.ProblemCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   casegroupresult.ProblemTable,
			Columns: []string{casegroupresult.ProblemColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(problem.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ProblemIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   casegroupresult.ProblemTable,
			Columns: []string{casegroupresult.ProblemColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(problem.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.CaseResultsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   casegroupresult.CaseResultsTable,
			Columns: []string{casegroupresult.CaseResultsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(caseresult.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedCaseResultsIDs(); len(nodes) > 0 && !_u.mutation.CaseResultsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   casegroupresult.CaseResultsTable,
			Columns: []string{casegroupresult.CaseResultsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(caseresult.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.CaseResultsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   casegroupresult.CaseResultsTable,
			Columns: []string{casegroupresult.CaseResultsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(caseresult.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.SubmissionRecordCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   casegroupresult.SubmissionRecordTable,
			Columns: []string{casegroupresult.SubmissionRecordColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(submissionrecord.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.SubmissionRecordIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   casegroupresult.SubmissionRecordTable,
			Columns: []string{casegroupresult.SubmissionRecordColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(submissionrecord.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{casegroupresult.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// CaseGroupResultUpdateOne is the builder for updating a single CaseGroupResult entity.
type CaseGroupResultUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *CaseGroupResultMutation
}

// SetSubmissionID sets the "submission_id" field.
func (_u *CaseGroupResultUpdateOne) SetSubmissionID(v int64) *CaseGroupResultUpdateOne {
	_u.mutation.SetSubmissionID(v)
	return _u
}

// SetNillableSubmissionID sets the "submission_id" field if the given value is not nil.
func (_u *CaseGroupResultUpdateOne) SetNillableSubmissionID(v *int64) *CaseGroupResultUpdateOne {
	if v != nil {
		_u.SetSubmissionID(*v)
	}
	return _u
}

// SetStatus sets the "status" field.
func (_u *CaseGroupResultUpdateOne) SetStatus(v int16) *CaseGroupResultUpdateOne {
	_u.mutation.ResetStatus()
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *CaseGroupResultUpdateOne) SetNillableStatus(v *int16) *CaseGroupResultUpdateOne {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// AddStatus adds value to the "status" field.
func (_u *CaseGroupResultUpdateOne) AddStatus(v int16) *CaseGroupResultUpdateOne {
	_u.mutation.AddStatus(v)
	return _u
}

// SetTotalTimeCostMs sets the "total_time_cost_ms" field.
func (_u *CaseGroupResultUpdateOne) SetTotalTimeCostMs(v uint64) *CaseGroupResultUpdateOne {
	_u.mutation.ResetTotalTimeCostMs()
	_u.mutation.SetTotalTimeCostMs(v)
	return _u
}

// SetNillableTotalTimeCostMs sets the "total_time_cost_ms" field if the given value is not nil.
func (_u *CaseGroupResultUpdateOne) SetNillableTotalTimeCostMs(v *uint64) *CaseGroupResultUpdateOne {
	if v != nil {
		_u.SetTotalTimeCostMs(*v)
	}
	return _u
}

// AddTotalTimeCostMs adds value to the "total_time_cost_ms" field.
func (_u *CaseGroupResultUpdateOne) AddTotalTimeCostMs(v int64) *CaseGroupResultUpdateOne {
	_u.mutation.AddTotalTimeCostMs(v)
	return _u
}

// SetMaxMemoryCostKB sets the "max_memory_cost_kb" field.
func (_u *CaseGroupResultUpdateOne) SetMaxMemoryCostKB(v uint64) *CaseGroupResultUpdateOne {
	_u.mutation.ResetMaxMemoryCostKB()
	_u.mutation.SetMaxMemoryCostKB(v)
	return _u
}

// SetNillableMaxMemoryCostKB sets the "max_memory_cost_kb" field if the given value is not nil.
func (_u *CaseGroupResultUpdateOne) SetNillableMaxMemoryCostKB(v *uint64) *CaseGroupResultUpdateOne {
	if v != nil {
		_u.SetMaxMemoryCostKB(*v)
	}
	return _u
}

// AddMaxMemoryCostKB adds value to the "max_memory_cost_kb" field.
func (_u *CaseGroupResultUpdateOne) AddMaxMemoryCostKB(v int64) *CaseGroupResultUpdateOne {
	_u.mutation.AddMaxMemoryCostKB(v)
	return _u
}

// SetScore sets the "score" field.
func (_u *CaseGroupResultUpdateOne) SetScore(v int) *CaseGroupResultUpdateOne {
	_u.mutation.ResetScore()
	_u.mutation.SetScore(v)
	return _u
}

// SetNillableScore sets the "score" field if the given value is not nil.
func (_u *CaseGroupResultUpdateOne) SetNillableScore(v *int) *CaseGroupResultUpdateOne {
	if v != nil {
		_u.SetScore(*v)
	}
	return _u
}

// AddScore adds value to the "score" field.
func (_u *CaseGroupResultUpdateOne) AddScore(v int) *CaseGroupResultUpdateOne {
	_u.mutation.AddScore(v)
	return _u
}

// AddProblemIDs adds the "problem" edge to the Problem entity by IDs.
func (_u *CaseGroupResultUpdateOne) AddProblemIDs(ids ...int64) *CaseGroupResultUpdateOne {
	_u.mutation.AddProblemIDs(ids...)
	return _u
}

// AddProblem adds the "problem" edges to the Problem entity.
func (_u *CaseGroupResultUpdateOne) AddProblem(v ...*Problem) *CaseGroupResultUpdateOne {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddProblemIDs(ids...)
}

// AddCaseResultIDs adds the "case_results" edge to the CaseResult entity by IDs.
func (_u *CaseGroupResultUpdateOne) AddCaseResultIDs(ids ...int64) *CaseGroupResultUpdateOne {
	_u.mutation.AddCaseResultIDs(ids...)
	return _u
}

// AddCaseResults adds the "case_results" edges to the CaseResult entity.
func (_u *CaseGroupResultUpdateOne) AddCaseResults(v ...*CaseResult) *CaseGroupResultUpdateOne {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddCaseResultIDs(ids...)
}

// SetSubmissionRecordID sets the "submission_record" edge to the SubmissionRecord entity by ID.
func (_u *CaseGroupResultUpdateOne) SetSubmissionRecordID(id int64) *CaseGroupResultUpdateOne {
	_u.mutation.SetSubmissionRecordID(id)
	return _u
}

// SetSubmissionRecord sets the "submission_record" edge to the SubmissionRecord entity.
func (_u *CaseGroupResultUpdateOne) SetSubmissionRecord(v *SubmissionRecord) *CaseGroupResultUpdateOne {
	return _u.SetSubmissionRecordID(v.ID)
}

// Mutation returns the CaseGroupResultMutation object of the builder.
func (_u *CaseGroupResultUpdateOne) Mutation() *CaseGroupResultMutation {
	return _u.mutation
}

// ClearProblem clears all "problem" edges to the Problem entity.
func (_u *CaseGroupResultUpdateOne) ClearProblem() *CaseGroupResultUpdateOne {
	_u.mutation.ClearProblem()
	return _u
}

// RemoveProblemIDs removes the "problem" edge to Problem entities by IDs.
func (_u *CaseGroupResultUpdateOne) RemoveProblemIDs(ids ...int64) *CaseGroupResultUpdateOne {
	_u.mutation.RemoveProblemIDs(ids...)
	return _u
}

// RemoveProblem removes "problem" edges to Problem entities.
func (_u *CaseGroupResultUpdateOne) RemoveProblem(v ...*Problem) *CaseGroupResultUpdateOne {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveProblemIDs(ids...)
}

// ClearCaseResults clears all "case_results" edges to the CaseResult entity.
func (_u *CaseGroupResultUpdateOne) ClearCaseResults() *CaseGroupResultUpdateOne {
	_u.mutation.ClearCaseResults()
	return _u
}

// RemoveCaseResultIDs removes the "case_results" edge to CaseResult entities by IDs.
func (_u *CaseGroupResultUpdateOne) RemoveCaseResultIDs(ids ...int64) *CaseGroupResultUpdateOne {
	_u.mutation.RemoveCaseResultIDs(ids...)
	return _u
}

// RemoveCaseResults removes "case_results" edges to CaseResult entities.
func (_u *CaseGroupResultUpdateOne) RemoveCaseResults(v ...*CaseResult) *CaseGroupResultUpdateOne {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveCaseResultIDs(ids...)
}

// ClearSubmissionRecord clears the "submission_record" edge to the SubmissionRecord entity.
func (_u *CaseGroupResultUpdateOne) ClearSubmissionRecord() *CaseGroupResultUpdateOne {
	_u.mutation.ClearSubmissionRecord()
	return _u
}

// Where appends a list predicates to the CaseGroupResultUpdate builder.
func (_u *CaseGroupResultUpdateOne) Where(ps ...predicate.CaseGroupResult) *CaseGroupResultUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *CaseGroupResultUpdateOne) Select(field string, fields ...string) *CaseGroupResultUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated CaseGroupResult entity.
func (_u *CaseGroupResultUpdateOne) Save(ctx context.Context) (*CaseGroupResult, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *CaseGroupResultUpdateOne) SaveX(ctx context.Context) *CaseGroupResult {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *CaseGroupResultUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *CaseGroupResultUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *CaseGroupResultUpdateOne) check() error {
	if _u.mutation.SubmissionRecordCleared() && len(_u.mutation.SubmissionRecordIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "CaseGroupResult.submission_record"`)
	}
	return nil
}

func (_u *CaseGroupResultUpdateOne) sqlSave(ctx context.Context) (_node *CaseGroupResult, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(casegroupresult.Table, casegroupresult.Columns, sqlgraph.NewFieldSpec(casegroupresult.FieldID, field.TypeInt64))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "CaseGroupResult.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, casegroupresult.FieldID)
		for _, f := range fields {
			if !casegroupresult.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != casegroupresult.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(casegroupresult.FieldStatus, field.TypeInt16, value)
	}
	if value, ok := _u.mutation.AddedStatus(); ok {
		_spec.AddField(casegroupresult.FieldStatus, field.TypeInt16, value)
	}
	if value, ok := _u.mutation.TotalTimeCostMs(); ok {
		_spec.SetField(casegroupresult.FieldTotalTimeCostMs, field.TypeUint64, value)
	}
	if value, ok := _u.mutation.AddedTotalTimeCostMs(); ok {
		_spec.AddField(casegroupresult.FieldTotalTimeCostMs, field.TypeUint64, value)
	}
	if value, ok := _u.mutation.MaxMemoryCostKB(); ok {
		_spec.SetField(casegroupresult.FieldMaxMemoryCostKB, field.TypeUint64, value)
	}
	if value, ok := _u.mutation.AddedMaxMemoryCostKB(); ok {
		_spec.AddField(casegroupresult.FieldMaxMemoryCostKB, field.TypeUint64, value)
	}
	if value, ok := _u.mutation.Score(); ok {
		_spec.SetField(casegroupresult.FieldScore, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedScore(); ok {
		_spec.AddField(casegroupresult.FieldScore, field.TypeInt, value)
	}
	if _u.mutation.ProblemCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   casegroupresult.ProblemTable,
			Columns: []string{casegroupresult.ProblemColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(problem.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedProblemIDs(); len(nodes) > 0 && !_u.mutation.ProblemCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   casegroupresult.ProblemTable,
			Columns: []string{casegroupresult.ProblemColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(problem.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ProblemIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   casegroupresult.ProblemTable,
			Columns: []string{casegroupresult.ProblemColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(problem.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.CaseResultsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   casegroupresult.CaseResultsTable,
			Columns: []string{casegroupresult.CaseResultsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(caseresult.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedCaseResultsIDs(); len(nodes) > 0 && !_u.mutation.CaseResultsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   casegroupresult.CaseResultsTable,
			Columns: []string{casegroupresult.CaseResultsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(caseresult.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.CaseResultsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   casegroupresult.CaseResultsTable,
			Columns: []string{casegroupresult.CaseResultsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(caseresult.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.SubmissionRecordCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   casegroupresult.SubmissionRecordTable,
			Columns: []string{casegroupresult.SubmissionRecordColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(submissionrecord.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.SubmissionRecordIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   casegroupresult.SubmissionRecordTable,
			Columns: []string{casegroupresult.SubmissionRecordColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(submissionrecord.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &CaseGroupResult{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{casegroupresult.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
