// Code generated by ent, DO NOT EDIT.

package ent

import (
	"cascade-oj/ent/competitor_list"
	"cascade-oj/ent/problemset"
	"cascade-oj/ent/user"
	"fmt"
	"strings"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
)

// Competitor_List is the model entity for the Competitor_List schema.
type Competitor_List struct {
	config `json:"-"`
	// ID of the ent.
	ID int64 `json:"id,omitempty"`
	// UserID holds the value of the "user_id" field.
	UserID int64 `json:"user_id,omitempty"`
	// ProblemSetID holds the value of the "problem_set_id" field.
	ProblemSetID int64 `json:"problem_set_id,omitempty"`
	// TotalScore holds the value of the "total_score" field.
	TotalScore int `json:"total_score,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the Competitor_ListQuery when eager-loading is set.
	Edges        Competitor_ListEdges `json:"edges"`
	selectValues sql.SelectValues
}

// Competitor_ListEdges holds the relations/edges for other nodes in the graph.
type Competitor_ListEdges struct {
	// User holds the value of the user edge.
	User *User `json:"user,omitempty"`
	// ProblemSet holds the value of the problem_set edge.
	ProblemSet *ProblemSet `json:"problem_set,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [2]bool
}

// UserOrErr returns the User value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e Competitor_ListEdges) UserOrErr() (*User, error) {
	if e.User != nil {
		return e.User, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: user.Label}
	}
	return nil, &NotLoadedError{edge: "user"}
}

// ProblemSetOrErr returns the ProblemSet value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e Competitor_ListEdges) ProblemSetOrErr() (*ProblemSet, error) {
	if e.ProblemSet != nil {
		return e.ProblemSet, nil
	} else if e.loadedTypes[1] {
		return nil, &NotFoundError{label: problemset.Label}
	}
	return nil, &NotLoadedError{edge: "problem_set"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*Competitor_List) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case competitor_list.FieldID, competitor_list.FieldUserID, competitor_list.FieldProblemSetID, competitor_list.FieldTotalScore:
			values[i] = new(sql.NullInt64)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the Competitor_List fields.
func (_m *Competitor_List) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case competitor_list.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int64(value.Int64)
		case competitor_list.FieldUserID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field user_id", values[i])
			} else if value.Valid {
				_m.UserID = value.Int64
			}
		case competitor_list.FieldProblemSetID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field problem_set_id", values[i])
			} else if value.Valid {
				_m.ProblemSetID = value.Int64
			}
		case competitor_list.FieldTotalScore:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field total_score", values[i])
			} else if value.Valid {
				_m.TotalScore = int(value.Int64)
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the Competitor_List.
// This includes values selected through modifiers, order, etc.
func (_m *Competitor_List) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryUser queries the "user" edge of the Competitor_List entity.
func (_m *Competitor_List) QueryUser() *UserQuery {
	return NewCompetitorListClient(_m.config).QueryUser(_m)
}

// QueryProblemSet queries the "problem_set" edge of the Competitor_List entity.
func (_m *Competitor_List) QueryProblemSet() *ProblemSetQuery {
	return NewCompetitorListClient(_m.config).QueryProblemSet(_m)
}

// Update returns a builder for updating this Competitor_List.
// Note that you need to call Competitor_List.Unwrap() before calling this method if this Competitor_List
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *Competitor_List) Update() *CompetitorListUpdateOne {
	return NewCompetitorListClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the Competitor_List entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *Competitor_List) Unwrap() *Competitor_List {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: Competitor_List is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *Competitor_List) String() string {
	var builder strings.Builder
	builder.WriteString("Competitor_List(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("user_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.UserID))
	builder.WriteString(", ")
	builder.WriteString("problem_set_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.ProblemSetID))
	builder.WriteString(", ")
	builder.WriteString("total_score=")
	builder.WriteString(fmt.Sprintf("%v", _m.TotalScore))
	builder.WriteByte(')')
	return builder.String()
}

// Competitor_Lists is a parsable slice of Competitor_List.
type Competitor_Lists []*Competitor_List
