// Code generated by ent, DO NOT EDIT.

package ent

import (
	"cascade-oj/ent/judgerecord"
	"cascade-oj/ent/problem"
	"cascade-oj/ent/submissionrecord"
	"cascade-oj/ent/user"
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// JudgeRecordCreate is the builder for creating a JudgeRecord entity.
type JudgeRecordCreate struct {
	config
	mutation *JudgeRecordMutation
	hooks    []Hook
}

// SetProblemID sets the "problem_id" field.
func (_c *JudgeRecordCreate) SetProblemID(v int) *JudgeRecordCreate {
	_c.mutation.SetProblemID(v)
	return _c
}

// SetUserID sets the "user_id" field.
func (_c *JudgeRecordCreate) SetUserID(v int) *JudgeRecordCreate {
	_c.mutation.SetUserID(v)
	return _c
}

// SetStatus sets the "status" field.
func (_c *JudgeRecordCreate) SetStatus(v judgerecord.Status) *JudgeRecordCreate {
	_c.mutation.SetStatus(v)
	return _c
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_c *JudgeRecordCreate) SetNillableStatus(v *judgerecord.Status) *JudgeRecordCreate {
	if v != nil {
		_c.SetStatus(*v)
	}
	return _c
}

// SetJudgeStartTime sets the "judge_start_time" field.
func (_c *JudgeRecordCreate) SetJudgeStartTime(v time.Time) *JudgeRecordCreate {
	_c.mutation.SetJudgeStartTime(v)
	return _c
}

// SetNillableJudgeStartTime sets the "judge_start_time" field if the given value is not nil.
func (_c *JudgeRecordCreate) SetNillableJudgeStartTime(v *time.Time) *JudgeRecordCreate {
	if v != nil {
		_c.SetJudgeStartTime(*v)
	}
	return _c
}

// SetResult sets the "result" field.
func (_c *JudgeRecordCreate) SetResult(v string) *JudgeRecordCreate {
	_c.mutation.SetResult(v)
	return _c
}

// SetNillableResult sets the "result" field if the given value is not nil.
func (_c *JudgeRecordCreate) SetNillableResult(v *string) *JudgeRecordCreate {
	if v != nil {
		_c.SetResult(*v)
	}
	return _c
}

// SetCode sets the "code" field.
func (_c *JudgeRecordCreate) SetCode(v string) *JudgeRecordCreate {
	_c.mutation.SetCode(v)
	return _c
}

// SetLanguage sets the "language" field.
func (_c *JudgeRecordCreate) SetLanguage(v judgerecord.Language) *JudgeRecordCreate {
	_c.mutation.SetLanguage(v)
	return _c
}

// SetNillableLanguage sets the "language" field if the given value is not nil.
func (_c *JudgeRecordCreate) SetNillableLanguage(v *judgerecord.Language) *JudgeRecordCreate {
	if v != nil {
		_c.SetLanguage(*v)
	}
	return _c
}

// SetJudgeType sets the "judge_type" field.
func (_c *JudgeRecordCreate) SetJudgeType(v judgerecord.JudgeType) *JudgeRecordCreate {
	_c.mutation.SetJudgeType(v)
	return _c
}

// SetNillableJudgeType sets the "judge_type" field if the given value is not nil.
func (_c *JudgeRecordCreate) SetNillableJudgeType(v *judgerecord.JudgeType) *JudgeRecordCreate {
	if v != nil {
		_c.SetJudgeType(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *JudgeRecordCreate) SetID(v int) *JudgeRecordCreate {
	_c.mutation.SetID(v)
	return _c
}

// SetProblem sets the "problem" edge to the Problem entity.
func (_c *JudgeRecordCreate) SetProblem(v *Problem) *JudgeRecordCreate {
	return _c.SetProblemID(v.ID)
}

// SetUser sets the "user" edge to the User entity.
func (_c *JudgeRecordCreate) SetUser(v *User) *JudgeRecordCreate {
	return _c.SetUserID(v.ID)
}

// AddSubmissionIDs adds the "submissions" edge to the SubmissionRecord entity by IDs.
func (_c *JudgeRecordCreate) AddSubmissionIDs(ids ...int) *JudgeRecordCreate {
	_c.mutation.AddSubmissionIDs(ids...)
	return _c
}

// AddSubmissions adds the "submissions" edges to the SubmissionRecord entity.
func (_c *JudgeRecordCreate) AddSubmissions(v ...*SubmissionRecord) *JudgeRecordCreate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddSubmissionIDs(ids...)
}

// Mutation returns the JudgeRecordMutation object of the builder.
func (_c *JudgeRecordCreate) Mutation() *JudgeRecordMutation {
	return _c.mutation
}

// Save creates the JudgeRecord in the database.
func (_c *JudgeRecordCreate) Save(ctx context.Context) (*JudgeRecord, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *JudgeRecordCreate) SaveX(ctx context.Context) *JudgeRecord {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *JudgeRecordCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *JudgeRecordCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *JudgeRecordCreate) defaults() {
	if _, ok := _c.mutation.Status(); !ok {
		v := judgerecord.DefaultStatus
		_c.mutation.SetStatus(v)
	}
	if _, ok := _c.mutation.JudgeStartTime(); !ok {
		v := judgerecord.DefaultJudgeStartTime
		_c.mutation.SetJudgeStartTime(v)
	}
	if _, ok := _c.mutation.Language(); !ok {
		v := judgerecord.DefaultLanguage
		_c.mutation.SetLanguage(v)
	}
	if _, ok := _c.mutation.JudgeType(); !ok {
		v := judgerecord.DefaultJudgeType
		_c.mutation.SetJudgeType(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *JudgeRecordCreate) check() error {
	if _, ok := _c.mutation.ProblemID(); !ok {
		return &ValidationError{Name: "problem_id", err: errors.New(`ent: missing required field "JudgeRecord.problem_id"`)}
	}
	if v, ok := _c.mutation.ProblemID(); ok {
		if err := judgerecord.ProblemIDValidator(v); err != nil {
			return &ValidationError{Name: "problem_id", err: fmt.Errorf(`ent: validator failed for field "JudgeRecord.problem_id": %w`, err)}
		}
	}
	if _, ok := _c.mutation.UserID(); !ok {
		return &ValidationError{Name: "user_id", err: errors.New(`ent: missing required field "JudgeRecord.user_id"`)}
	}
	if v, ok := _c.mutation.UserID(); ok {
		if err := judgerecord.UserIDValidator(v); err != nil {
			return &ValidationError{Name: "user_id", err: fmt.Errorf(`ent: validator failed for field "JudgeRecord.user_id": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Status(); !ok {
		return &ValidationError{Name: "status", err: errors.New(`ent: missing required field "JudgeRecord.status"`)}
	}
	if v, ok := _c.mutation.Status(); ok {
		if err := judgerecord.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "JudgeRecord.status": %w`, err)}
		}
	}
	if _, ok := _c.mutation.JudgeStartTime(); !ok {
		return &ValidationError{Name: "judge_start_time", err: errors.New(`ent: missing required field "JudgeRecord.judge_start_time"`)}
	}
	if _, ok := _c.mutation.Code(); !ok {
		return &ValidationError{Name: "code", err: errors.New(`ent: missing required field "JudgeRecord.code"`)}
	}
	if v, ok := _c.mutation.Code(); ok {
		if err := judgerecord.CodeValidator(v); err != nil {
			return &ValidationError{Name: "code", err: fmt.Errorf(`ent: validator failed for field "JudgeRecord.code": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Language(); !ok {
		return &ValidationError{Name: "language", err: errors.New(`ent: missing required field "JudgeRecord.language"`)}
	}
	if v, ok := _c.mutation.Language(); ok {
		if err := judgerecord.LanguageValidator(v); err != nil {
			return &ValidationError{Name: "language", err: fmt.Errorf(`ent: validator failed for field "JudgeRecord.language": %w`, err)}
		}
	}
	if _, ok := _c.mutation.JudgeType(); !ok {
		return &ValidationError{Name: "judge_type", err: errors.New(`ent: missing required field "JudgeRecord.judge_type"`)}
	}
	if v, ok := _c.mutation.JudgeType(); ok {
		if err := judgerecord.JudgeTypeValidator(v); err != nil {
			return &ValidationError{Name: "judge_type", err: fmt.Errorf(`ent: validator failed for field "JudgeRecord.judge_type": %w`, err)}
		}
	}
	if v, ok := _c.mutation.ID(); ok {
		if err := judgerecord.IDValidator(v); err != nil {
			return &ValidationError{Name: "id", err: fmt.Errorf(`ent: validator failed for field "JudgeRecord.id": %w`, err)}
		}
	}
	if len(_c.mutation.ProblemIDs()) == 0 {
		return &ValidationError{Name: "problem", err: errors.New(`ent: missing required edge "JudgeRecord.problem"`)}
	}
	if len(_c.mutation.UserIDs()) == 0 {
		return &ValidationError{Name: "user", err: errors.New(`ent: missing required edge "JudgeRecord.user"`)}
	}
	return nil
}

func (_c *JudgeRecordCreate) sqlSave(ctx context.Context) (*JudgeRecord, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != _node.ID {
		id := _spec.ID.Value.(int64)
		_node.ID = int(id)
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *JudgeRecordCreate) createSpec() (*JudgeRecord, *sqlgraph.CreateSpec) {
	var (
		_node = &JudgeRecord{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(judgerecord.Table, sqlgraph.NewFieldSpec(judgerecord.FieldID, field.TypeInt))
	)
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = id
	}
	if value, ok := _c.mutation.Status(); ok {
		_spec.SetField(judgerecord.FieldStatus, field.TypeEnum, value)
		_node.Status = value
	}
	if value, ok := _c.mutation.JudgeStartTime(); ok {
		_spec.SetField(judgerecord.FieldJudgeStartTime, field.TypeTime, value)
		_node.JudgeStartTime = value
	}
	if value, ok := _c.mutation.Result(); ok {
		_spec.SetField(judgerecord.FieldResult, field.TypeString, value)
		_node.Result = value
	}
	if value, ok := _c.mutation.Code(); ok {
		_spec.SetField(judgerecord.FieldCode, field.TypeString, value)
		_node.Code = value
	}
	if value, ok := _c.mutation.Language(); ok {
		_spec.SetField(judgerecord.FieldLanguage, field.TypeEnum, value)
		_node.Language = value
	}
	if value, ok := _c.mutation.JudgeType(); ok {
		_spec.SetField(judgerecord.FieldJudgeType, field.TypeEnum, value)
		_node.JudgeType = value
	}
	if nodes := _c.mutation.ProblemIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   judgerecord.ProblemTable,
			Columns: []string{judgerecord.ProblemColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(problem.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.ProblemID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   judgerecord.UserTable,
			Columns: []string{judgerecord.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.UserID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.SubmissionsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   judgerecord.SubmissionsTable,
			Columns: []string{judgerecord.SubmissionsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(submissionrecord.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// JudgeRecordCreateBulk is the builder for creating many JudgeRecord entities in bulk.
type JudgeRecordCreateBulk struct {
	config
	err      error
	builders []*JudgeRecordCreate
}

// Save creates the JudgeRecord entities in the database.
func (_c *JudgeRecordCreateBulk) Save(ctx context.Context) ([]*JudgeRecord, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*JudgeRecord, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*JudgeRecordMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil && nodes[i].ID == 0 {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *JudgeRecordCreateBulk) SaveX(ctx context.Context) []*JudgeRecord {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *JudgeRecordCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *JudgeRecordCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
