// Code generated by ent, DO NOT EDIT.

package ent

import (
	"cascade-oj/ent/predicate"
	"cascade-oj/ent/problemset"
	"cascade-oj/ent/problemsetmanager"
	"cascade-oj/ent/user"
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// ProblemSetManagerUpdate is the builder for updating ProblemSetManager entities.
type ProblemSetManagerUpdate struct {
	config
	hooks    []Hook
	mutation *ProblemSetManagerMutation
}

// Where appends a list predicates to the ProblemSetManagerUpdate builder.
func (_u *ProblemSetManagerUpdate) Where(ps ...predicate.ProblemSetManager) *ProblemSetManagerUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetAdminID sets the "admin_id" field.
func (_u *ProblemSetManagerUpdate) SetAdminID(v int64) *ProblemSetManagerUpdate {
	_u.mutation.SetAdminID(v)
	return _u
}

// SetNillableAdminID sets the "admin_id" field if the given value is not nil.
func (_u *ProblemSetManagerUpdate) SetNillableAdminID(v *int64) *ProblemSetManagerUpdate {
	if v != nil {
		_u.SetAdminID(*v)
	}
	return _u
}

// SetProblemSetID sets the "problem_set_id" field.
func (_u *ProblemSetManagerUpdate) SetProblemSetID(v int64) *ProblemSetManagerUpdate {
	_u.mutation.SetProblemSetID(v)
	return _u
}

// SetNillableProblemSetID sets the "problem_set_id" field if the given value is not nil.
func (_u *ProblemSetManagerUpdate) SetNillableProblemSetID(v *int64) *ProblemSetManagerUpdate {
	if v != nil {
		_u.SetProblemSetID(*v)
	}
	return _u
}

// SetAdmin sets the "admin" edge to the User entity.
func (_u *ProblemSetManagerUpdate) SetAdmin(v *User) *ProblemSetManagerUpdate {
	return _u.SetAdminID(v.ID)
}

// SetProblemSet sets the "problem_set" edge to the ProblemSet entity.
func (_u *ProblemSetManagerUpdate) SetProblemSet(v *ProblemSet) *ProblemSetManagerUpdate {
	return _u.SetProblemSetID(v.ID)
}

// Mutation returns the ProblemSetManagerMutation object of the builder.
func (_u *ProblemSetManagerUpdate) Mutation() *ProblemSetManagerMutation {
	return _u.mutation
}

// ClearAdmin clears the "admin" edge to the User entity.
func (_u *ProblemSetManagerUpdate) ClearAdmin() *ProblemSetManagerUpdate {
	_u.mutation.ClearAdmin()
	return _u
}

// ClearProblemSet clears the "problem_set" edge to the ProblemSet entity.
func (_u *ProblemSetManagerUpdate) ClearProblemSet() *ProblemSetManagerUpdate {
	_u.mutation.ClearProblemSet()
	return _u
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *ProblemSetManagerUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *ProblemSetManagerUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *ProblemSetManagerUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *ProblemSetManagerUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *ProblemSetManagerUpdate) check() error {
	if v, ok := _u.mutation.AdminID(); ok {
		if err := problemsetmanager.AdminIDValidator(v); err != nil {
			return &ValidationError{Name: "admin_id", err: fmt.Errorf(`ent: validator failed for field "ProblemSetManager.admin_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.ProblemSetID(); ok {
		if err := problemsetmanager.ProblemSetIDValidator(v); err != nil {
			return &ValidationError{Name: "problem_set_id", err: fmt.Errorf(`ent: validator failed for field "ProblemSetManager.problem_set_id": %w`, err)}
		}
	}
	if _u.mutation.AdminCleared() && len(_u.mutation.AdminIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "ProblemSetManager.admin"`)
	}
	if _u.mutation.ProblemSetCleared() && len(_u.mutation.ProblemSetIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "ProblemSetManager.problem_set"`)
	}
	return nil
}

func (_u *ProblemSetManagerUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(problemsetmanager.Table, problemsetmanager.Columns, sqlgraph.NewFieldSpec(problemsetmanager.FieldID, field.TypeInt64))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if _u.mutation.AdminCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   problemsetmanager.AdminTable,
			Columns: []string{problemsetmanager.AdminColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.AdminIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   problemsetmanager.AdminTable,
			Columns: []string{problemsetmanager.AdminColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.ProblemSetCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   problemsetmanager.ProblemSetTable,
			Columns: []string{problemsetmanager.ProblemSetColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(problemset.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ProblemSetIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   problemsetmanager.ProblemSetTable,
			Columns: []string{problemsetmanager.ProblemSetColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(problemset.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{problemsetmanager.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// ProblemSetManagerUpdateOne is the builder for updating a single ProblemSetManager entity.
type ProblemSetManagerUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *ProblemSetManagerMutation
}

// SetAdminID sets the "admin_id" field.
func (_u *ProblemSetManagerUpdateOne) SetAdminID(v int64) *ProblemSetManagerUpdateOne {
	_u.mutation.SetAdminID(v)
	return _u
}

// SetNillableAdminID sets the "admin_id" field if the given value is not nil.
func (_u *ProblemSetManagerUpdateOne) SetNillableAdminID(v *int64) *ProblemSetManagerUpdateOne {
	if v != nil {
		_u.SetAdminID(*v)
	}
	return _u
}

// SetProblemSetID sets the "problem_set_id" field.
func (_u *ProblemSetManagerUpdateOne) SetProblemSetID(v int64) *ProblemSetManagerUpdateOne {
	_u.mutation.SetProblemSetID(v)
	return _u
}

// SetNillableProblemSetID sets the "problem_set_id" field if the given value is not nil.
func (_u *ProblemSetManagerUpdateOne) SetNillableProblemSetID(v *int64) *ProblemSetManagerUpdateOne {
	if v != nil {
		_u.SetProblemSetID(*v)
	}
	return _u
}

// SetAdmin sets the "admin" edge to the User entity.
func (_u *ProblemSetManagerUpdateOne) SetAdmin(v *User) *ProblemSetManagerUpdateOne {
	return _u.SetAdminID(v.ID)
}

// SetProblemSet sets the "problem_set" edge to the ProblemSet entity.
func (_u *ProblemSetManagerUpdateOne) SetProblemSet(v *ProblemSet) *ProblemSetManagerUpdateOne {
	return _u.SetProblemSetID(v.ID)
}

// Mutation returns the ProblemSetManagerMutation object of the builder.
func (_u *ProblemSetManagerUpdateOne) Mutation() *ProblemSetManagerMutation {
	return _u.mutation
}

// ClearAdmin clears the "admin" edge to the User entity.
func (_u *ProblemSetManagerUpdateOne) ClearAdmin() *ProblemSetManagerUpdateOne {
	_u.mutation.ClearAdmin()
	return _u
}

// ClearProblemSet clears the "problem_set" edge to the ProblemSet entity.
func (_u *ProblemSetManagerUpdateOne) ClearProblemSet() *ProblemSetManagerUpdateOne {
	_u.mutation.ClearProblemSet()
	return _u
}

// Where appends a list predicates to the ProblemSetManagerUpdate builder.
func (_u *ProblemSetManagerUpdateOne) Where(ps ...predicate.ProblemSetManager) *ProblemSetManagerUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *ProblemSetManagerUpdateOne) Select(field string, fields ...string) *ProblemSetManagerUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated ProblemSetManager entity.
func (_u *ProblemSetManagerUpdateOne) Save(ctx context.Context) (*ProblemSetManager, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *ProblemSetManagerUpdateOne) SaveX(ctx context.Context) *ProblemSetManager {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *ProblemSetManagerUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *ProblemSetManagerUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *ProblemSetManagerUpdateOne) check() error {
	if v, ok := _u.mutation.AdminID(); ok {
		if err := problemsetmanager.AdminIDValidator(v); err != nil {
			return &ValidationError{Name: "admin_id", err: fmt.Errorf(`ent: validator failed for field "ProblemSetManager.admin_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.ProblemSetID(); ok {
		if err := problemsetmanager.ProblemSetIDValidator(v); err != nil {
			return &ValidationError{Name: "problem_set_id", err: fmt.Errorf(`ent: validator failed for field "ProblemSetManager.problem_set_id": %w`, err)}
		}
	}
	if _u.mutation.AdminCleared() && len(_u.mutation.AdminIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "ProblemSetManager.admin"`)
	}
	if _u.mutation.ProblemSetCleared() && len(_u.mutation.ProblemSetIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "ProblemSetManager.problem_set"`)
	}
	return nil
}

func (_u *ProblemSetManagerUpdateOne) sqlSave(ctx context.Context) (_node *ProblemSetManager, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(problemsetmanager.Table, problemsetmanager.Columns, sqlgraph.NewFieldSpec(problemsetmanager.FieldID, field.TypeInt64))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "ProblemSetManager.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, problemsetmanager.FieldID)
		for _, f := range fields {
			if !problemsetmanager.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != problemsetmanager.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if _u.mutation.AdminCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   problemsetmanager.AdminTable,
			Columns: []string{problemsetmanager.AdminColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.AdminIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   problemsetmanager.AdminTable,
			Columns: []string{problemsetmanager.AdminColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.ProblemSetCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   problemsetmanager.ProblemSetTable,
			Columns: []string{problemsetmanager.ProblemSetColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(problemset.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ProblemSetIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   problemsetmanager.ProblemSetTable,
			Columns: []string{problemsetmanager.ProblemSetColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(problemset.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &ProblemSetManager{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{problemsetmanager.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
