// Code generated by ent, DO NOT EDIT.

package ent

import (
	"cascade-oj/ent/adminproblemset"
	"cascade-oj/ent/problemset"
	"cascade-oj/ent/problemset_problem"
	"cascade-oj/ent/problemset_user"
	"cascade-oj/ent/submissionrecord"
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// ProblemSetCreate is the builder for creating a ProblemSet entity.
type ProblemSetCreate struct {
	config
	mutation *ProblemSetMutation
	hooks    []Hook
}

// SetName sets the "name" field.
func (_c *ProblemSetCreate) SetName(v string) *ProblemSetCreate {
	_c.mutation.SetName(v)
	return _c
}

// SetDescription sets the "description" field.
func (_c *ProblemSetCreate) SetDescription(v string) *ProblemSetCreate {
	_c.mutation.SetDescription(v)
	return _c
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (_c *ProblemSetCreate) SetNillableDescription(v *string) *ProblemSetCreate {
	if v != nil {
		_c.SetDescription(*v)
	}
	return _c
}

// SetStartTime sets the "start_time" field.
func (_c *ProblemSetCreate) SetStartTime(v time.Time) *ProblemSetCreate {
	_c.mutation.SetStartTime(v)
	return _c
}

// SetEndTime sets the "end_time" field.
func (_c *ProblemSetCreate) SetEndTime(v time.Time) *ProblemSetCreate {
	_c.mutation.SetEndTime(v)
	return _c
}

// SetStatus sets the "status" field.
func (_c *ProblemSetCreate) SetStatus(v problemset.Status) *ProblemSetCreate {
	_c.mutation.SetStatus(v)
	return _c
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_c *ProblemSetCreate) SetNillableStatus(v *problemset.Status) *ProblemSetCreate {
	if v != nil {
		_c.SetStatus(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *ProblemSetCreate) SetID(v int64) *ProblemSetCreate {
	_c.mutation.SetID(v)
	return _c
}

// AddSubmissionIDs adds the "submissions" edge to the SubmissionRecord entity by IDs.
func (_c *ProblemSetCreate) AddSubmissionIDs(ids ...int64) *ProblemSetCreate {
	_c.mutation.AddSubmissionIDs(ids...)
	return _c
}

// AddSubmissions adds the "submissions" edges to the SubmissionRecord entity.
func (_c *ProblemSetCreate) AddSubmissions(v ...*SubmissionRecord) *ProblemSetCreate {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddSubmissionIDs(ids...)
}

// AddAdminProblemSetIDs adds the "admin_problem_sets" edge to the AdminProblemSet entity by IDs.
func (_c *ProblemSetCreate) AddAdminProblemSetIDs(ids ...int64) *ProblemSetCreate {
	_c.mutation.AddAdminProblemSetIDs(ids...)
	return _c
}

// AddAdminProblemSets adds the "admin_problem_sets" edges to the AdminProblemSet entity.
func (_c *ProblemSetCreate) AddAdminProblemSets(v ...*AdminProblemSet) *ProblemSetCreate {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddAdminProblemSetIDs(ids...)
}

// AddProblemSetProblemIDs adds the "problem_set_problems" edge to the ProblemSet_Problem entity by IDs.
func (_c *ProblemSetCreate) AddProblemSetProblemIDs(ids ...int64) *ProblemSetCreate {
	_c.mutation.AddProblemSetProblemIDs(ids...)
	return _c
}

// AddProblemSetProblems adds the "problem_set_problems" edges to the ProblemSet_Problem entity.
func (_c *ProblemSetCreate) AddProblemSetProblems(v ...*ProblemSet_Problem) *ProblemSetCreate {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddProblemSetProblemIDs(ids...)
}

// AddProblemSetUserIDs adds the "problem_set_users" edge to the ProblemSet_User entity by IDs.
func (_c *ProblemSetCreate) AddProblemSetUserIDs(ids ...int64) *ProblemSetCreate {
	_c.mutation.AddProblemSetUserIDs(ids...)
	return _c
}

// AddProblemSetUsers adds the "problem_set_users" edges to the ProblemSet_User entity.
func (_c *ProblemSetCreate) AddProblemSetUsers(v ...*ProblemSet_User) *ProblemSetCreate {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddProblemSetUserIDs(ids...)
}

// Mutation returns the ProblemSetMutation object of the builder.
func (_c *ProblemSetCreate) Mutation() *ProblemSetMutation {
	return _c.mutation
}

// Save creates the ProblemSet in the database.
func (_c *ProblemSetCreate) Save(ctx context.Context) (*ProblemSet, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *ProblemSetCreate) SaveX(ctx context.Context) *ProblemSet {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *ProblemSetCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *ProblemSetCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *ProblemSetCreate) defaults() {
	if _, ok := _c.mutation.Status(); !ok {
		v := problemset.DefaultStatus
		_c.mutation.SetStatus(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *ProblemSetCreate) check() error {
	if _, ok := _c.mutation.Name(); !ok {
		return &ValidationError{Name: "name", err: errors.New(`ent: missing required field "ProblemSet.name"`)}
	}
	if v, ok := _c.mutation.Name(); ok {
		if err := problemset.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "ProblemSet.name": %w`, err)}
		}
	}
	if _, ok := _c.mutation.StartTime(); !ok {
		return &ValidationError{Name: "start_time", err: errors.New(`ent: missing required field "ProblemSet.start_time"`)}
	}
	if _, ok := _c.mutation.EndTime(); !ok {
		return &ValidationError{Name: "end_time", err: errors.New(`ent: missing required field "ProblemSet.end_time"`)}
	}
	if _, ok := _c.mutation.Status(); !ok {
		return &ValidationError{Name: "status", err: errors.New(`ent: missing required field "ProblemSet.status"`)}
	}
	if v, ok := _c.mutation.Status(); ok {
		if err := problemset.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "ProblemSet.status": %w`, err)}
		}
	}
	if v, ok := _c.mutation.ID(); ok {
		if err := problemset.IDValidator(v); err != nil {
			return &ValidationError{Name: "id", err: fmt.Errorf(`ent: validator failed for field "ProblemSet.id": %w`, err)}
		}
	}
	return nil
}

func (_c *ProblemSetCreate) sqlSave(ctx context.Context) (*ProblemSet, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != _node.ID {
		id := _spec.ID.Value.(int64)
		_node.ID = int64(id)
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *ProblemSetCreate) createSpec() (*ProblemSet, *sqlgraph.CreateSpec) {
	var (
		_node = &ProblemSet{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(problemset.Table, sqlgraph.NewFieldSpec(problemset.FieldID, field.TypeInt64))
	)
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = id
	}
	if value, ok := _c.mutation.Name(); ok {
		_spec.SetField(problemset.FieldName, field.TypeString, value)
		_node.Name = value
	}
	if value, ok := _c.mutation.Description(); ok {
		_spec.SetField(problemset.FieldDescription, field.TypeString, value)
		_node.Description = value
	}
	if value, ok := _c.mutation.StartTime(); ok {
		_spec.SetField(problemset.FieldStartTime, field.TypeTime, value)
		_node.StartTime = value
	}
	if value, ok := _c.mutation.EndTime(); ok {
		_spec.SetField(problemset.FieldEndTime, field.TypeTime, value)
		_node.EndTime = value
	}
	if value, ok := _c.mutation.Status(); ok {
		_spec.SetField(problemset.FieldStatus, field.TypeEnum, value)
		_node.Status = value
	}
	if nodes := _c.mutation.SubmissionsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   problemset.SubmissionsTable,
			Columns: []string{problemset.SubmissionsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(submissionrecord.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.AdminProblemSetsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   problemset.AdminProblemSetsTable,
			Columns: []string{problemset.AdminProblemSetsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(adminproblemset.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.ProblemSetProblemsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   problemset.ProblemSetProblemsTable,
			Columns: []string{problemset.ProblemSetProblemsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(problemset_problem.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.ProblemSetUsersIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   problemset.ProblemSetUsersTable,
			Columns: []string{problemset.ProblemSetUsersColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(problemset_user.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// ProblemSetCreateBulk is the builder for creating many ProblemSet entities in bulk.
type ProblemSetCreateBulk struct {
	config
	err      error
	builders []*ProblemSetCreate
}

// Save creates the ProblemSet entities in the database.
func (_c *ProblemSetCreateBulk) Save(ctx context.Context) ([]*ProblemSet, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*ProblemSet, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*ProblemSetMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil && nodes[i].ID == 0 {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int64(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *ProblemSetCreateBulk) SaveX(ctx context.Context) []*ProblemSet {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *ProblemSetCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *ProblemSetCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
