// Code generated by ent, DO NOT EDIT.

package ent

import (
	"cascade-oj/ent/predicate"
	"cascade-oj/ent/problem"
	"cascade-oj/ent/problemjudgeconfig"
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// ProblemJudgeConfigUpdate is the builder for updating ProblemJudgeConfig entities.
type ProblemJudgeConfigUpdate struct {
	config
	hooks    []Hook
	mutation *ProblemJudgeConfigMutation
}

// Where appends a list predicates to the ProblemJudgeConfigUpdate builder.
func (_u *ProblemJudgeConfigUpdate) Where(ps ...predicate.ProblemJudgeConfig) *ProblemJudgeConfigUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetConfigName sets the "config_name" field.
func (_u *ProblemJudgeConfigUpdate) SetConfigName(v string) *ProblemJudgeConfigUpdate {
	_u.mutation.SetConfigName(v)
	return _u
}

// SetNillableConfigName sets the "config_name" field if the given value is not nil.
func (_u *ProblemJudgeConfigUpdate) SetNillableConfigName(v *string) *ProblemJudgeConfigUpdate {
	if v != nil {
		_u.SetConfigName(*v)
	}
	return _u
}

// SetDescription sets the "description" field.
func (_u *ProblemJudgeConfigUpdate) SetDescription(v string) *ProblemJudgeConfigUpdate {
	_u.mutation.SetDescription(v)
	return _u
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (_u *ProblemJudgeConfigUpdate) SetNillableDescription(v *string) *ProblemJudgeConfigUpdate {
	if v != nil {
		_u.SetDescription(*v)
	}
	return _u
}

// SetSubmissionQueueName sets the "submission_queue_name" field.
func (_u *ProblemJudgeConfigUpdate) SetSubmissionQueueName(v string) *ProblemJudgeConfigUpdate {
	_u.mutation.SetSubmissionQueueName(v)
	return _u
}

// SetNillableSubmissionQueueName sets the "submission_queue_name" field if the given value is not nil.
func (_u *ProblemJudgeConfigUpdate) SetNillableSubmissionQueueName(v *string) *ProblemJudgeConfigUpdate {
	if v != nil {
		_u.SetSubmissionQueueName(*v)
	}
	return _u
}

// SetSelfTestQueueName sets the "self_test_queue_name" field.
func (_u *ProblemJudgeConfigUpdate) SetSelfTestQueueName(v string) *ProblemJudgeConfigUpdate {
	_u.mutation.SetSelfTestQueueName(v)
	return _u
}

// SetNillableSelfTestQueueName sets the "self_test_queue_name" field if the given value is not nil.
func (_u *ProblemJudgeConfigUpdate) SetNillableSelfTestQueueName(v *string) *ProblemJudgeConfigUpdate {
	if v != nil {
		_u.SetSelfTestQueueName(*v)
	}
	return _u
}

// SetJudgeEngine sets the "judge_engine" field.
func (_u *ProblemJudgeConfigUpdate) SetJudgeEngine(v string) *ProblemJudgeConfigUpdate {
	_u.mutation.SetJudgeEngine(v)
	return _u
}

// SetNillableJudgeEngine sets the "judge_engine" field if the given value is not nil.
func (_u *ProblemJudgeConfigUpdate) SetNillableJudgeEngine(v *string) *ProblemJudgeConfigUpdate {
	if v != nil {
		_u.SetJudgeEngine(*v)
	}
	return _u
}

// AddJudgeConfigIDs adds the "judge_config" edge to the Problem entity by IDs.
func (_u *ProblemJudgeConfigUpdate) AddJudgeConfigIDs(ids ...int64) *ProblemJudgeConfigUpdate {
	_u.mutation.AddJudgeConfigIDs(ids...)
	return _u
}

// AddJudgeConfig adds the "judge_config" edges to the Problem entity.
func (_u *ProblemJudgeConfigUpdate) AddJudgeConfig(v ...*Problem) *ProblemJudgeConfigUpdate {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddJudgeConfigIDs(ids...)
}

// Mutation returns the ProblemJudgeConfigMutation object of the builder.
func (_u *ProblemJudgeConfigUpdate) Mutation() *ProblemJudgeConfigMutation {
	return _u.mutation
}

// ClearJudgeConfig clears all "judge_config" edges to the Problem entity.
func (_u *ProblemJudgeConfigUpdate) ClearJudgeConfig() *ProblemJudgeConfigUpdate {
	_u.mutation.ClearJudgeConfig()
	return _u
}

// RemoveJudgeConfigIDs removes the "judge_config" edge to Problem entities by IDs.
func (_u *ProblemJudgeConfigUpdate) RemoveJudgeConfigIDs(ids ...int64) *ProblemJudgeConfigUpdate {
	_u.mutation.RemoveJudgeConfigIDs(ids...)
	return _u
}

// RemoveJudgeConfig removes "judge_config" edges to Problem entities.
func (_u *ProblemJudgeConfigUpdate) RemoveJudgeConfig(v ...*Problem) *ProblemJudgeConfigUpdate {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveJudgeConfigIDs(ids...)
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *ProblemJudgeConfigUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *ProblemJudgeConfigUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *ProblemJudgeConfigUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *ProblemJudgeConfigUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

func (_u *ProblemJudgeConfigUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	_spec := sqlgraph.NewUpdateSpec(problemjudgeconfig.Table, problemjudgeconfig.Columns, sqlgraph.NewFieldSpec(problemjudgeconfig.FieldID, field.TypeInt64))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.ConfigName(); ok {
		_spec.SetField(problemjudgeconfig.FieldConfigName, field.TypeString, value)
	}
	if value, ok := _u.mutation.Description(); ok {
		_spec.SetField(problemjudgeconfig.FieldDescription, field.TypeString, value)
	}
	if value, ok := _u.mutation.SubmissionQueueName(); ok {
		_spec.SetField(problemjudgeconfig.FieldSubmissionQueueName, field.TypeString, value)
	}
	if value, ok := _u.mutation.SelfTestQueueName(); ok {
		_spec.SetField(problemjudgeconfig.FieldSelfTestQueueName, field.TypeString, value)
	}
	if value, ok := _u.mutation.JudgeEngine(); ok {
		_spec.SetField(problemjudgeconfig.FieldJudgeEngine, field.TypeString, value)
	}
	if _u.mutation.JudgeConfigCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   problemjudgeconfig.JudgeConfigTable,
			Columns: []string{problemjudgeconfig.JudgeConfigColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(problem.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedJudgeConfigIDs(); len(nodes) > 0 && !_u.mutation.JudgeConfigCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   problemjudgeconfig.JudgeConfigTable,
			Columns: []string{problemjudgeconfig.JudgeConfigColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(problem.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.JudgeConfigIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   problemjudgeconfig.JudgeConfigTable,
			Columns: []string{problemjudgeconfig.JudgeConfigColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(problem.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{problemjudgeconfig.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// ProblemJudgeConfigUpdateOne is the builder for updating a single ProblemJudgeConfig entity.
type ProblemJudgeConfigUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *ProblemJudgeConfigMutation
}

// SetConfigName sets the "config_name" field.
func (_u *ProblemJudgeConfigUpdateOne) SetConfigName(v string) *ProblemJudgeConfigUpdateOne {
	_u.mutation.SetConfigName(v)
	return _u
}

// SetNillableConfigName sets the "config_name" field if the given value is not nil.
func (_u *ProblemJudgeConfigUpdateOne) SetNillableConfigName(v *string) *ProblemJudgeConfigUpdateOne {
	if v != nil {
		_u.SetConfigName(*v)
	}
	return _u
}

// SetDescription sets the "description" field.
func (_u *ProblemJudgeConfigUpdateOne) SetDescription(v string) *ProblemJudgeConfigUpdateOne {
	_u.mutation.SetDescription(v)
	return _u
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (_u *ProblemJudgeConfigUpdateOne) SetNillableDescription(v *string) *ProblemJudgeConfigUpdateOne {
	if v != nil {
		_u.SetDescription(*v)
	}
	return _u
}

// SetSubmissionQueueName sets the "submission_queue_name" field.
func (_u *ProblemJudgeConfigUpdateOne) SetSubmissionQueueName(v string) *ProblemJudgeConfigUpdateOne {
	_u.mutation.SetSubmissionQueueName(v)
	return _u
}

// SetNillableSubmissionQueueName sets the "submission_queue_name" field if the given value is not nil.
func (_u *ProblemJudgeConfigUpdateOne) SetNillableSubmissionQueueName(v *string) *ProblemJudgeConfigUpdateOne {
	if v != nil {
		_u.SetSubmissionQueueName(*v)
	}
	return _u
}

// SetSelfTestQueueName sets the "self_test_queue_name" field.
func (_u *ProblemJudgeConfigUpdateOne) SetSelfTestQueueName(v string) *ProblemJudgeConfigUpdateOne {
	_u.mutation.SetSelfTestQueueName(v)
	return _u
}

// SetNillableSelfTestQueueName sets the "self_test_queue_name" field if the given value is not nil.
func (_u *ProblemJudgeConfigUpdateOne) SetNillableSelfTestQueueName(v *string) *ProblemJudgeConfigUpdateOne {
	if v != nil {
		_u.SetSelfTestQueueName(*v)
	}
	return _u
}

// SetJudgeEngine sets the "judge_engine" field.
func (_u *ProblemJudgeConfigUpdateOne) SetJudgeEngine(v string) *ProblemJudgeConfigUpdateOne {
	_u.mutation.SetJudgeEngine(v)
	return _u
}

// SetNillableJudgeEngine sets the "judge_engine" field if the given value is not nil.
func (_u *ProblemJudgeConfigUpdateOne) SetNillableJudgeEngine(v *string) *ProblemJudgeConfigUpdateOne {
	if v != nil {
		_u.SetJudgeEngine(*v)
	}
	return _u
}

// AddJudgeConfigIDs adds the "judge_config" edge to the Problem entity by IDs.
func (_u *ProblemJudgeConfigUpdateOne) AddJudgeConfigIDs(ids ...int64) *ProblemJudgeConfigUpdateOne {
	_u.mutation.AddJudgeConfigIDs(ids...)
	return _u
}

// AddJudgeConfig adds the "judge_config" edges to the Problem entity.
func (_u *ProblemJudgeConfigUpdateOne) AddJudgeConfig(v ...*Problem) *ProblemJudgeConfigUpdateOne {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddJudgeConfigIDs(ids...)
}

// Mutation returns the ProblemJudgeConfigMutation object of the builder.
func (_u *ProblemJudgeConfigUpdateOne) Mutation() *ProblemJudgeConfigMutation {
	return _u.mutation
}

// ClearJudgeConfig clears all "judge_config" edges to the Problem entity.
func (_u *ProblemJudgeConfigUpdateOne) ClearJudgeConfig() *ProblemJudgeConfigUpdateOne {
	_u.mutation.ClearJudgeConfig()
	return _u
}

// RemoveJudgeConfigIDs removes the "judge_config" edge to Problem entities by IDs.
func (_u *ProblemJudgeConfigUpdateOne) RemoveJudgeConfigIDs(ids ...int64) *ProblemJudgeConfigUpdateOne {
	_u.mutation.RemoveJudgeConfigIDs(ids...)
	return _u
}

// RemoveJudgeConfig removes "judge_config" edges to Problem entities.
func (_u *ProblemJudgeConfigUpdateOne) RemoveJudgeConfig(v ...*Problem) *ProblemJudgeConfigUpdateOne {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveJudgeConfigIDs(ids...)
}

// Where appends a list predicates to the ProblemJudgeConfigUpdate builder.
func (_u *ProblemJudgeConfigUpdateOne) Where(ps ...predicate.ProblemJudgeConfig) *ProblemJudgeConfigUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *ProblemJudgeConfigUpdateOne) Select(field string, fields ...string) *ProblemJudgeConfigUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated ProblemJudgeConfig entity.
func (_u *ProblemJudgeConfigUpdateOne) Save(ctx context.Context) (*ProblemJudgeConfig, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *ProblemJudgeConfigUpdateOne) SaveX(ctx context.Context) *ProblemJudgeConfig {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *ProblemJudgeConfigUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *ProblemJudgeConfigUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

func (_u *ProblemJudgeConfigUpdateOne) sqlSave(ctx context.Context) (_node *ProblemJudgeConfig, err error) {
	_spec := sqlgraph.NewUpdateSpec(problemjudgeconfig.Table, problemjudgeconfig.Columns, sqlgraph.NewFieldSpec(problemjudgeconfig.FieldID, field.TypeInt64))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "ProblemJudgeConfig.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, problemjudgeconfig.FieldID)
		for _, f := range fields {
			if !problemjudgeconfig.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != problemjudgeconfig.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.ConfigName(); ok {
		_spec.SetField(problemjudgeconfig.FieldConfigName, field.TypeString, value)
	}
	if value, ok := _u.mutation.Description(); ok {
		_spec.SetField(problemjudgeconfig.FieldDescription, field.TypeString, value)
	}
	if value, ok := _u.mutation.SubmissionQueueName(); ok {
		_spec.SetField(problemjudgeconfig.FieldSubmissionQueueName, field.TypeString, value)
	}
	if value, ok := _u.mutation.SelfTestQueueName(); ok {
		_spec.SetField(problemjudgeconfig.FieldSelfTestQueueName, field.TypeString, value)
	}
	if value, ok := _u.mutation.JudgeEngine(); ok {
		_spec.SetField(problemjudgeconfig.FieldJudgeEngine, field.TypeString, value)
	}
	if _u.mutation.JudgeConfigCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   problemjudgeconfig.JudgeConfigTable,
			Columns: []string{problemjudgeconfig.JudgeConfigColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(problem.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedJudgeConfigIDs(); len(nodes) > 0 && !_u.mutation.JudgeConfigCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   problemjudgeconfig.JudgeConfigTable,
			Columns: []string{problemjudgeconfig.JudgeConfigColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(problem.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.JudgeConfigIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   problemjudgeconfig.JudgeConfigTable,
			Columns: []string{problemjudgeconfig.JudgeConfigColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(problem.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &ProblemJudgeConfig{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{problemjudgeconfig.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
