// Code generated by ent, DO NOT EDIT.

package ent

import (
	"cascade-oj/ent/alertevent"
	"cascade-oj/ent/alertreport"
	"cascade-oj/ent/announcement"
	"cascade-oj/ent/casegroupresult"
	"cascade-oj/ent/caseresult"
	"cascade-oj/ent/competitor_list"
	"cascade-oj/ent/judgerecord"
	"cascade-oj/ent/problem"
	"cascade-oj/ent/problemjudgeconfig"
	"cascade-oj/ent/problemset"
	"cascade-oj/ent/problemset_includes"
	"cascade-oj/ent/problemsetmanager"
	"cascade-oj/ent/problemtemplate"
	"cascade-oj/ent/schema"
	"cascade-oj/ent/submissionrecord"
	"cascade-oj/ent/systemlog"
	"cascade-oj/ent/user"
	"time"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	alerteventFields := schema.AlertEvent{}.Fields()
	_ = alerteventFields
	// alerteventDescSource is the schema descriptor for source field.
	alerteventDescSource := alerteventFields[1].Descriptor()
	// alertevent.SourceValidator is a validator for the "source" field. It is called by the builders before save.
	alertevent.SourceValidator = func() func(string) error {
		validators := alerteventDescSource.Validators
		fns := [...]func(string) error{
			validators[0].(func(string) error),
			validators[1].(func(string) error),
		}
		return func(source string) error {
			for _, fn := range fns {
				if err := fn(source); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	// alerteventDescMetricName is the schema descriptor for metric_name field.
	alerteventDescMetricName := alerteventFields[3].Descriptor()
	// alertevent.DefaultMetricName holds the default value on creation for the metric_name field.
	alertevent.DefaultMetricName = alerteventDescMetricName.Default.(string)
	// alertevent.MetricNameValidator is a validator for the "metric_name" field. It is called by the builders before save.
	alertevent.MetricNameValidator = alerteventDescMetricName.Validators[0].(func(string) error)
	// alerteventDescMetricValue is the schema descriptor for metric_value field.
	alerteventDescMetricValue := alerteventFields[4].Descriptor()
	// alertevent.DefaultMetricValue holds the default value on creation for the metric_value field.
	alertevent.DefaultMetricValue = alerteventDescMetricValue.Default.(float64)
	// alerteventDescThreshold is the schema descriptor for threshold field.
	alerteventDescThreshold := alerteventFields[5].Descriptor()
	// alertevent.DefaultThreshold holds the default value on creation for the threshold field.
	alertevent.DefaultThreshold = alerteventDescThreshold.Default.(float64)
	// alerteventDescReceivedAt is the schema descriptor for received_at field.
	alerteventDescReceivedAt := alerteventFields[7].Descriptor()
	// alertevent.DefaultReceivedAt holds the default value on creation for the received_at field.
	alertevent.DefaultReceivedAt = alerteventDescReceivedAt.Default.(func() time.Time)
	// alerteventDescAggregatedInto is the schema descriptor for aggregated_into field.
	alerteventDescAggregatedInto := alerteventFields[8].Descriptor()
	// alertevent.DefaultAggregatedInto holds the default value on creation for the aggregated_into field.
	alertevent.DefaultAggregatedInto = alerteventDescAggregatedInto.Default.(int64)
	// alerteventDescID is the schema descriptor for id field.
	alerteventDescID := alerteventFields[0].Descriptor()
	// alertevent.IDValidator is a validator for the "id" field. It is called by the builders before save.
	alertevent.IDValidator = alerteventDescID.Validators[0].(func(int64) error)
	alertreportFields := schema.AlertReport{}.Fields()
	_ = alertreportFields
	// alertreportDescTitle is the schema descriptor for title field.
	alertreportDescTitle := alertreportFields[1].Descriptor()
	// alertreport.TitleValidator is a validator for the "title" field. It is called by the builders before save.
	alertreport.TitleValidator = func() func(string) error {
		validators := alertreportDescTitle.Validators
		fns := [...]func(string) error{
			validators[0].(func(string) error),
			validators[1].(func(string) error),
		}
		return func(title string) error {
			for _, fn := range fns {
				if err := fn(title); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	// alertreportDescSummary is the schema descriptor for summary field.
	alertreportDescSummary := alertreportFields[2].Descriptor()
	// alertreport.SummaryValidator is a validator for the "summary" field. It is called by the builders before save.
	alertreport.SummaryValidator = alertreportDescSummary.Validators[0].(func(string) error)
	// alertreportDescNoiseCount is the schema descriptor for noise_count field.
	alertreportDescNoiseCount := alertreportFields[5].Descriptor()
	// alertreport.DefaultNoiseCount holds the default value on creation for the noise_count field.
	alertreport.DefaultNoiseCount = alertreportDescNoiseCount.Default.(int)
	// alertreportDescRealRiskCount is the schema descriptor for real_risk_count field.
	alertreportDescRealRiskCount := alertreportFields[6].Descriptor()
	// alertreport.DefaultRealRiskCount holds the default value on creation for the real_risk_count field.
	alertreport.DefaultRealRiskCount = alertreportDescRealRiskCount.Default.(int)
	// alertreportDescCreatedAt is the schema descriptor for created_at field.
	alertreportDescCreatedAt := alertreportFields[9].Descriptor()
	// alertreport.DefaultCreatedAt holds the default value on creation for the created_at field.
	alertreport.DefaultCreatedAt = alertreportDescCreatedAt.Default.(func() time.Time)
	// alertreportDescID is the schema descriptor for id field.
	alertreportDescID := alertreportFields[0].Descriptor()
	// alertreport.IDValidator is a validator for the "id" field. It is called by the builders before save.
	alertreport.IDValidator = alertreportDescID.Validators[0].(func(int64) error)
	announcementFields := schema.Announcement{}.Fields()
	_ = announcementFields
	// announcementDescPublisherID is the schema descriptor for publisher_id field.
	announcementDescPublisherID := announcementFields[1].Descriptor()
	// announcement.PublisherIDValidator is a validator for the "publisher_id" field. It is called by the builders before save.
	announcement.PublisherIDValidator = announcementDescPublisherID.Validators[0].(func(int64) error)
	// announcementDescTitle is the schema descriptor for title field.
	announcementDescTitle := announcementFields[2].Descriptor()
	// announcement.TitleValidator is a validator for the "title" field. It is called by the builders before save.
	announcement.TitleValidator = func() func(string) error {
		validators := announcementDescTitle.Validators
		fns := [...]func(string) error{
			validators[0].(func(string) error),
			validators[1].(func(string) error),
		}
		return func(title string) error {
			for _, fn := range fns {
				if err := fn(title); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	// announcementDescContent is the schema descriptor for content field.
	announcementDescContent := announcementFields[3].Descriptor()
	// announcement.ContentValidator is a validator for the "content" field. It is called by the builders before save.
	announcement.ContentValidator = announcementDescContent.Validators[0].(func(string) error)
	// announcementDescID is the schema descriptor for id field.
	announcementDescID := announcementFields[0].Descriptor()
	// announcement.IDValidator is a validator for the "id" field. It is called by the builders before save.
	announcement.IDValidator = announcementDescID.Validators[0].(func(int64) error)
	casegroupresultFields := schema.CaseGroupResult{}.Fields()
	_ = casegroupresultFields
	// casegroupresultDescStatus is the schema descriptor for status field.
	casegroupresultDescStatus := casegroupresultFields[2].Descriptor()
	// casegroupresult.DefaultStatus holds the default value on creation for the status field.
	casegroupresult.DefaultStatus = casegroupresultDescStatus.Default.(int16)
	// casegroupresultDescScore is the schema descriptor for score field.
	casegroupresultDescScore := casegroupresultFields[5].Descriptor()
	// casegroupresult.DefaultScore holds the default value on creation for the score field.
	casegroupresult.DefaultScore = casegroupresultDescScore.Default.(int)
	// casegroupresultDescID is the schema descriptor for id field.
	casegroupresultDescID := casegroupresultFields[0].Descriptor()
	// casegroupresult.IDValidator is a validator for the "id" field. It is called by the builders before save.
	casegroupresult.IDValidator = casegroupresultDescID.Validators[0].(func(int64) error)
	caseresultFields := schema.CaseResult{}.Fields()
	_ = caseresultFields
	// caseresultDescStatus is the schema descriptor for status field.
	caseresultDescStatus := caseresultFields[2].Descriptor()
	// caseresult.DefaultStatus holds the default value on creation for the status field.
	caseresult.DefaultStatus = caseresultDescStatus.Default.(int16)
	// caseresultDescStdout is the schema descriptor for stdout field.
	caseresultDescStdout := caseresultFields[5].Descriptor()
	// caseresult.DefaultStdout holds the default value on creation for the stdout field.
	caseresult.DefaultStdout = caseresultDescStdout.Default.(string)
	// caseresultDescStderr is the schema descriptor for stderr field.
	caseresultDescStderr := caseresultFields[6].Descriptor()
	// caseresult.DefaultStderr holds the default value on creation for the stderr field.
	caseresult.DefaultStderr = caseresultDescStderr.Default.(string)
	// caseresultDescScore is the schema descriptor for score field.
	caseresultDescScore := caseresultFields[7].Descriptor()
	// caseresult.DefaultScore holds the default value on creation for the score field.
	caseresult.DefaultScore = caseresultDescScore.Default.(int)
	// caseresultDescID is the schema descriptor for id field.
	caseresultDescID := caseresultFields[0].Descriptor()
	// caseresult.IDValidator is a validator for the "id" field. It is called by the builders before save.
	caseresult.IDValidator = caseresultDescID.Validators[0].(func(int64) error)
	competitor_listFields := schema.Competitor_List{}.Fields()
	_ = competitor_listFields
	// competitor_listDescUserID is the schema descriptor for user_id field.
	competitor_listDescUserID := competitor_listFields[1].Descriptor()
	// competitor_list.UserIDValidator is a validator for the "user_id" field. It is called by the builders before save.
	competitor_list.UserIDValidator = competitor_listDescUserID.Validators[0].(func(int64) error)
	// competitor_listDescProblemSetID is the schema descriptor for problem_set_id field.
	competitor_listDescProblemSetID := competitor_listFields[2].Descriptor()
	// competitor_list.ProblemSetIDValidator is a validator for the "problem_set_id" field. It is called by the builders before save.
	competitor_list.ProblemSetIDValidator = competitor_listDescProblemSetID.Validators[0].(func(int64) error)
	// competitor_listDescTotalScore is the schema descriptor for total_score field.
	competitor_listDescTotalScore := competitor_listFields[3].Descriptor()
	// competitor_list.DefaultTotalScore holds the default value on creation for the total_score field.
	competitor_list.DefaultTotalScore = competitor_listDescTotalScore.Default.(int)
	// competitor_listDescID is the schema descriptor for id field.
	competitor_listDescID := competitor_listFields[0].Descriptor()
	// competitor_list.IDValidator is a validator for the "id" field. It is called by the builders before save.
	competitor_list.IDValidator = competitor_listDescID.Validators[0].(func(int64) error)
	judgerecordFields := schema.JudgeRecord{}.Fields()
	_ = judgerecordFields
	// judgerecordDescProblemID is the schema descriptor for problem_id field.
	judgerecordDescProblemID := judgerecordFields[1].Descriptor()
	// judgerecord.ProblemIDValidator is a validator for the "problem_id" field. It is called by the builders before save.
	judgerecord.ProblemIDValidator = judgerecordDescProblemID.Validators[0].(func(int64) error)
	// judgerecordDescUserID is the schema descriptor for user_id field.
	judgerecordDescUserID := judgerecordFields[2].Descriptor()
	// judgerecord.UserIDValidator is a validator for the "user_id" field. It is called by the builders before save.
	judgerecord.UserIDValidator = judgerecordDescUserID.Validators[0].(func(int64) error)
	// judgerecordDescStatus is the schema descriptor for status field.
	judgerecordDescStatus := judgerecordFields[4].Descriptor()
	// judgerecord.DefaultStatus holds the default value on creation for the status field.
	judgerecord.DefaultStatus = judgerecordDescStatus.Default.(int16)
	// judgerecordDescJudgeStartTime is the schema descriptor for judge_start_time field.
	judgerecordDescJudgeStartTime := judgerecordFields[5].Descriptor()
	// judgerecord.DefaultJudgeStartTime holds the default value on creation for the judge_start_time field.
	judgerecord.DefaultJudgeStartTime = judgerecordDescJudgeStartTime.Default.(time.Time)
	// judgerecordDescCode is the schema descriptor for code field.
	judgerecordDescCode := judgerecordFields[8].Descriptor()
	// judgerecord.CodeValidator is a validator for the "code" field. It is called by the builders before save.
	judgerecord.CodeValidator = judgerecordDescCode.Validators[0].(func(string) error)
	// judgerecordDescLanguage is the schema descriptor for language field.
	judgerecordDescLanguage := judgerecordFields[9].Descriptor()
	// judgerecord.DefaultLanguage holds the default value on creation for the language field.
	judgerecord.DefaultLanguage = judgerecordDescLanguage.Default.(string)
	// judgerecordDescID is the schema descriptor for id field.
	judgerecordDescID := judgerecordFields[0].Descriptor()
	// judgerecord.IDValidator is a validator for the "id" field. It is called by the builders before save.
	judgerecord.IDValidator = judgerecordDescID.Validators[0].(func(int64) error)
	problemFields := schema.Problem{}.Fields()
	_ = problemFields
	// problemDescCreatorID is the schema descriptor for creator_id field.
	problemDescCreatorID := problemFields[1].Descriptor()
	// problem.CreatorIDValidator is a validator for the "creator_id" field. It is called by the builders before save.
	problem.CreatorIDValidator = problemDescCreatorID.Validators[0].(func(int64) error)
	// problemDescTitle is the schema descriptor for title field.
	problemDescTitle := problemFields[2].Descriptor()
	// problem.TitleValidator is a validator for the "title" field. It is called by the builders before save.
	problem.TitleValidator = func() func(string) error {
		validators := problemDescTitle.Validators
		fns := [...]func(string) error{
			validators[0].(func(string) error),
			validators[1].(func(string) error),
		}
		return func(title string) error {
			for _, fn := range fns {
				if err := fn(title); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	// problemDescDescription is the schema descriptor for description field.
	problemDescDescription := problemFields[3].Descriptor()
	// problem.DescriptionValidator is a validator for the "description" field. It is called by the builders before save.
	problem.DescriptionValidator = problemDescDescription.Validators[0].(func(string) error)
	// problemDescCaseVersion is the schema descriptor for case_version field.
	problemDescCaseVersion := problemFields[5].Descriptor()
	// problem.DefaultCaseVersion holds the default value on creation for the case_version field.
	problem.DefaultCaseVersion = problemDescCaseVersion.Default.(int16)
	// problemDescTimeLimitMs is the schema descriptor for time_limit_ms field.
	problemDescTimeLimitMs := problemFields[6].Descriptor()
	// problem.TimeLimitMsValidator is a validator for the "time_limit_ms" field. It is called by the builders before save.
	problem.TimeLimitMsValidator = problemDescTimeLimitMs.Validators[0].(func(int) error)
	// problemDescMemoryLimitKB is the schema descriptor for memory_limit_kb field.
	problemDescMemoryLimitKB := problemFields[7].Descriptor()
	// problem.MemoryLimitKBValidator is a validator for the "memory_limit_kb" field. It is called by the builders before save.
	problem.MemoryLimitKBValidator = problemDescMemoryLimitKB.Validators[0].(func(int) error)
	// problemDescID is the schema descriptor for id field.
	problemDescID := problemFields[0].Descriptor()
	// problem.IDValidator is a validator for the "id" field. It is called by the builders before save.
	problem.IDValidator = problemDescID.Validators[0].(func(int64) error)
	problemjudgeconfigFields := schema.ProblemJudgeConfig{}.Fields()
	_ = problemjudgeconfigFields
	// problemjudgeconfigDescDescription is the schema descriptor for description field.
	problemjudgeconfigDescDescription := problemjudgeconfigFields[2].Descriptor()
	// problemjudgeconfig.DefaultDescription holds the default value on creation for the description field.
	problemjudgeconfig.DefaultDescription = problemjudgeconfigDescDescription.Default.(string)
	// problemjudgeconfigDescSubmissionQueueName is the schema descriptor for submission_queue_name field.
	problemjudgeconfigDescSubmissionQueueName := problemjudgeconfigFields[3].Descriptor()
	// problemjudgeconfig.DefaultSubmissionQueueName holds the default value on creation for the submission_queue_name field.
	problemjudgeconfig.DefaultSubmissionQueueName = problemjudgeconfigDescSubmissionQueueName.Default.(string)
	// problemjudgeconfigDescSelfTestQueueName is the schema descriptor for self_test_queue_name field.
	problemjudgeconfigDescSelfTestQueueName := problemjudgeconfigFields[4].Descriptor()
	// problemjudgeconfig.DefaultSelfTestQueueName holds the default value on creation for the self_test_queue_name field.
	problemjudgeconfig.DefaultSelfTestQueueName = problemjudgeconfigDescSelfTestQueueName.Default.(string)
	// problemjudgeconfigDescJudgeEngine is the schema descriptor for judge_engine field.
	problemjudgeconfigDescJudgeEngine := problemjudgeconfigFields[5].Descriptor()
	// problemjudgeconfig.DefaultJudgeEngine holds the default value on creation for the judge_engine field.
	problemjudgeconfig.DefaultJudgeEngine = problemjudgeconfigDescJudgeEngine.Default.(string)
	// problemjudgeconfigDescID is the schema descriptor for id field.
	problemjudgeconfigDescID := problemjudgeconfigFields[0].Descriptor()
	// problemjudgeconfig.IDValidator is a validator for the "id" field. It is called by the builders before save.
	problemjudgeconfig.IDValidator = problemjudgeconfigDescID.Validators[0].(func(int64) error)
	problemsetFields := schema.ProblemSet{}.Fields()
	_ = problemsetFields
	// problemsetDescName is the schema descriptor for name field.
	problemsetDescName := problemsetFields[1].Descriptor()
	// problemset.NameValidator is a validator for the "name" field. It is called by the builders before save.
	problemset.NameValidator = func() func(string) error {
		validators := problemsetDescName.Validators
		fns := [...]func(string) error{
			validators[0].(func(string) error),
			validators[1].(func(string) error),
		}
		return func(name string) error {
			for _, fn := range fns {
				if err := fn(name); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	// problemsetDescID is the schema descriptor for id field.
	problemsetDescID := problemsetFields[0].Descriptor()
	// problemset.IDValidator is a validator for the "id" field. It is called by the builders before save.
	problemset.IDValidator = problemsetDescID.Validators[0].(func(int64) error)
	problemsetmanagerFields := schema.ProblemSetManager{}.Fields()
	_ = problemsetmanagerFields
	// problemsetmanagerDescAdminID is the schema descriptor for admin_id field.
	problemsetmanagerDescAdminID := problemsetmanagerFields[1].Descriptor()
	// problemsetmanager.AdminIDValidator is a validator for the "admin_id" field. It is called by the builders before save.
	problemsetmanager.AdminIDValidator = problemsetmanagerDescAdminID.Validators[0].(func(int64) error)
	// problemsetmanagerDescProblemSetID is the schema descriptor for problem_set_id field.
	problemsetmanagerDescProblemSetID := problemsetmanagerFields[2].Descriptor()
	// problemsetmanager.ProblemSetIDValidator is a validator for the "problem_set_id" field. It is called by the builders before save.
	problemsetmanager.ProblemSetIDValidator = problemsetmanagerDescProblemSetID.Validators[0].(func(int64) error)
	// problemsetmanagerDescID is the schema descriptor for id field.
	problemsetmanagerDescID := problemsetmanagerFields[0].Descriptor()
	// problemsetmanager.IDValidator is a validator for the "id" field. It is called by the builders before save.
	problemsetmanager.IDValidator = problemsetmanagerDescID.Validators[0].(func(int64) error)
	problemset_includesFields := schema.ProblemSet_Includes{}.Fields()
	_ = problemset_includesFields
	// problemset_includesDescProblemSetID is the schema descriptor for problem_set_id field.
	problemset_includesDescProblemSetID := problemset_includesFields[1].Descriptor()
	// problemset_includes.ProblemSetIDValidator is a validator for the "problem_set_id" field. It is called by the builders before save.
	problemset_includes.ProblemSetIDValidator = problemset_includesDescProblemSetID.Validators[0].(func(int64) error)
	// problemset_includesDescProblemID is the schema descriptor for problem_id field.
	problemset_includesDescProblemID := problemset_includesFields[2].Descriptor()
	// problemset_includes.ProblemIDValidator is a validator for the "problem_id" field. It is called by the builders before save.
	problemset_includes.ProblemIDValidator = problemset_includesDescProblemID.Validators[0].(func(int64) error)
	// problemset_includesDescProblemOrder is the schema descriptor for problem_order field.
	problemset_includesDescProblemOrder := problemset_includesFields[3].Descriptor()
	// problemset_includes.ProblemOrderValidator is a validator for the "problem_order" field. It is called by the builders before save.
	problemset_includes.ProblemOrderValidator = problemset_includesDescProblemOrder.Validators[0].(func(int) error)
	// problemset_includesDescID is the schema descriptor for id field.
	problemset_includesDescID := problemset_includesFields[0].Descriptor()
	// problemset_includes.IDValidator is a validator for the "id" field. It is called by the builders before save.
	problemset_includes.IDValidator = problemset_includesDescID.Validators[0].(func(int64) error)
	problemtemplateFields := schema.ProblemTemplate{}.Fields()
	_ = problemtemplateFields
	// problemtemplateDescName is the schema descriptor for name field.
	problemtemplateDescName := problemtemplateFields[0].Descriptor()
	// problemtemplate.DefaultName holds the default value on creation for the name field.
	problemtemplate.DefaultName = problemtemplateDescName.Default.(string)
	submissionrecordFields := schema.SubmissionRecord{}.Fields()
	_ = submissionrecordFields
	// submissionrecordDescJudgeID is the schema descriptor for judge_id field.
	submissionrecordDescJudgeID := submissionrecordFields[1].Descriptor()
	// submissionrecord.JudgeIDValidator is a validator for the "judge_id" field. It is called by the builders before save.
	submissionrecord.JudgeIDValidator = submissionrecordDescJudgeID.Validators[0].(func(int64) error)
	// submissionrecordDescProblemID is the schema descriptor for problem_id field.
	submissionrecordDescProblemID := submissionrecordFields[2].Descriptor()
	// submissionrecord.ProblemIDValidator is a validator for the "problem_id" field. It is called by the builders before save.
	submissionrecord.ProblemIDValidator = submissionrecordDescProblemID.Validators[0].(func(int64) error)
	// submissionrecordDescSubmissionTime is the schema descriptor for submission_time field.
	submissionrecordDescSubmissionTime := submissionrecordFields[4].Descriptor()
	// submissionrecord.DefaultSubmissionTime holds the default value on creation for the submission_time field.
	submissionrecord.DefaultSubmissionTime = submissionrecordDescSubmissionTime.Default.(time.Time)
	// submissionrecordDescScore is the schema descriptor for score field.
	submissionrecordDescScore := submissionrecordFields[5].Descriptor()
	// submissionrecord.DefaultScore holds the default value on creation for the score field.
	submissionrecord.DefaultScore = submissionrecordDescScore.Default.(int)
	// submissionrecordDescID is the schema descriptor for id field.
	submissionrecordDescID := submissionrecordFields[0].Descriptor()
	// submissionrecord.IDValidator is a validator for the "id" field. It is called by the builders before save.
	submissionrecord.IDValidator = submissionrecordDescID.Validators[0].(func(int64) error)
	systemlogFields := schema.SystemLog{}.Fields()
	_ = systemlogFields
	// systemlogDescLogTime is the schema descriptor for log_time field.
	systemlogDescLogTime := systemlogFields[1].Descriptor()
	// systemlog.DefaultLogTime holds the default value on creation for the log_time field.
	systemlog.DefaultLogTime = systemlogDescLogTime.Default.(func() time.Time)
	// systemlogDescLogInfo is the schema descriptor for log_info field.
	systemlogDescLogInfo := systemlogFields[2].Descriptor()
	// systemlog.LogInfoValidator is a validator for the "log_info" field. It is called by the builders before save.
	systemlog.LogInfoValidator = systemlogDescLogInfo.Validators[0].(func(string) error)
	// systemlogDescID is the schema descriptor for id field.
	systemlogDescID := systemlogFields[0].Descriptor()
	// systemlog.IDValidator is a validator for the "id" field. It is called by the builders before save.
	systemlog.IDValidator = systemlogDescID.Validators[0].(func(int64) error)
	userFields := schema.User{}.Fields()
	_ = userFields
	// userDescUsername is the schema descriptor for username field.
	userDescUsername := userFields[1].Descriptor()
	// user.UsernameValidator is a validator for the "username" field. It is called by the builders before save.
	user.UsernameValidator = func() func(string) error {
		validators := userDescUsername.Validators
		fns := [...]func(string) error{
			validators[0].(func(string) error),
			validators[1].(func(string) error),
		}
		return func(username string) error {
			for _, fn := range fns {
				if err := fn(username); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	// userDescEmail is the schema descriptor for email field.
	userDescEmail := userFields[2].Descriptor()
	// user.EmailValidator is a validator for the "email" field. It is called by the builders before save.
	user.EmailValidator = func() func(string) error {
		validators := userDescEmail.Validators
		fns := [...]func(string) error{
			validators[0].(func(string) error),
			validators[1].(func(string) error),
		}
		return func(email string) error {
			for _, fn := range fns {
				if err := fn(email); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	// userDescPasswordHash is the schema descriptor for password_hash field.
	userDescPasswordHash := userFields[3].Descriptor()
	// user.PasswordHashValidator is a validator for the "password_hash" field. It is called by the builders before save.
	user.PasswordHashValidator = func() func(string) error {
		validators := userDescPasswordHash.Validators
		fns := [...]func(string) error{
			validators[0].(func(string) error),
			validators[1].(func(string) error),
		}
		return func(password_hash string) error {
			for _, fn := range fns {
				if err := fn(password_hash); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	// userDescID is the schema descriptor for id field.
	userDescID := userFields[0].Descriptor()
	// user.IDValidator is a validator for the "id" field. It is called by the builders before save.
	user.IDValidator = userDescID.Validators[0].(func(int64) error)
}
