// Code generated by ent, DO NOT EDIT.

package ent

import (
	"cascade-oj/ent/judgerecord"
	"cascade-oj/ent/predicate"
	"cascade-oj/ent/problem"
	"cascade-oj/ent/problemset"
	"cascade-oj/ent/submissionrecord"
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// SubmissionRecordUpdate is the builder for updating SubmissionRecord entities.
type SubmissionRecordUpdate struct {
	config
	hooks    []Hook
	mutation *SubmissionRecordMutation
}

// Where appends a list predicates to the SubmissionRecordUpdate builder.
func (_u *SubmissionRecordUpdate) Where(ps ...predicate.SubmissionRecord) *SubmissionRecordUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetJudgeID sets the "judge_id" field.
func (_u *SubmissionRecordUpdate) SetJudgeID(v int64) *SubmissionRecordUpdate {
	_u.mutation.SetJudgeID(v)
	return _u
}

// SetNillableJudgeID sets the "judge_id" field if the given value is not nil.
func (_u *SubmissionRecordUpdate) SetNillableJudgeID(v *int64) *SubmissionRecordUpdate {
	if v != nil {
		_u.SetJudgeID(*v)
	}
	return _u
}

// SetProblemID sets the "problem_id" field.
func (_u *SubmissionRecordUpdate) SetProblemID(v int64) *SubmissionRecordUpdate {
	_u.mutation.SetProblemID(v)
	return _u
}

// SetNillableProblemID sets the "problem_id" field if the given value is not nil.
func (_u *SubmissionRecordUpdate) SetNillableProblemID(v *int64) *SubmissionRecordUpdate {
	if v != nil {
		_u.SetProblemID(*v)
	}
	return _u
}

// SetProblemSetID sets the "problem_set_id" field.
func (_u *SubmissionRecordUpdate) SetProblemSetID(v int64) *SubmissionRecordUpdate {
	_u.mutation.SetProblemSetID(v)
	return _u
}

// SetNillableProblemSetID sets the "problem_set_id" field if the given value is not nil.
func (_u *SubmissionRecordUpdate) SetNillableProblemSetID(v *int64) *SubmissionRecordUpdate {
	if v != nil {
		_u.SetProblemSetID(*v)
	}
	return _u
}

// ClearProblemSetID clears the value of the "problem_set_id" field.
func (_u *SubmissionRecordUpdate) ClearProblemSetID() *SubmissionRecordUpdate {
	_u.mutation.ClearProblemSetID()
	return _u
}

// SetSubmissionTime sets the "submission_time" field.
func (_u *SubmissionRecordUpdate) SetSubmissionTime(v time.Time) *SubmissionRecordUpdate {
	_u.mutation.SetSubmissionTime(v)
	return _u
}

// SetNillableSubmissionTime sets the "submission_time" field if the given value is not nil.
func (_u *SubmissionRecordUpdate) SetNillableSubmissionTime(v *time.Time) *SubmissionRecordUpdate {
	if v != nil {
		_u.SetSubmissionTime(*v)
	}
	return _u
}

// SetScore sets the "score" field.
func (_u *SubmissionRecordUpdate) SetScore(v int) *SubmissionRecordUpdate {
	_u.mutation.ResetScore()
	_u.mutation.SetScore(v)
	return _u
}

// SetNillableScore sets the "score" field if the given value is not nil.
func (_u *SubmissionRecordUpdate) SetNillableScore(v *int) *SubmissionRecordUpdate {
	if v != nil {
		_u.SetScore(*v)
	}
	return _u
}

// AddScore adds value to the "score" field.
func (_u *SubmissionRecordUpdate) AddScore(v int) *SubmissionRecordUpdate {
	_u.mutation.AddScore(v)
	return _u
}

// SetJudge sets the "judge" edge to the JudgeRecord entity.
func (_u *SubmissionRecordUpdate) SetJudge(v *JudgeRecord) *SubmissionRecordUpdate {
	return _u.SetJudgeID(v.ID)
}

// SetProblem sets the "problem" edge to the Problem entity.
func (_u *SubmissionRecordUpdate) SetProblem(v *Problem) *SubmissionRecordUpdate {
	return _u.SetProblemID(v.ID)
}

// SetProblemSet sets the "problem_set" edge to the ProblemSet entity.
func (_u *SubmissionRecordUpdate) SetProblemSet(v *ProblemSet) *SubmissionRecordUpdate {
	return _u.SetProblemSetID(v.ID)
}

// Mutation returns the SubmissionRecordMutation object of the builder.
func (_u *SubmissionRecordUpdate) Mutation() *SubmissionRecordMutation {
	return _u.mutation
}

// ClearJudge clears the "judge" edge to the JudgeRecord entity.
func (_u *SubmissionRecordUpdate) ClearJudge() *SubmissionRecordUpdate {
	_u.mutation.ClearJudge()
	return _u
}

// ClearProblem clears the "problem" edge to the Problem entity.
func (_u *SubmissionRecordUpdate) ClearProblem() *SubmissionRecordUpdate {
	_u.mutation.ClearProblem()
	return _u
}

// ClearProblemSet clears the "problem_set" edge to the ProblemSet entity.
func (_u *SubmissionRecordUpdate) ClearProblemSet() *SubmissionRecordUpdate {
	_u.mutation.ClearProblemSet()
	return _u
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *SubmissionRecordUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *SubmissionRecordUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *SubmissionRecordUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *SubmissionRecordUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *SubmissionRecordUpdate) check() error {
	if v, ok := _u.mutation.JudgeID(); ok {
		if err := submissionrecord.JudgeIDValidator(v); err != nil {
			return &ValidationError{Name: "judge_id", err: fmt.Errorf(`ent: validator failed for field "SubmissionRecord.judge_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.ProblemID(); ok {
		if err := submissionrecord.ProblemIDValidator(v); err != nil {
			return &ValidationError{Name: "problem_id", err: fmt.Errorf(`ent: validator failed for field "SubmissionRecord.problem_id": %w`, err)}
		}
	}
	if _u.mutation.JudgeCleared() && len(_u.mutation.JudgeIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "SubmissionRecord.judge"`)
	}
	if _u.mutation.ProblemCleared() && len(_u.mutation.ProblemIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "SubmissionRecord.problem"`)
	}
	return nil
}

func (_u *SubmissionRecordUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(submissionrecord.Table, submissionrecord.Columns, sqlgraph.NewFieldSpec(submissionrecord.FieldID, field.TypeInt64))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.SubmissionTime(); ok {
		_spec.SetField(submissionrecord.FieldSubmissionTime, field.TypeTime, value)
	}
	if value, ok := _u.mutation.Score(); ok {
		_spec.SetField(submissionrecord.FieldScore, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedScore(); ok {
		_spec.AddField(submissionrecord.FieldScore, field.TypeInt, value)
	}
	if _u.mutation.JudgeCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   submissionrecord.JudgeTable,
			Columns: []string{submissionrecord.JudgeColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(judgerecord.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.JudgeIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   submissionrecord.JudgeTable,
			Columns: []string{submissionrecord.JudgeColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(judgerecord.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.ProblemCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   submissionrecord.ProblemTable,
			Columns: []string{submissionrecord.ProblemColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(problem.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ProblemIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   submissionrecord.ProblemTable,
			Columns: []string{submissionrecord.ProblemColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(problem.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.ProblemSetCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   submissionrecord.ProblemSetTable,
			Columns: []string{submissionrecord.ProblemSetColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(problemset.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ProblemSetIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   submissionrecord.ProblemSetTable,
			Columns: []string{submissionrecord.ProblemSetColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(problemset.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{submissionrecord.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// SubmissionRecordUpdateOne is the builder for updating a single SubmissionRecord entity.
type SubmissionRecordUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *SubmissionRecordMutation
}

// SetJudgeID sets the "judge_id" field.
func (_u *SubmissionRecordUpdateOne) SetJudgeID(v int64) *SubmissionRecordUpdateOne {
	_u.mutation.SetJudgeID(v)
	return _u
}

// SetNillableJudgeID sets the "judge_id" field if the given value is not nil.
func (_u *SubmissionRecordUpdateOne) SetNillableJudgeID(v *int64) *SubmissionRecordUpdateOne {
	if v != nil {
		_u.SetJudgeID(*v)
	}
	return _u
}

// SetProblemID sets the "problem_id" field.
func (_u *SubmissionRecordUpdateOne) SetProblemID(v int64) *SubmissionRecordUpdateOne {
	_u.mutation.SetProblemID(v)
	return _u
}

// SetNillableProblemID sets the "problem_id" field if the given value is not nil.
func (_u *SubmissionRecordUpdateOne) SetNillableProblemID(v *int64) *SubmissionRecordUpdateOne {
	if v != nil {
		_u.SetProblemID(*v)
	}
	return _u
}

// SetProblemSetID sets the "problem_set_id" field.
func (_u *SubmissionRecordUpdateOne) SetProblemSetID(v int64) *SubmissionRecordUpdateOne {
	_u.mutation.SetProblemSetID(v)
	return _u
}

// SetNillableProblemSetID sets the "problem_set_id" field if the given value is not nil.
func (_u *SubmissionRecordUpdateOne) SetNillableProblemSetID(v *int64) *SubmissionRecordUpdateOne {
	if v != nil {
		_u.SetProblemSetID(*v)
	}
	return _u
}

// ClearProblemSetID clears the value of the "problem_set_id" field.
func (_u *SubmissionRecordUpdateOne) ClearProblemSetID() *SubmissionRecordUpdateOne {
	_u.mutation.ClearProblemSetID()
	return _u
}

// SetSubmissionTime sets the "submission_time" field.
func (_u *SubmissionRecordUpdateOne) SetSubmissionTime(v time.Time) *SubmissionRecordUpdateOne {
	_u.mutation.SetSubmissionTime(v)
	return _u
}

// SetNillableSubmissionTime sets the "submission_time" field if the given value is not nil.
func (_u *SubmissionRecordUpdateOne) SetNillableSubmissionTime(v *time.Time) *SubmissionRecordUpdateOne {
	if v != nil {
		_u.SetSubmissionTime(*v)
	}
	return _u
}

// SetScore sets the "score" field.
func (_u *SubmissionRecordUpdateOne) SetScore(v int) *SubmissionRecordUpdateOne {
	_u.mutation.ResetScore()
	_u.mutation.SetScore(v)
	return _u
}

// SetNillableScore sets the "score" field if the given value is not nil.
func (_u *SubmissionRecordUpdateOne) SetNillableScore(v *int) *SubmissionRecordUpdateOne {
	if v != nil {
		_u.SetScore(*v)
	}
	return _u
}

// AddScore adds value to the "score" field.
func (_u *SubmissionRecordUpdateOne) AddScore(v int) *SubmissionRecordUpdateOne {
	_u.mutation.AddScore(v)
	return _u
}

// SetJudge sets the "judge" edge to the JudgeRecord entity.
func (_u *SubmissionRecordUpdateOne) SetJudge(v *JudgeRecord) *SubmissionRecordUpdateOne {
	return _u.SetJudgeID(v.ID)
}

// SetProblem sets the "problem" edge to the Problem entity.
func (_u *SubmissionRecordUpdateOne) SetProblem(v *Problem) *SubmissionRecordUpdateOne {
	return _u.SetProblemID(v.ID)
}

// SetProblemSet sets the "problem_set" edge to the ProblemSet entity.
func (_u *SubmissionRecordUpdateOne) SetProblemSet(v *ProblemSet) *SubmissionRecordUpdateOne {
	return _u.SetProblemSetID(v.ID)
}

// Mutation returns the SubmissionRecordMutation object of the builder.
func (_u *SubmissionRecordUpdateOne) Mutation() *SubmissionRecordMutation {
	return _u.mutation
}

// ClearJudge clears the "judge" edge to the JudgeRecord entity.
func (_u *SubmissionRecordUpdateOne) ClearJudge() *SubmissionRecordUpdateOne {
	_u.mutation.ClearJudge()
	return _u
}

// ClearProblem clears the "problem" edge to the Problem entity.
func (_u *SubmissionRecordUpdateOne) ClearProblem() *SubmissionRecordUpdateOne {
	_u.mutation.ClearProblem()
	return _u
}

// ClearProblemSet clears the "problem_set" edge to the ProblemSet entity.
func (_u *SubmissionRecordUpdateOne) ClearProblemSet() *SubmissionRecordUpdateOne {
	_u.mutation.ClearProblemSet()
	return _u
}

// Where appends a list predicates to the SubmissionRecordUpdate builder.
func (_u *SubmissionRecordUpdateOne) Where(ps ...predicate.SubmissionRecord) *SubmissionRecordUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *SubmissionRecordUpdateOne) Select(field string, fields ...string) *SubmissionRecordUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated SubmissionRecord entity.
func (_u *SubmissionRecordUpdateOne) Save(ctx context.Context) (*SubmissionRecord, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *SubmissionRecordUpdateOne) SaveX(ctx context.Context) *SubmissionRecord {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *SubmissionRecordUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *SubmissionRecordUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *SubmissionRecordUpdateOne) check() error {
	if v, ok := _u.mutation.JudgeID(); ok {
		if err := submissionrecord.JudgeIDValidator(v); err != nil {
			return &ValidationError{Name: "judge_id", err: fmt.Errorf(`ent: validator failed for field "SubmissionRecord.judge_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.ProblemID(); ok {
		if err := submissionrecord.ProblemIDValidator(v); err != nil {
			return &ValidationError{Name: "problem_id", err: fmt.Errorf(`ent: validator failed for field "SubmissionRecord.problem_id": %w`, err)}
		}
	}
	if _u.mutation.JudgeCleared() && len(_u.mutation.JudgeIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "SubmissionRecord.judge"`)
	}
	if _u.mutation.ProblemCleared() && len(_u.mutation.ProblemIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "SubmissionRecord.problem"`)
	}
	return nil
}

func (_u *SubmissionRecordUpdateOne) sqlSave(ctx context.Context) (_node *SubmissionRecord, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(submissionrecord.Table, submissionrecord.Columns, sqlgraph.NewFieldSpec(submissionrecord.FieldID, field.TypeInt64))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "SubmissionRecord.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, submissionrecord.FieldID)
		for _, f := range fields {
			if !submissionrecord.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != submissionrecord.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.SubmissionTime(); ok {
		_spec.SetField(submissionrecord.FieldSubmissionTime, field.TypeTime, value)
	}
	if value, ok := _u.mutation.Score(); ok {
		_spec.SetField(submissionrecord.FieldScore, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedScore(); ok {
		_spec.AddField(submissionrecord.FieldScore, field.TypeInt, value)
	}
	if _u.mutation.JudgeCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   submissionrecord.JudgeTable,
			Columns: []string{submissionrecord.JudgeColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(judgerecord.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.JudgeIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   submissionrecord.JudgeTable,
			Columns: []string{submissionrecord.JudgeColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(judgerecord.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.ProblemCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   submissionrecord.ProblemTable,
			Columns: []string{submissionrecord.ProblemColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(problem.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ProblemIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   submissionrecord.ProblemTable,
			Columns: []string{submissionrecord.ProblemColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(problem.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.ProblemSetCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   submissionrecord.ProblemSetTable,
			Columns: []string{submissionrecord.ProblemSetColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(problemset.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ProblemSetIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   submissionrecord.ProblemSetTable,
			Columns: []string{submissionrecord.ProblemSetColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(problemset.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &SubmissionRecord{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{submissionrecord.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
