// Code generated by ent, DO NOT EDIT.

package ent

import (
	"cascade-oj/ent/user"
	"fmt"
	"strings"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
)

// User is the model entity for the User schema.
type User struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// Username holds the value of the "username" field.
	Username string `json:"username,omitempty"`
	// Email holds the value of the "email" field.
	Email string `json:"email,omitempty"`
	// PasswordHash holds the value of the "password_hash" field.
	PasswordHash string `json:"password_hash,omitempty"`
	// Role holds the value of the "role" field.
	Role user.Role `json:"role,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the UserQuery when eager-loading is set.
	Edges        UserEdges `json:"edges"`
	selectValues sql.SelectValues
}

// UserEdges holds the relations/edges for other nodes in the graph.
type UserEdges struct {
	// Problems holds the value of the problems edge.
	Problems []*Problem `json:"problems,omitempty"`
	// JudgeRecords holds the value of the judge_records edge.
	JudgeRecords []*JudgeRecord `json:"judge_records,omitempty"`
	// Announcements holds the value of the announcements edge.
	Announcements []*Announcement `json:"announcements,omitempty"`
	// AdminProblemSets holds the value of the admin_problem_sets edge.
	AdminProblemSets []*AdminProblemSet `json:"admin_problem_sets,omitempty"`
	// ProblemSetUsers holds the value of the problem_set_users edge.
	ProblemSetUsers []*ProblemSetUser `json:"problem_set_users,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [5]bool
}

// ProblemsOrErr returns the Problems value or an error if the edge
// was not loaded in eager-loading.
func (e UserEdges) ProblemsOrErr() ([]*Problem, error) {
	if e.loadedTypes[0] {
		return e.Problems, nil
	}
	return nil, &NotLoadedError{edge: "problems"}
}

// JudgeRecordsOrErr returns the JudgeRecords value or an error if the edge
// was not loaded in eager-loading.
func (e UserEdges) JudgeRecordsOrErr() ([]*JudgeRecord, error) {
	if e.loadedTypes[1] {
		return e.JudgeRecords, nil
	}
	return nil, &NotLoadedError{edge: "judge_records"}
}

// AnnouncementsOrErr returns the Announcements value or an error if the edge
// was not loaded in eager-loading.
func (e UserEdges) AnnouncementsOrErr() ([]*Announcement, error) {
	if e.loadedTypes[2] {
		return e.Announcements, nil
	}
	return nil, &NotLoadedError{edge: "announcements"}
}

// AdminProblemSetsOrErr returns the AdminProblemSets value or an error if the edge
// was not loaded in eager-loading.
func (e UserEdges) AdminProblemSetsOrErr() ([]*AdminProblemSet, error) {
	if e.loadedTypes[3] {
		return e.AdminProblemSets, nil
	}
	return nil, &NotLoadedError{edge: "admin_problem_sets"}
}

// ProblemSetUsersOrErr returns the ProblemSetUsers value or an error if the edge
// was not loaded in eager-loading.
func (e UserEdges) ProblemSetUsersOrErr() ([]*ProblemSetUser, error) {
	if e.loadedTypes[4] {
		return e.ProblemSetUsers, nil
	}
	return nil, &NotLoadedError{edge: "problem_set_users"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*User) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case user.FieldID:
			values[i] = new(sql.NullInt64)
		case user.FieldUsername, user.FieldEmail, user.FieldPasswordHash, user.FieldRole:
			values[i] = new(sql.NullString)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the User fields.
func (_m *User) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case user.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int(value.Int64)
		case user.FieldUsername:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field username", values[i])
			} else if value.Valid {
				_m.Username = value.String
			}
		case user.FieldEmail:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field email", values[i])
			} else if value.Valid {
				_m.Email = value.String
			}
		case user.FieldPasswordHash:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field password_hash", values[i])
			} else if value.Valid {
				_m.PasswordHash = value.String
			}
		case user.FieldRole:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field role", values[i])
			} else if value.Valid {
				_m.Role = user.Role(value.String)
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the User.
// This includes values selected through modifiers, order, etc.
func (_m *User) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryProblems queries the "problems" edge of the User entity.
func (_m *User) QueryProblems() *ProblemQuery {
	return NewUserClient(_m.config).QueryProblems(_m)
}

// QueryJudgeRecords queries the "judge_records" edge of the User entity.
func (_m *User) QueryJudgeRecords() *JudgeRecordQuery {
	return NewUserClient(_m.config).QueryJudgeRecords(_m)
}

// QueryAnnouncements queries the "announcements" edge of the User entity.
func (_m *User) QueryAnnouncements() *AnnouncementQuery {
	return NewUserClient(_m.config).QueryAnnouncements(_m)
}

// QueryAdminProblemSets queries the "admin_problem_sets" edge of the User entity.
func (_m *User) QueryAdminProblemSets() *AdminProblemSetQuery {
	return NewUserClient(_m.config).QueryAdminProblemSets(_m)
}

// QueryProblemSetUsers queries the "problem_set_users" edge of the User entity.
func (_m *User) QueryProblemSetUsers() *ProblemSetUserQuery {
	return NewUserClient(_m.config).QueryProblemSetUsers(_m)
}

// Update returns a builder for updating this User.
// Note that you need to call User.Unwrap() before calling this method if this User
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *User) Update() *UserUpdateOne {
	return NewUserClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the User entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *User) Unwrap() *User {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: User is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *User) String() string {
	var builder strings.Builder
	builder.WriteString("User(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("username=")
	builder.WriteString(_m.Username)
	builder.WriteString(", ")
	builder.WriteString("email=")
	builder.WriteString(_m.Email)
	builder.WriteString(", ")
	builder.WriteString("password_hash=")
	builder.WriteString(_m.PasswordHash)
	builder.WriteString(", ")
	builder.WriteString("role=")
	builder.WriteString(fmt.Sprintf("%v", _m.Role))
	builder.WriteByte(')')
	return builder.String()
}

// Users is a parsable slice of User.
type Users []*User
