// Code generated by ent, DO NOT EDIT.

package competitor_list

import (
	"cascade-oj/ent/predicate"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

// ID filters vertices based on their ID field.
func ID(id int64) predicate.Competitor_List {
	return predicate.Competitor_List(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int64) predicate.Competitor_List {
	return predicate.Competitor_List(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int64) predicate.Competitor_List {
	return predicate.Competitor_List(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int64) predicate.Competitor_List {
	return predicate.Competitor_List(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int64) predicate.Competitor_List {
	return predicate.Competitor_List(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int64) predicate.Competitor_List {
	return predicate.Competitor_List(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int64) predicate.Competitor_List {
	return predicate.Competitor_List(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int64) predicate.Competitor_List {
	return predicate.Competitor_List(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int64) predicate.Competitor_List {
	return predicate.Competitor_List(sql.FieldLTE(FieldID, id))
}

// UserID applies equality check predicate on the "user_id" field. It's identical to UserIDEQ.
func UserID(v int64) predicate.Competitor_List {
	return predicate.Competitor_List(sql.FieldEQ(FieldUserID, v))
}

// ProblemSetID applies equality check predicate on the "problem_set_id" field. It's identical to ProblemSetIDEQ.
func ProblemSetID(v int64) predicate.Competitor_List {
	return predicate.Competitor_List(sql.FieldEQ(FieldProblemSetID, v))
}

// TotalScore applies equality check predicate on the "total_score" field. It's identical to TotalScoreEQ.
func TotalScore(v int) predicate.Competitor_List {
	return predicate.Competitor_List(sql.FieldEQ(FieldTotalScore, v))
}

// UserIDEQ applies the EQ predicate on the "user_id" field.
func UserIDEQ(v int64) predicate.Competitor_List {
	return predicate.Competitor_List(sql.FieldEQ(FieldUserID, v))
}

// UserIDNEQ applies the NEQ predicate on the "user_id" field.
func UserIDNEQ(v int64) predicate.Competitor_List {
	return predicate.Competitor_List(sql.FieldNEQ(FieldUserID, v))
}

// UserIDIn applies the In predicate on the "user_id" field.
func UserIDIn(vs ...int64) predicate.Competitor_List {
	return predicate.Competitor_List(sql.FieldIn(FieldUserID, vs...))
}

// UserIDNotIn applies the NotIn predicate on the "user_id" field.
func UserIDNotIn(vs ...int64) predicate.Competitor_List {
	return predicate.Competitor_List(sql.FieldNotIn(FieldUserID, vs...))
}

// ProblemSetIDEQ applies the EQ predicate on the "problem_set_id" field.
func ProblemSetIDEQ(v int64) predicate.Competitor_List {
	return predicate.Competitor_List(sql.FieldEQ(FieldProblemSetID, v))
}

// ProblemSetIDNEQ applies the NEQ predicate on the "problem_set_id" field.
func ProblemSetIDNEQ(v int64) predicate.Competitor_List {
	return predicate.Competitor_List(sql.FieldNEQ(FieldProblemSetID, v))
}

// ProblemSetIDIn applies the In predicate on the "problem_set_id" field.
func ProblemSetIDIn(vs ...int64) predicate.Competitor_List {
	return predicate.Competitor_List(sql.FieldIn(FieldProblemSetID, vs...))
}

// ProblemSetIDNotIn applies the NotIn predicate on the "problem_set_id" field.
func ProblemSetIDNotIn(vs ...int64) predicate.Competitor_List {
	return predicate.Competitor_List(sql.FieldNotIn(FieldProblemSetID, vs...))
}

// TotalScoreEQ applies the EQ predicate on the "total_score" field.
func TotalScoreEQ(v int) predicate.Competitor_List {
	return predicate.Competitor_List(sql.FieldEQ(FieldTotalScore, v))
}

// TotalScoreNEQ applies the NEQ predicate on the "total_score" field.
func TotalScoreNEQ(v int) predicate.Competitor_List {
	return predicate.Competitor_List(sql.FieldNEQ(FieldTotalScore, v))
}

// TotalScoreIn applies the In predicate on the "total_score" field.
func TotalScoreIn(vs ...int) predicate.Competitor_List {
	return predicate.Competitor_List(sql.FieldIn(FieldTotalScore, vs...))
}

// TotalScoreNotIn applies the NotIn predicate on the "total_score" field.
func TotalScoreNotIn(vs ...int) predicate.Competitor_List {
	return predicate.Competitor_List(sql.FieldNotIn(FieldTotalScore, vs...))
}

// TotalScoreGT applies the GT predicate on the "total_score" field.
func TotalScoreGT(v int) predicate.Competitor_List {
	return predicate.Competitor_List(sql.FieldGT(FieldTotalScore, v))
}

// TotalScoreGTE applies the GTE predicate on the "total_score" field.
func TotalScoreGTE(v int) predicate.Competitor_List {
	return predicate.Competitor_List(sql.FieldGTE(FieldTotalScore, v))
}

// TotalScoreLT applies the LT predicate on the "total_score" field.
func TotalScoreLT(v int) predicate.Competitor_List {
	return predicate.Competitor_List(sql.FieldLT(FieldTotalScore, v))
}

// TotalScoreLTE applies the LTE predicate on the "total_score" field.
func TotalScoreLTE(v int) predicate.Competitor_List {
	return predicate.Competitor_List(sql.FieldLTE(FieldTotalScore, v))
}

// TotalScoreIsNil applies the IsNil predicate on the "total_score" field.
func TotalScoreIsNil() predicate.Competitor_List {
	return predicate.Competitor_List(sql.FieldIsNull(FieldTotalScore))
}

// TotalScoreNotNil applies the NotNil predicate on the "total_score" field.
func TotalScoreNotNil() predicate.Competitor_List {
	return predicate.Competitor_List(sql.FieldNotNull(FieldTotalScore))
}

// HasUser applies the HasEdge predicate on the "user" edge.
func HasUser() predicate.Competitor_List {
	return predicate.Competitor_List(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, UserTable, UserColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasUserWith applies the HasEdge predicate on the "user" edge with a given conditions (other predicates).
func HasUserWith(preds ...predicate.User) predicate.Competitor_List {
	return predicate.Competitor_List(func(s *sql.Selector) {
		step := newUserStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasProblemSet applies the HasEdge predicate on the "problem_set" edge.
func HasProblemSet() predicate.Competitor_List {
	return predicate.Competitor_List(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, ProblemSetTable, ProblemSetColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasProblemSetWith applies the HasEdge predicate on the "problem_set" edge with a given conditions (other predicates).
func HasProblemSetWith(preds ...predicate.ProblemSet) predicate.Competitor_List {
	return predicate.Competitor_List(func(s *sql.Selector) {
		step := newProblemSetStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.Competitor_List) predicate.Competitor_List {
	return predicate.Competitor_List(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.Competitor_List) predicate.Competitor_List {
	return predicate.Competitor_List(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.Competitor_List) predicate.Competitor_List {
	return predicate.Competitor_List(sql.NotPredicates(p))
}
