// Code generated by ent, DO NOT EDIT.

package problem

import (
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

const (
	// Label holds the string label denoting the problem type in the database.
	Label = "problem"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldCreatorID holds the string denoting the creator_id field in the database.
	FieldCreatorID = "creator_id"
	// FieldTitle holds the string denoting the title field in the database.
	FieldTitle = "title"
	// FieldDescription holds the string denoting the description field in the database.
	FieldDescription = "description"
	// FieldProblemType holds the string denoting the problem_type field in the database.
	FieldProblemType = "problem_type"
	// FieldTimeLimit holds the string denoting the time_limit field in the database.
	FieldTimeLimit = "time_limit"
	// FieldMemoryLimit holds the string denoting the memory_limit field in the database.
	FieldMemoryLimit = "memory_limit"
	// FieldUseStatus holds the string denoting the use_status field in the database.
	FieldUseStatus = "use_status"
	// EdgeCreator holds the string denoting the creator edge name in mutations.
	EdgeCreator = "creator"
	// EdgeTestCases holds the string denoting the test_cases edge name in mutations.
	EdgeTestCases = "test_cases"
	// EdgeJudgeRecords holds the string denoting the judge_records edge name in mutations.
	EdgeJudgeRecords = "judge_records"
	// EdgeSubmissions holds the string denoting the submissions edge name in mutations.
	EdgeSubmissions = "submissions"
	// EdgeProblemSetProblems holds the string denoting the problem_set_problems edge name in mutations.
	EdgeProblemSetProblems = "problem_set_problems"
	// Table holds the table name of the problem in the database.
	Table = "Problems"
	// CreatorTable is the table that holds the creator relation/edge.
	CreatorTable = "Problems"
	// CreatorInverseTable is the table name for the User entity.
	// It exists in this package in order to avoid circular dependency with the "user" package.
	CreatorInverseTable = "Users"
	// CreatorColumn is the table column denoting the creator relation/edge.
	CreatorColumn = "creator_id"
	// TestCasesTable is the table that holds the test_cases relation/edge.
	TestCasesTable = "TestCases"
	// TestCasesInverseTable is the table name for the TestCase entity.
	// It exists in this package in order to avoid circular dependency with the "testcase" package.
	TestCasesInverseTable = "TestCases"
	// TestCasesColumn is the table column denoting the test_cases relation/edge.
	TestCasesColumn = "problem_id"
	// JudgeRecordsTable is the table that holds the judge_records relation/edge.
	JudgeRecordsTable = "JudgeRecords"
	// JudgeRecordsInverseTable is the table name for the JudgeRecord entity.
	// It exists in this package in order to avoid circular dependency with the "judgerecord" package.
	JudgeRecordsInverseTable = "JudgeRecords"
	// JudgeRecordsColumn is the table column denoting the judge_records relation/edge.
	JudgeRecordsColumn = "problem_id"
	// SubmissionsTable is the table that holds the submissions relation/edge.
	SubmissionsTable = "SubmissionRecords"
	// SubmissionsInverseTable is the table name for the SubmissionRecord entity.
	// It exists in this package in order to avoid circular dependency with the "submissionrecord" package.
	SubmissionsInverseTable = "SubmissionRecords"
	// SubmissionsColumn is the table column denoting the submissions relation/edge.
	SubmissionsColumn = "problem_id"
	// ProblemSetProblemsTable is the table that holds the problem_set_problems relation/edge.
	ProblemSetProblemsTable = "ProblemSet_Problems"
	// ProblemSetProblemsInverseTable is the table name for the ProblemSet_Problem entity.
	// It exists in this package in order to avoid circular dependency with the "problemset_problem" package.
	ProblemSetProblemsInverseTable = "ProblemSet_Problems"
	// ProblemSetProblemsColumn is the table column denoting the problem_set_problems relation/edge.
	ProblemSetProblemsColumn = "problem_id"
)

// Columns holds all SQL columns for problem fields.
var Columns = []string{
	FieldID,
	FieldCreatorID,
	FieldTitle,
	FieldDescription,
	FieldProblemType,
	FieldTimeLimit,
	FieldMemoryLimit,
	FieldUseStatus,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// CreatorIDValidator is a validator for the "creator_id" field. It is called by the builders before save.
	CreatorIDValidator func(int64) error
	// TitleValidator is a validator for the "title" field. It is called by the builders before save.
	TitleValidator func(string) error
	// DescriptionValidator is a validator for the "description" field. It is called by the builders before save.
	DescriptionValidator func(string) error
	// TimeLimitValidator is a validator for the "time_limit" field. It is called by the builders before save.
	TimeLimitValidator func(int) error
	// MemoryLimitValidator is a validator for the "memory_limit" field. It is called by the builders before save.
	MemoryLimitValidator func(int) error
	// IDValidator is a validator for the "id" field. It is called by the builders before save.
	IDValidator func(int64) error
)

// ProblemType defines the type for the "problem_type" enum field.
type ProblemType string

// ProblemTypeOJ is the default value of the ProblemType enum.
const DefaultProblemType = ProblemTypeOJ

// ProblemType values.
const (
	ProblemTypeOJ    ProblemType = "OJ"
	ProblemTypeOther ProblemType = "other"
)

func (pt ProblemType) String() string {
	return string(pt)
}

// ProblemTypeValidator is a validator for the "problem_type" field enum values. It is called by the builders before save.
func ProblemTypeValidator(pt ProblemType) error {
	switch pt {
	case ProblemTypeOJ, ProblemTypeOther:
		return nil
	default:
		return fmt.Errorf("problem: invalid enum value for problem_type field: %q", pt)
	}
}

// UseStatus defines the type for the "use_status" enum field.
type UseStatus string

// UseStatusUnavailable is the default value of the UseStatus enum.
const DefaultUseStatus = UseStatusUnavailable

// UseStatus values.
const (
	UseStatusUnavailable UseStatus = "unavailable"
	UseStatusAvailable   UseStatus = "available"
	UseStatusUsing       UseStatus = "using"
)

func (us UseStatus) String() string {
	return string(us)
}

// UseStatusValidator is a validator for the "use_status" field enum values. It is called by the builders before save.
func UseStatusValidator(us UseStatus) error {
	switch us {
	case UseStatusUnavailable, UseStatusAvailable, UseStatusUsing:
		return nil
	default:
		return fmt.Errorf("problem: invalid enum value for use_status field: %q", us)
	}
}

// OrderOption defines the ordering options for the Problem queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByCreatorID orders the results by the creator_id field.
func ByCreatorID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatorID, opts...).ToFunc()
}

// ByTitle orders the results by the title field.
func ByTitle(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldTitle, opts...).ToFunc()
}

// ByDescription orders the results by the description field.
func ByDescription(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDescription, opts...).ToFunc()
}

// ByProblemType orders the results by the problem_type field.
func ByProblemType(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldProblemType, opts...).ToFunc()
}

// ByTimeLimit orders the results by the time_limit field.
func ByTimeLimit(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldTimeLimit, opts...).ToFunc()
}

// ByMemoryLimit orders the results by the memory_limit field.
func ByMemoryLimit(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldMemoryLimit, opts...).ToFunc()
}

// ByUseStatus orders the results by the use_status field.
func ByUseStatus(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUseStatus, opts...).ToFunc()
}

// ByCreatorField orders the results by creator field.
func ByCreatorField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newCreatorStep(), sql.OrderByField(field, opts...))
	}
}

// ByTestCasesCount orders the results by test_cases count.
func ByTestCasesCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newTestCasesStep(), opts...)
	}
}

// ByTestCases orders the results by test_cases terms.
func ByTestCases(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newTestCasesStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}

// ByJudgeRecordsCount orders the results by judge_records count.
func ByJudgeRecordsCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newJudgeRecordsStep(), opts...)
	}
}

// ByJudgeRecords orders the results by judge_records terms.
func ByJudgeRecords(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newJudgeRecordsStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}

// BySubmissionsCount orders the results by submissions count.
func BySubmissionsCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newSubmissionsStep(), opts...)
	}
}

// BySubmissions orders the results by submissions terms.
func BySubmissions(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newSubmissionsStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}

// ByProblemSetProblemsCount orders the results by problem_set_problems count.
func ByProblemSetProblemsCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newProblemSetProblemsStep(), opts...)
	}
}

// ByProblemSetProblems orders the results by problem_set_problems terms.
func ByProblemSetProblems(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newProblemSetProblemsStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}
func newCreatorStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(CreatorInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, CreatorTable, CreatorColumn),
	)
}
func newTestCasesStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(TestCasesInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2M, false, TestCasesTable, TestCasesColumn),
	)
}
func newJudgeRecordsStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(JudgeRecordsInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2M, false, JudgeRecordsTable, JudgeRecordsColumn),
	)
}
func newSubmissionsStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(SubmissionsInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2M, false, SubmissionsTable, SubmissionsColumn),
	)
}
func newProblemSetProblemsStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(ProblemSetProblemsInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2M, false, ProblemSetProblemsTable, ProblemSetProblemsColumn),
	)
}
