// Code generated by ent, DO NOT EDIT.

package problem

import (
	"cascade-oj/ent/predicate"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

// ID filters vertices based on their ID field.
func ID(id int) predicate.Problem {
	return predicate.Problem(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.Problem {
	return predicate.Problem(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.Problem {
	return predicate.Problem(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.Problem {
	return predicate.Problem(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.Problem {
	return predicate.Problem(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.Problem {
	return predicate.Problem(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.Problem {
	return predicate.Problem(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.Problem {
	return predicate.Problem(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.Problem {
	return predicate.Problem(sql.FieldLTE(FieldID, id))
}

// CreatorID applies equality check predicate on the "creator_id" field. It's identical to CreatorIDEQ.
func CreatorID(v int) predicate.Problem {
	return predicate.Problem(sql.FieldEQ(FieldCreatorID, v))
}

// Title applies equality check predicate on the "title" field. It's identical to TitleEQ.
func Title(v string) predicate.Problem {
	return predicate.Problem(sql.FieldEQ(FieldTitle, v))
}

// Description applies equality check predicate on the "description" field. It's identical to DescriptionEQ.
func Description(v string) predicate.Problem {
	return predicate.Problem(sql.FieldEQ(FieldDescription, v))
}

// TimeLimit applies equality check predicate on the "time_limit" field. It's identical to TimeLimitEQ.
func TimeLimit(v int) predicate.Problem {
	return predicate.Problem(sql.FieldEQ(FieldTimeLimit, v))
}

// MemoryLimit applies equality check predicate on the "memory_limit" field. It's identical to MemoryLimitEQ.
func MemoryLimit(v int) predicate.Problem {
	return predicate.Problem(sql.FieldEQ(FieldMemoryLimit, v))
}

// CreatorIDEQ applies the EQ predicate on the "creator_id" field.
func CreatorIDEQ(v int) predicate.Problem {
	return predicate.Problem(sql.FieldEQ(FieldCreatorID, v))
}

// CreatorIDNEQ applies the NEQ predicate on the "creator_id" field.
func CreatorIDNEQ(v int) predicate.Problem {
	return predicate.Problem(sql.FieldNEQ(FieldCreatorID, v))
}

// CreatorIDIn applies the In predicate on the "creator_id" field.
func CreatorIDIn(vs ...int) predicate.Problem {
	return predicate.Problem(sql.FieldIn(FieldCreatorID, vs...))
}

// CreatorIDNotIn applies the NotIn predicate on the "creator_id" field.
func CreatorIDNotIn(vs ...int) predicate.Problem {
	return predicate.Problem(sql.FieldNotIn(FieldCreatorID, vs...))
}

// TitleEQ applies the EQ predicate on the "title" field.
func TitleEQ(v string) predicate.Problem {
	return predicate.Problem(sql.FieldEQ(FieldTitle, v))
}

// TitleNEQ applies the NEQ predicate on the "title" field.
func TitleNEQ(v string) predicate.Problem {
	return predicate.Problem(sql.FieldNEQ(FieldTitle, v))
}

// TitleIn applies the In predicate on the "title" field.
func TitleIn(vs ...string) predicate.Problem {
	return predicate.Problem(sql.FieldIn(FieldTitle, vs...))
}

// TitleNotIn applies the NotIn predicate on the "title" field.
func TitleNotIn(vs ...string) predicate.Problem {
	return predicate.Problem(sql.FieldNotIn(FieldTitle, vs...))
}

// TitleGT applies the GT predicate on the "title" field.
func TitleGT(v string) predicate.Problem {
	return predicate.Problem(sql.FieldGT(FieldTitle, v))
}

// TitleGTE applies the GTE predicate on the "title" field.
func TitleGTE(v string) predicate.Problem {
	return predicate.Problem(sql.FieldGTE(FieldTitle, v))
}

// TitleLT applies the LT predicate on the "title" field.
func TitleLT(v string) predicate.Problem {
	return predicate.Problem(sql.FieldLT(FieldTitle, v))
}

// TitleLTE applies the LTE predicate on the "title" field.
func TitleLTE(v string) predicate.Problem {
	return predicate.Problem(sql.FieldLTE(FieldTitle, v))
}

// TitleContains applies the Contains predicate on the "title" field.
func TitleContains(v string) predicate.Problem {
	return predicate.Problem(sql.FieldContains(FieldTitle, v))
}

// TitleHasPrefix applies the HasPrefix predicate on the "title" field.
func TitleHasPrefix(v string) predicate.Problem {
	return predicate.Problem(sql.FieldHasPrefix(FieldTitle, v))
}

// TitleHasSuffix applies the HasSuffix predicate on the "title" field.
func TitleHasSuffix(v string) predicate.Problem {
	return predicate.Problem(sql.FieldHasSuffix(FieldTitle, v))
}

// TitleEqualFold applies the EqualFold predicate on the "title" field.
func TitleEqualFold(v string) predicate.Problem {
	return predicate.Problem(sql.FieldEqualFold(FieldTitle, v))
}

// TitleContainsFold applies the ContainsFold predicate on the "title" field.
func TitleContainsFold(v string) predicate.Problem {
	return predicate.Problem(sql.FieldContainsFold(FieldTitle, v))
}

// DescriptionEQ applies the EQ predicate on the "description" field.
func DescriptionEQ(v string) predicate.Problem {
	return predicate.Problem(sql.FieldEQ(FieldDescription, v))
}

// DescriptionNEQ applies the NEQ predicate on the "description" field.
func DescriptionNEQ(v string) predicate.Problem {
	return predicate.Problem(sql.FieldNEQ(FieldDescription, v))
}

// DescriptionIn applies the In predicate on the "description" field.
func DescriptionIn(vs ...string) predicate.Problem {
	return predicate.Problem(sql.FieldIn(FieldDescription, vs...))
}

// DescriptionNotIn applies the NotIn predicate on the "description" field.
func DescriptionNotIn(vs ...string) predicate.Problem {
	return predicate.Problem(sql.FieldNotIn(FieldDescription, vs...))
}

// DescriptionGT applies the GT predicate on the "description" field.
func DescriptionGT(v string) predicate.Problem {
	return predicate.Problem(sql.FieldGT(FieldDescription, v))
}

// DescriptionGTE applies the GTE predicate on the "description" field.
func DescriptionGTE(v string) predicate.Problem {
	return predicate.Problem(sql.FieldGTE(FieldDescription, v))
}

// DescriptionLT applies the LT predicate on the "description" field.
func DescriptionLT(v string) predicate.Problem {
	return predicate.Problem(sql.FieldLT(FieldDescription, v))
}

// DescriptionLTE applies the LTE predicate on the "description" field.
func DescriptionLTE(v string) predicate.Problem {
	return predicate.Problem(sql.FieldLTE(FieldDescription, v))
}

// DescriptionContains applies the Contains predicate on the "description" field.
func DescriptionContains(v string) predicate.Problem {
	return predicate.Problem(sql.FieldContains(FieldDescription, v))
}

// DescriptionHasPrefix applies the HasPrefix predicate on the "description" field.
func DescriptionHasPrefix(v string) predicate.Problem {
	return predicate.Problem(sql.FieldHasPrefix(FieldDescription, v))
}

// DescriptionHasSuffix applies the HasSuffix predicate on the "description" field.
func DescriptionHasSuffix(v string) predicate.Problem {
	return predicate.Problem(sql.FieldHasSuffix(FieldDescription, v))
}

// DescriptionEqualFold applies the EqualFold predicate on the "description" field.
func DescriptionEqualFold(v string) predicate.Problem {
	return predicate.Problem(sql.FieldEqualFold(FieldDescription, v))
}

// DescriptionContainsFold applies the ContainsFold predicate on the "description" field.
func DescriptionContainsFold(v string) predicate.Problem {
	return predicate.Problem(sql.FieldContainsFold(FieldDescription, v))
}

// ProblemTypeEQ applies the EQ predicate on the "problem_type" field.
func ProblemTypeEQ(v ProblemType) predicate.Problem {
	return predicate.Problem(sql.FieldEQ(FieldProblemType, v))
}

// ProblemTypeNEQ applies the NEQ predicate on the "problem_type" field.
func ProblemTypeNEQ(v ProblemType) predicate.Problem {
	return predicate.Problem(sql.FieldNEQ(FieldProblemType, v))
}

// ProblemTypeIn applies the In predicate on the "problem_type" field.
func ProblemTypeIn(vs ...ProblemType) predicate.Problem {
	return predicate.Problem(sql.FieldIn(FieldProblemType, vs...))
}

// ProblemTypeNotIn applies the NotIn predicate on the "problem_type" field.
func ProblemTypeNotIn(vs ...ProblemType) predicate.Problem {
	return predicate.Problem(sql.FieldNotIn(FieldProblemType, vs...))
}

// TimeLimitEQ applies the EQ predicate on the "time_limit" field.
func TimeLimitEQ(v int) predicate.Problem {
	return predicate.Problem(sql.FieldEQ(FieldTimeLimit, v))
}

// TimeLimitNEQ applies the NEQ predicate on the "time_limit" field.
func TimeLimitNEQ(v int) predicate.Problem {
	return predicate.Problem(sql.FieldNEQ(FieldTimeLimit, v))
}

// TimeLimitIn applies the In predicate on the "time_limit" field.
func TimeLimitIn(vs ...int) predicate.Problem {
	return predicate.Problem(sql.FieldIn(FieldTimeLimit, vs...))
}

// TimeLimitNotIn applies the NotIn predicate on the "time_limit" field.
func TimeLimitNotIn(vs ...int) predicate.Problem {
	return predicate.Problem(sql.FieldNotIn(FieldTimeLimit, vs...))
}

// TimeLimitGT applies the GT predicate on the "time_limit" field.
func TimeLimitGT(v int) predicate.Problem {
	return predicate.Problem(sql.FieldGT(FieldTimeLimit, v))
}

// TimeLimitGTE applies the GTE predicate on the "time_limit" field.
func TimeLimitGTE(v int) predicate.Problem {
	return predicate.Problem(sql.FieldGTE(FieldTimeLimit, v))
}

// TimeLimitLT applies the LT predicate on the "time_limit" field.
func TimeLimitLT(v int) predicate.Problem {
	return predicate.Problem(sql.FieldLT(FieldTimeLimit, v))
}

// TimeLimitLTE applies the LTE predicate on the "time_limit" field.
func TimeLimitLTE(v int) predicate.Problem {
	return predicate.Problem(sql.FieldLTE(FieldTimeLimit, v))
}

// MemoryLimitEQ applies the EQ predicate on the "memory_limit" field.
func MemoryLimitEQ(v int) predicate.Problem {
	return predicate.Problem(sql.FieldEQ(FieldMemoryLimit, v))
}

// MemoryLimitNEQ applies the NEQ predicate on the "memory_limit" field.
func MemoryLimitNEQ(v int) predicate.Problem {
	return predicate.Problem(sql.FieldNEQ(FieldMemoryLimit, v))
}

// MemoryLimitIn applies the In predicate on the "memory_limit" field.
func MemoryLimitIn(vs ...int) predicate.Problem {
	return predicate.Problem(sql.FieldIn(FieldMemoryLimit, vs...))
}

// MemoryLimitNotIn applies the NotIn predicate on the "memory_limit" field.
func MemoryLimitNotIn(vs ...int) predicate.Problem {
	return predicate.Problem(sql.FieldNotIn(FieldMemoryLimit, vs...))
}

// MemoryLimitGT applies the GT predicate on the "memory_limit" field.
func MemoryLimitGT(v int) predicate.Problem {
	return predicate.Problem(sql.FieldGT(FieldMemoryLimit, v))
}

// MemoryLimitGTE applies the GTE predicate on the "memory_limit" field.
func MemoryLimitGTE(v int) predicate.Problem {
	return predicate.Problem(sql.FieldGTE(FieldMemoryLimit, v))
}

// MemoryLimitLT applies the LT predicate on the "memory_limit" field.
func MemoryLimitLT(v int) predicate.Problem {
	return predicate.Problem(sql.FieldLT(FieldMemoryLimit, v))
}

// MemoryLimitLTE applies the LTE predicate on the "memory_limit" field.
func MemoryLimitLTE(v int) predicate.Problem {
	return predicate.Problem(sql.FieldLTE(FieldMemoryLimit, v))
}

// UseStatusEQ applies the EQ predicate on the "use_status" field.
func UseStatusEQ(v UseStatus) predicate.Problem {
	return predicate.Problem(sql.FieldEQ(FieldUseStatus, v))
}

// UseStatusNEQ applies the NEQ predicate on the "use_status" field.
func UseStatusNEQ(v UseStatus) predicate.Problem {
	return predicate.Problem(sql.FieldNEQ(FieldUseStatus, v))
}

// UseStatusIn applies the In predicate on the "use_status" field.
func UseStatusIn(vs ...UseStatus) predicate.Problem {
	return predicate.Problem(sql.FieldIn(FieldUseStatus, vs...))
}

// UseStatusNotIn applies the NotIn predicate on the "use_status" field.
func UseStatusNotIn(vs ...UseStatus) predicate.Problem {
	return predicate.Problem(sql.FieldNotIn(FieldUseStatus, vs...))
}

// HasCreator applies the HasEdge predicate on the "creator" edge.
func HasCreator() predicate.Problem {
	return predicate.Problem(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, CreatorTable, CreatorColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasCreatorWith applies the HasEdge predicate on the "creator" edge with a given conditions (other predicates).
func HasCreatorWith(preds ...predicate.User) predicate.Problem {
	return predicate.Problem(func(s *sql.Selector) {
		step := newCreatorStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasTestCases applies the HasEdge predicate on the "test_cases" edge.
func HasTestCases() predicate.Problem {
	return predicate.Problem(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, TestCasesTable, TestCasesColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasTestCasesWith applies the HasEdge predicate on the "test_cases" edge with a given conditions (other predicates).
func HasTestCasesWith(preds ...predicate.TestCase) predicate.Problem {
	return predicate.Problem(func(s *sql.Selector) {
		step := newTestCasesStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasJudgeRecords applies the HasEdge predicate on the "judge_records" edge.
func HasJudgeRecords() predicate.Problem {
	return predicate.Problem(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, JudgeRecordsTable, JudgeRecordsColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasJudgeRecordsWith applies the HasEdge predicate on the "judge_records" edge with a given conditions (other predicates).
func HasJudgeRecordsWith(preds ...predicate.JudgeRecord) predicate.Problem {
	return predicate.Problem(func(s *sql.Selector) {
		step := newJudgeRecordsStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasSubmissions applies the HasEdge predicate on the "submissions" edge.
func HasSubmissions() predicate.Problem {
	return predicate.Problem(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, SubmissionsTable, SubmissionsColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasSubmissionsWith applies the HasEdge predicate on the "submissions" edge with a given conditions (other predicates).
func HasSubmissionsWith(preds ...predicate.SubmissionRecord) predicate.Problem {
	return predicate.Problem(func(s *sql.Selector) {
		step := newSubmissionsStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasProblemSetProblems applies the HasEdge predicate on the "problem_set_problems" edge.
func HasProblemSetProblems() predicate.Problem {
	return predicate.Problem(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, ProblemSetProblemsTable, ProblemSetProblemsColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasProblemSetProblemsWith applies the HasEdge predicate on the "problem_set_problems" edge with a given conditions (other predicates).
func HasProblemSetProblemsWith(preds ...predicate.ProblemSetProblem) predicate.Problem {
	return predicate.Problem(func(s *sql.Selector) {
		step := newProblemSetProblemsStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.Problem) predicate.Problem {
	return predicate.Problem(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.Problem) predicate.Problem {
	return predicate.Problem(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.Problem) predicate.Problem {
	return predicate.Problem(sql.NotPredicates(p))
}
