// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"cascade-oj/app/services/admin/internal/biz"
	"cascade-oj/app/services/admin/internal/conf"
	"cascade-oj/app/services/admin/internal/data"
	"cascade-oj/app/services/admin/internal/server"
	"cascade-oj/app/services/admin/internal/service"
	"github.com/go-kratos/kratos/v2"
	"github.com/go-kratos/kratos/v2/log"
	"net/http"
)

// Injectors from wire.go:

// wireApp init kratos application.
func wireApp(confServer *conf.Server, confData *conf.Data, logger log.Logger, handler http.Handler) (*kratos.App, func(), error) {
	dataData, cleanup, err := data.NewData(confData, logger)
	if err != nil {
		return nil, nil, err
	}
	announcementRepo := data.NewAnnouncementRepo(dataData, logger)
	announcementUseCase := biz.NewAnnouncementUseCase(announcementRepo, logger)
	contestRepo := data.NewContestRepo(dataData, logger)
	contestUsecase := biz.NewContestUsecase(contestRepo, logger)
	logRepo := data.NewLogRepo(dataData, logger)
	logUseCase := biz.NewLogUseCase(logRepo, logger)
	problemRepo := data.NewProblemRepo(dataData, logger)
	problemUsecase := biz.NewProblemUsecase(problemRepo, logger)
	submissionRepo := data.NewSubmissionRepo(dataData, logger)
	submissionUseCase := biz.NewSubmissionUseCase(submissionRepo, logger)
	userRepo := data.NewUserRepo(dataData, logger)
	userUsecase := biz.NewUserUsecase(userRepo, logger)
	adminService := service.NewAdminService(announcementUseCase, contestUsecase, logUseCase, problemUsecase, submissionUseCase, userUsecase, logger)
	grpcServer := server.NewGRPCServer(confServer, adminService, logger)
	httpServer := server.NewHTTPServer(confServer, adminService, handler, logger)
	rabbitmqServer := server.NewMQServer(confServer, adminService, logger)
	app := newApp(logger, grpcServer, httpServer, rabbitmqServer)
	return app, func() {
		cleanup()
	}, nil
}
