services:
  cascade_nginx:
    build:
      context: ./
      dockerfile: ./Dockerfile
    image: cascade-oj/nginx:latest
    restart: always
    ports:
      - "80:80"
      - "443:443"
      - "10086:10086"
      - "11086:11086"
    volumes:
      - ./nginx/logs:/var/log/nginx
    container_name: cascade_oj_nginx
    deploy:
      resources:
        limits:
          cpus: '0.2'
          memory: 128M
        reservations:
          cpus: '0.1'
          memory: 32M
    networks:
      frontend-network:
        aliases:
          - nginx
      backend-network:
        aliases:
          - frontend-nginx

networks:
  frontend-network:
    driver: bridge

  # 连接后端服务的网络
  backend-network:
    external: true
    name: cascade-oj-backend-network
