server:
  http:
    addr: 0.0.0.0:8080
    timeout: 1s
  grpc:
    addr: 0.0.0.0:9000
    timeout: 1s
  jwt_secret: cascade
client:
  http:
    addr: localhost:8080
    timeout: 1s
  grpc:
    addr: localhost:9000
    timeout: 1s
data:
  mq: amqp://cascade:123456@cascade_rabbitmq:5672
  ipv4_prefix: 0
  port: 8080
  api_key: cascade
  endpoint_preset: "gateway:8080"