// Code generated by protoc-gen-go-http. DO NOT EDIT.
// versions:
// - protoc-gen-go-http v2.9.2
// - protoc             (unknown)
// source: aiops/v1/aiops.proto

package v1

import (
	context "context"
	http "github.com/go-kratos/kratos/v2/transport/http"
	binding "github.com/go-kratos/kratos/v2/transport/http/binding"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the kratos package it is being compiled against.
var _ = new(context.Context)
var _ = binding.EncodeURL

const _ = http.SupportPackageIsVersion1

const OperationAIOpsAckReport = "/api.cascade.aiops.v1.AIOps/AckReport"
const OperationAIOpsGetMetricsSummary = "/api.cascade.aiops.v1.AIOps/GetMetricsSummary"
const OperationAIOpsGetReport = "/api.cascade.aiops.v1.AIOps/GetReport"
const OperationAIOpsListReports = "/api.cascade.aiops.v1.AIOps/ListReports"
const OperationAIOpsTriggerAnalysis = "/api.cascade.aiops.v1.AIOps/TriggerAnalysis"

type AIOpsHTTPServer interface {
	// AckReport AckReport acknowledges a report.
	AckReport(context.Context, *AckReportRequest) (*AckReportReply, error)
	// GetMetricsSummary GetMetricsSummary returns current metrics summary for debugging.
	GetMetricsSummary(context.Context, *GetMetricsSummaryRequest) (*GetMetricsSummaryReply, error)
	// GetReport GetReport retrieves a historical analysis report by ID or time range.
	GetReport(context.Context, *GetReportRequest) (*GetReportReply, error)
	// ListReports ListReports lists historical analysis reports.
	ListReports(context.Context, *ListReportsRequest) (*ListReportsReply, error)
	// TriggerAnalysis TriggerAnalysis manually triggers an alert analysis and noise reduction run.
	TriggerAnalysis(context.Context, *TriggerAnalysisRequest) (*TriggerAnalysisReply, error)
}

func RegisterAIOpsHTTPServer(s *http.Server, srv AIOpsHTTPServer) {
	r := s.Route("/")
	r.POST("/aiops/v1/analysis/trigger", _AIOps_TriggerAnalysis0_HTTP_Handler(srv))
	r.GET("/aiops/v1/reports/{report_id}", _AIOps_GetReport0_HTTP_Handler(srv))
	r.GET("/aiops/v1/reports", _AIOps_ListReports0_HTTP_Handler(srv))
	r.GET("/aiops/v1/metrics", _AIOps_GetMetricsSummary0_HTTP_Handler(srv))
	r.POST("/aiops/v1/reports/{report_id}/ack", _AIOps_AckReport0_HTTP_Handler(srv))
}

func _AIOps_TriggerAnalysis0_HTTP_Handler(srv AIOpsHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in TriggerAnalysisRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationAIOpsTriggerAnalysis)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.TriggerAnalysis(ctx, req.(*TriggerAnalysisRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*TriggerAnalysisReply)
		return ctx.Result(200, reply)
	}
}

func _AIOps_GetReport0_HTTP_Handler(srv AIOpsHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in GetReportRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationAIOpsGetReport)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.GetReport(ctx, req.(*GetReportRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*GetReportReply)
		return ctx.Result(200, reply)
	}
}

func _AIOps_ListReports0_HTTP_Handler(srv AIOpsHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in ListReportsRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationAIOpsListReports)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.ListReports(ctx, req.(*ListReportsRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*ListReportsReply)
		return ctx.Result(200, reply)
	}
}

func _AIOps_GetMetricsSummary0_HTTP_Handler(srv AIOpsHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in GetMetricsSummaryRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationAIOpsGetMetricsSummary)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.GetMetricsSummary(ctx, req.(*GetMetricsSummaryRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*GetMetricsSummaryReply)
		return ctx.Result(200, reply)
	}
}

func _AIOps_AckReport0_HTTP_Handler(srv AIOpsHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in AckReportRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationAIOpsAckReport)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.AckReport(ctx, req.(*AckReportRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*AckReportReply)
		return ctx.Result(200, reply)
	}
}

type AIOpsHTTPClient interface {
	// AckReport AckReport acknowledges a report.
	AckReport(ctx context.Context, req *AckReportRequest, opts ...http.CallOption) (rsp *AckReportReply, err error)
	// GetMetricsSummary GetMetricsSummary returns current metrics summary for debugging.
	GetMetricsSummary(ctx context.Context, req *GetMetricsSummaryRequest, opts ...http.CallOption) (rsp *GetMetricsSummaryReply, err error)
	// GetReport GetReport retrieves a historical analysis report by ID or time range.
	GetReport(ctx context.Context, req *GetReportRequest, opts ...http.CallOption) (rsp *GetReportReply, err error)
	// ListReports ListReports lists historical analysis reports.
	ListReports(ctx context.Context, req *ListReportsRequest, opts ...http.CallOption) (rsp *ListReportsReply, err error)
	// TriggerAnalysis TriggerAnalysis manually triggers an alert analysis and noise reduction run.
	TriggerAnalysis(ctx context.Context, req *TriggerAnalysisRequest, opts ...http.CallOption) (rsp *TriggerAnalysisReply, err error)
}

type AIOpsHTTPClientImpl struct {
	cc *http.Client
}

func NewAIOpsHTTPClient(client *http.Client) AIOpsHTTPClient {
	return &AIOpsHTTPClientImpl{client}
}

// AckReport AckReport acknowledges a report.
func (c *AIOpsHTTPClientImpl) AckReport(ctx context.Context, in *AckReportRequest, opts ...http.CallOption) (*AckReportReply, error) {
	var out AckReportReply
	pattern := "/aiops/v1/reports/{report_id}/ack"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationAIOpsAckReport))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// GetMetricsSummary GetMetricsSummary returns current metrics summary for debugging.
func (c *AIOpsHTTPClientImpl) GetMetricsSummary(ctx context.Context, in *GetMetricsSummaryRequest, opts ...http.CallOption) (*GetMetricsSummaryReply, error) {
	var out GetMetricsSummaryReply
	pattern := "/aiops/v1/metrics"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationAIOpsGetMetricsSummary))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// GetReport GetReport retrieves a historical analysis report by ID or time range.
func (c *AIOpsHTTPClientImpl) GetReport(ctx context.Context, in *GetReportRequest, opts ...http.CallOption) (*GetReportReply, error) {
	var out GetReportReply
	pattern := "/aiops/v1/reports/{report_id}"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationAIOpsGetReport))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// ListReports ListReports lists historical analysis reports.
func (c *AIOpsHTTPClientImpl) ListReports(ctx context.Context, in *ListReportsRequest, opts ...http.CallOption) (*ListReportsReply, error) {
	var out ListReportsReply
	pattern := "/aiops/v1/reports"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationAIOpsListReports))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// TriggerAnalysis TriggerAnalysis manually triggers an alert analysis and noise reduction run.
func (c *AIOpsHTTPClientImpl) TriggerAnalysis(ctx context.Context, in *TriggerAnalysisRequest, opts ...http.CallOption) (*TriggerAnalysisReply, error) {
	var out TriggerAnalysisReply
	pattern := "/aiops/v1/analysis/trigger"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationAIOpsTriggerAnalysis))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}
