// Code generated by protoc-gen-validate. DO NOT EDIT.
// source: aiops/v1/aiops.proto

package v1

import (
	"bytes"
	"errors"
	"fmt"
	"net"
	"net/mail"
	"net/url"
	"regexp"
	"sort"
	"strings"
	"time"
	"unicode/utf8"

	"google.golang.org/protobuf/types/known/anypb"
)

// ensure the imports are used
var (
	_ = bytes.MinRead
	_ = errors.New("")
	_ = fmt.Print
	_ = utf8.UTFMax
	_ = (*regexp.Regexp)(nil)
	_ = (*strings.Reader)(nil)
	_ = net.IPv4len
	_ = time.Duration(0)
	_ = (*url.URL)(nil)
	_ = (*mail.Address)(nil)
	_ = anypb.Any{}
	_ = sort.Sort
)

// Validate checks the field values on TriggerAnalysisRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *TriggerAnalysisRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on TriggerAnalysisRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// TriggerAnalysisRequestMultiError, or nil if none found.
func (m *TriggerAnalysisRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *TriggerAnalysisRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for TimeRangeMinutes

	if len(errors) > 0 {
		return TriggerAnalysisRequestMultiError(errors)
	}

	return nil
}

// TriggerAnalysisRequestMultiError is an error wrapping multiple validation
// errors returned by TriggerAnalysisRequest.ValidateAll() if the designated
// constraints aren't met.
type TriggerAnalysisRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m TriggerAnalysisRequestMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m TriggerAnalysisRequestMultiError) AllErrors() []error { return m }

// TriggerAnalysisRequestValidationError is the validation error returned by
// TriggerAnalysisRequest.Validate if the designated constraints aren't met.
type TriggerAnalysisRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e TriggerAnalysisRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e TriggerAnalysisRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e TriggerAnalysisRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e TriggerAnalysisRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e TriggerAnalysisRequestValidationError) ErrorName() string {
	return "TriggerAnalysisRequestValidationError"
}

// Error satisfies the builtin error interface
func (e TriggerAnalysisRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sTriggerAnalysisRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = TriggerAnalysisRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = TriggerAnalysisRequestValidationError{}

// Validate checks the field values on TriggerAnalysisReply with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *TriggerAnalysisReply) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on TriggerAnalysisReply with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// TriggerAnalysisReplyMultiError, or nil if none found.
func (m *TriggerAnalysisReply) ValidateAll() error {
	return m.validate(true)
}

func (m *TriggerAnalysisReply) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for ReportId

	// no validation rules for Title

	// no validation rules for Summary

	// no validation rules for NoiseCount

	// no validation rules for RealRiskCount

	// no validation rules for FullReportMarkdown

	if all {
		switch v := interface{}(m.GetCreatedAt()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, TriggerAnalysisReplyValidationError{
					field:  "CreatedAt",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, TriggerAnalysisReplyValidationError{
					field:  "CreatedAt",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetCreatedAt()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return TriggerAnalysisReplyValidationError{
				field:  "CreatedAt",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if len(errors) > 0 {
		return TriggerAnalysisReplyMultiError(errors)
	}

	return nil
}

// TriggerAnalysisReplyMultiError is an error wrapping multiple validation
// errors returned by TriggerAnalysisReply.ValidateAll() if the designated
// constraints aren't met.
type TriggerAnalysisReplyMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m TriggerAnalysisReplyMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m TriggerAnalysisReplyMultiError) AllErrors() []error { return m }

// TriggerAnalysisReplyValidationError is the validation error returned by
// TriggerAnalysisReply.Validate if the designated constraints aren't met.
type TriggerAnalysisReplyValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e TriggerAnalysisReplyValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e TriggerAnalysisReplyValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e TriggerAnalysisReplyValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e TriggerAnalysisReplyValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e TriggerAnalysisReplyValidationError) ErrorName() string {
	return "TriggerAnalysisReplyValidationError"
}

// Error satisfies the builtin error interface
func (e TriggerAnalysisReplyValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sTriggerAnalysisReply.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = TriggerAnalysisReplyValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = TriggerAnalysisReplyValidationError{}

// Validate checks the field values on GetReportRequest with the rules defined
// in the proto definition for this message. If any rules are violated, the
// first error encountered is returned, or nil if there are no violations.
func (m *GetReportRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on GetReportRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// GetReportRequestMultiError, or nil if none found.
func (m *GetReportRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *GetReportRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for ReportId

	if len(errors) > 0 {
		return GetReportRequestMultiError(errors)
	}

	return nil
}

// GetReportRequestMultiError is an error wrapping multiple validation errors
// returned by GetReportRequest.ValidateAll() if the designated constraints
// aren't met.
type GetReportRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m GetReportRequestMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m GetReportRequestMultiError) AllErrors() []error { return m }

// GetReportRequestValidationError is the validation error returned by
// GetReportRequest.Validate if the designated constraints aren't met.
type GetReportRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e GetReportRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e GetReportRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e GetReportRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e GetReportRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e GetReportRequestValidationError) ErrorName() string { return "GetReportRequestValidationError" }

// Error satisfies the builtin error interface
func (e GetReportRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sGetReportRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = GetReportRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = GetReportRequestValidationError{}

// Validate checks the field values on GetReportReply with the rules defined in
// the proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *GetReportReply) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on GetReportReply with the rules defined
// in the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in GetReportReplyMultiError,
// or nil if none found.
func (m *GetReportReply) ValidateAll() error {
	return m.validate(true)
}

func (m *GetReportReply) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Id

	// no validation rules for Title

	// no validation rules for Summary

	// no validation rules for RootCausesJson

	// no validation rules for SuggestedActionsJson

	// no validation rules for NoiseCount

	// no validation rules for RealRiskCount

	// no validation rules for Status

	// no validation rules for FullReportMarkdown

	if all {
		switch v := interface{}(m.GetCreatedAt()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, GetReportReplyValidationError{
					field:  "CreatedAt",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, GetReportReplyValidationError{
					field:  "CreatedAt",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetCreatedAt()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return GetReportReplyValidationError{
				field:  "CreatedAt",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if all {
		switch v := interface{}(m.GetAcknowledgedAt()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, GetReportReplyValidationError{
					field:  "AcknowledgedAt",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, GetReportReplyValidationError{
					field:  "AcknowledgedAt",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetAcknowledgedAt()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return GetReportReplyValidationError{
				field:  "AcknowledgedAt",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if len(errors) > 0 {
		return GetReportReplyMultiError(errors)
	}

	return nil
}

// GetReportReplyMultiError is an error wrapping multiple validation errors
// returned by GetReportReply.ValidateAll() if the designated constraints
// aren't met.
type GetReportReplyMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m GetReportReplyMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m GetReportReplyMultiError) AllErrors() []error { return m }

// GetReportReplyValidationError is the validation error returned by
// GetReportReply.Validate if the designated constraints aren't met.
type GetReportReplyValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e GetReportReplyValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e GetReportReplyValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e GetReportReplyValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e GetReportReplyValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e GetReportReplyValidationError) ErrorName() string { return "GetReportReplyValidationError" }

// Error satisfies the builtin error interface
func (e GetReportReplyValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sGetReportReply.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = GetReportReplyValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = GetReportReplyValidationError{}

// Validate checks the field values on ListReportsRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *ListReportsRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on ListReportsRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// ListReportsRequestMultiError, or nil if none found.
func (m *ListReportsRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *ListReportsRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Page

	// no validation rules for PageSize

	// no validation rules for StatusFilter

	if len(errors) > 0 {
		return ListReportsRequestMultiError(errors)
	}

	return nil
}

// ListReportsRequestMultiError is an error wrapping multiple validation errors
// returned by ListReportsRequest.ValidateAll() if the designated constraints
// aren't met.
type ListReportsRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m ListReportsRequestMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m ListReportsRequestMultiError) AllErrors() []error { return m }

// ListReportsRequestValidationError is the validation error returned by
// ListReportsRequest.Validate if the designated constraints aren't met.
type ListReportsRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e ListReportsRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e ListReportsRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e ListReportsRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e ListReportsRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e ListReportsRequestValidationError) ErrorName() string {
	return "ListReportsRequestValidationError"
}

// Error satisfies the builtin error interface
func (e ListReportsRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sListReportsRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = ListReportsRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = ListReportsRequestValidationError{}

// Validate checks the field values on ListReportsReply with the rules defined
// in the proto definition for this message. If any rules are violated, the
// first error encountered is returned, or nil if there are no violations.
func (m *ListReportsReply) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on ListReportsReply with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// ListReportsReplyMultiError, or nil if none found.
func (m *ListReportsReply) ValidateAll() error {
	return m.validate(true)
}

func (m *ListReportsReply) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	for idx, item := range m.GetReports() {
		_, _ = idx, item

		if all {
			switch v := interface{}(item).(type) {
			case interface{ ValidateAll() error }:
				if err := v.ValidateAll(); err != nil {
					errors = append(errors, ListReportsReplyValidationError{
						field:  fmt.Sprintf("Reports[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			case interface{ Validate() error }:
				if err := v.Validate(); err != nil {
					errors = append(errors, ListReportsReplyValidationError{
						field:  fmt.Sprintf("Reports[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			}
		} else if v, ok := interface{}(item).(interface{ Validate() error }); ok {
			if err := v.Validate(); err != nil {
				return ListReportsReplyValidationError{
					field:  fmt.Sprintf("Reports[%v]", idx),
					reason: "embedded message failed validation",
					cause:  err,
				}
			}
		}

	}

	// no validation rules for Total

	if len(errors) > 0 {
		return ListReportsReplyMultiError(errors)
	}

	return nil
}

// ListReportsReplyMultiError is an error wrapping multiple validation errors
// returned by ListReportsReply.ValidateAll() if the designated constraints
// aren't met.
type ListReportsReplyMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m ListReportsReplyMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m ListReportsReplyMultiError) AllErrors() []error { return m }

// ListReportsReplyValidationError is the validation error returned by
// ListReportsReply.Validate if the designated constraints aren't met.
type ListReportsReplyValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e ListReportsReplyValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e ListReportsReplyValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e ListReportsReplyValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e ListReportsReplyValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e ListReportsReplyValidationError) ErrorName() string { return "ListReportsReplyValidationError" }

// Error satisfies the builtin error interface
func (e ListReportsReplyValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sListReportsReply.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = ListReportsReplyValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = ListReportsReplyValidationError{}

// Validate checks the field values on ReportSummary with the rules defined in
// the proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *ReportSummary) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on ReportSummary with the rules defined
// in the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in ReportSummaryMultiError, or
// nil if none found.
func (m *ReportSummary) ValidateAll() error {
	return m.validate(true)
}

func (m *ReportSummary) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Id

	// no validation rules for Title

	// no validation rules for NoiseCount

	// no validation rules for RealRiskCount

	// no validation rules for Status

	if all {
		switch v := interface{}(m.GetCreatedAt()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, ReportSummaryValidationError{
					field:  "CreatedAt",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, ReportSummaryValidationError{
					field:  "CreatedAt",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetCreatedAt()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return ReportSummaryValidationError{
				field:  "CreatedAt",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if len(errors) > 0 {
		return ReportSummaryMultiError(errors)
	}

	return nil
}

// ReportSummaryMultiError is an error wrapping multiple validation errors
// returned by ReportSummary.ValidateAll() if the designated constraints
// aren't met.
type ReportSummaryMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m ReportSummaryMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m ReportSummaryMultiError) AllErrors() []error { return m }

// ReportSummaryValidationError is the validation error returned by
// ReportSummary.Validate if the designated constraints aren't met.
type ReportSummaryValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e ReportSummaryValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e ReportSummaryValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e ReportSummaryValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e ReportSummaryValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e ReportSummaryValidationError) ErrorName() string { return "ReportSummaryValidationError" }

// Error satisfies the builtin error interface
func (e ReportSummaryValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sReportSummary.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = ReportSummaryValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = ReportSummaryValidationError{}

// Validate checks the field values on GetMetricsSummaryRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *GetMetricsSummaryRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on GetMetricsSummaryRequest with the
// rules defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// GetMetricsSummaryRequestMultiError, or nil if none found.
func (m *GetMetricsSummaryRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *GetMetricsSummaryRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if len(errors) > 0 {
		return GetMetricsSummaryRequestMultiError(errors)
	}

	return nil
}

// GetMetricsSummaryRequestMultiError is an error wrapping multiple validation
// errors returned by GetMetricsSummaryRequest.ValidateAll() if the designated
// constraints aren't met.
type GetMetricsSummaryRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m GetMetricsSummaryRequestMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m GetMetricsSummaryRequestMultiError) AllErrors() []error { return m }

// GetMetricsSummaryRequestValidationError is the validation error returned by
// GetMetricsSummaryRequest.Validate if the designated constraints aren't met.
type GetMetricsSummaryRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e GetMetricsSummaryRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e GetMetricsSummaryRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e GetMetricsSummaryRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e GetMetricsSummaryRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e GetMetricsSummaryRequestValidationError) ErrorName() string {
	return "GetMetricsSummaryRequestValidationError"
}

// Error satisfies the builtin error interface
func (e GetMetricsSummaryRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sGetMetricsSummaryRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = GetMetricsSummaryRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = GetMetricsSummaryRequestValidationError{}

// Validate checks the field values on GetMetricsSummaryReply with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *GetMetricsSummaryReply) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on GetMetricsSummaryReply with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// GetMetricsSummaryReplyMultiError, or nil if none found.
func (m *GetMetricsSummaryReply) ValidateAll() error {
	return m.validate(true)
}

func (m *GetMetricsSummaryReply) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for PrometheusStatus

	// no validation rules for MetricsSnapshotJson

	if all {
		switch v := interface{}(m.GetQueriedAt()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, GetMetricsSummaryReplyValidationError{
					field:  "QueriedAt",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, GetMetricsSummaryReplyValidationError{
					field:  "QueriedAt",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetQueriedAt()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return GetMetricsSummaryReplyValidationError{
				field:  "QueriedAt",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if len(errors) > 0 {
		return GetMetricsSummaryReplyMultiError(errors)
	}

	return nil
}

// GetMetricsSummaryReplyMultiError is an error wrapping multiple validation
// errors returned by GetMetricsSummaryReply.ValidateAll() if the designated
// constraints aren't met.
type GetMetricsSummaryReplyMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m GetMetricsSummaryReplyMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m GetMetricsSummaryReplyMultiError) AllErrors() []error { return m }

// GetMetricsSummaryReplyValidationError is the validation error returned by
// GetMetricsSummaryReply.Validate if the designated constraints aren't met.
type GetMetricsSummaryReplyValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e GetMetricsSummaryReplyValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e GetMetricsSummaryReplyValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e GetMetricsSummaryReplyValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e GetMetricsSummaryReplyValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e GetMetricsSummaryReplyValidationError) ErrorName() string {
	return "GetMetricsSummaryReplyValidationError"
}

// Error satisfies the builtin error interface
func (e GetMetricsSummaryReplyValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sGetMetricsSummaryReply.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = GetMetricsSummaryReplyValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = GetMetricsSummaryReplyValidationError{}

// Validate checks the field values on AckReportRequest with the rules defined
// in the proto definition for this message. If any rules are violated, the
// first error encountered is returned, or nil if there are no violations.
func (m *AckReportRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on AckReportRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// AckReportRequestMultiError, or nil if none found.
func (m *AckReportRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *AckReportRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for ReportId

	if len(errors) > 0 {
		return AckReportRequestMultiError(errors)
	}

	return nil
}

// AckReportRequestMultiError is an error wrapping multiple validation errors
// returned by AckReportRequest.ValidateAll() if the designated constraints
// aren't met.
type AckReportRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m AckReportRequestMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m AckReportRequestMultiError) AllErrors() []error { return m }

// AckReportRequestValidationError is the validation error returned by
// AckReportRequest.Validate if the designated constraints aren't met.
type AckReportRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e AckReportRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e AckReportRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e AckReportRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e AckReportRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e AckReportRequestValidationError) ErrorName() string { return "AckReportRequestValidationError" }

// Error satisfies the builtin error interface
func (e AckReportRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sAckReportRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = AckReportRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = AckReportRequestValidationError{}

// Validate checks the field values on AckReportReply with the rules defined in
// the proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *AckReportReply) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on AckReportReply with the rules defined
// in the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in AckReportReplyMultiError,
// or nil if none found.
func (m *AckReportReply) ValidateAll() error {
	return m.validate(true)
}

func (m *AckReportReply) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if len(errors) > 0 {
		return AckReportReplyMultiError(errors)
	}

	return nil
}

// AckReportReplyMultiError is an error wrapping multiple validation errors
// returned by AckReportReply.ValidateAll() if the designated constraints
// aren't met.
type AckReportReplyMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m AckReportReplyMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m AckReportReplyMultiError) AllErrors() []error { return m }

// AckReportReplyValidationError is the validation error returned by
// AckReportReply.Validate if the designated constraints aren't met.
type AckReportReplyValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e AckReportReplyValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e AckReportReplyValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e AckReportReplyValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e AckReportReplyValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e AckReportReplyValidationError) ErrorName() string { return "AckReportReplyValidationError" }

// Error satisfies the builtin error interface
func (e AckReportReplyValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sAckReportReply.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = AckReportReplyValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = AckReportReplyValidationError{}
