// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             (unknown)
// source: aiops/v1/aiops.proto

package v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	AIOps_TriggerAnalysis_FullMethodName   = "/api.cascade.aiops.v1.AIOps/TriggerAnalysis"
	AIOps_GetReport_FullMethodName         = "/api.cascade.aiops.v1.AIOps/GetReport"
	AIOps_ListReports_FullMethodName       = "/api.cascade.aiops.v1.AIOps/ListReports"
	AIOps_GetMetricsSummary_FullMethodName = "/api.cascade.aiops.v1.AIOps/GetMetricsSummary"
	AIOps_AckReport_FullMethodName         = "/api.cascade.aiops.v1.AIOps/AckReport"
)

// AIOpsClient is the client API for AIOps service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// AIOps provides intelligent operations analysis including alert noise reduction.
type AIOpsClient interface {
	// TriggerAnalysis manually triggers an alert analysis and noise reduction run.
	TriggerAnalysis(ctx context.Context, in *TriggerAnalysisRequest, opts ...grpc.CallOption) (*TriggerAnalysisReply, error)
	// GetReport retrieves a historical analysis report by ID or time range.
	GetReport(ctx context.Context, in *GetReportRequest, opts ...grpc.CallOption) (*GetReportReply, error)
	// ListReports lists historical analysis reports.
	ListReports(ctx context.Context, in *ListReportsRequest, opts ...grpc.CallOption) (*ListReportsReply, error)
	// GetMetricsSummary returns current metrics summary for debugging.
	GetMetricsSummary(ctx context.Context, in *GetMetricsSummaryRequest, opts ...grpc.CallOption) (*GetMetricsSummaryReply, error)
	// AckReport acknowledges a report.
	AckReport(ctx context.Context, in *AckReportRequest, opts ...grpc.CallOption) (*AckReportReply, error)
}

type aIOpsClient struct {
	cc grpc.ClientConnInterface
}

func NewAIOpsClient(cc grpc.ClientConnInterface) AIOpsClient {
	return &aIOpsClient{cc}
}

func (c *aIOpsClient) TriggerAnalysis(ctx context.Context, in *TriggerAnalysisRequest, opts ...grpc.CallOption) (*TriggerAnalysisReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TriggerAnalysisReply)
	err := c.cc.Invoke(ctx, AIOps_TriggerAnalysis_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aIOpsClient) GetReport(ctx context.Context, in *GetReportRequest, opts ...grpc.CallOption) (*GetReportReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetReportReply)
	err := c.cc.Invoke(ctx, AIOps_GetReport_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aIOpsClient) ListReports(ctx context.Context, in *ListReportsRequest, opts ...grpc.CallOption) (*ListReportsReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListReportsReply)
	err := c.cc.Invoke(ctx, AIOps_ListReports_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aIOpsClient) GetMetricsSummary(ctx context.Context, in *GetMetricsSummaryRequest, opts ...grpc.CallOption) (*GetMetricsSummaryReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetMetricsSummaryReply)
	err := c.cc.Invoke(ctx, AIOps_GetMetricsSummary_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aIOpsClient) AckReport(ctx context.Context, in *AckReportRequest, opts ...grpc.CallOption) (*AckReportReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AckReportReply)
	err := c.cc.Invoke(ctx, AIOps_AckReport_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AIOpsServer is the server API for AIOps service.
// All implementations must embed UnimplementedAIOpsServer
// for forward compatibility.
//
// AIOps provides intelligent operations analysis including alert noise reduction.
type AIOpsServer interface {
	// TriggerAnalysis manually triggers an alert analysis and noise reduction run.
	TriggerAnalysis(context.Context, *TriggerAnalysisRequest) (*TriggerAnalysisReply, error)
	// GetReport retrieves a historical analysis report by ID or time range.
	GetReport(context.Context, *GetReportRequest) (*GetReportReply, error)
	// ListReports lists historical analysis reports.
	ListReports(context.Context, *ListReportsRequest) (*ListReportsReply, error)
	// GetMetricsSummary returns current metrics summary for debugging.
	GetMetricsSummary(context.Context, *GetMetricsSummaryRequest) (*GetMetricsSummaryReply, error)
	// AckReport acknowledges a report.
	AckReport(context.Context, *AckReportRequest) (*AckReportReply, error)
	mustEmbedUnimplementedAIOpsServer()
}

// UnimplementedAIOpsServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedAIOpsServer struct{}

func (UnimplementedAIOpsServer) TriggerAnalysis(context.Context, *TriggerAnalysisRequest) (*TriggerAnalysisReply, error) {
	return nil, status.Error(codes.Unimplemented, "method TriggerAnalysis not implemented")
}
func (UnimplementedAIOpsServer) GetReport(context.Context, *GetReportRequest) (*GetReportReply, error) {
	return nil, status.Error(codes.Unimplemented, "method GetReport not implemented")
}
func (UnimplementedAIOpsServer) ListReports(context.Context, *ListReportsRequest) (*ListReportsReply, error) {
	return nil, status.Error(codes.Unimplemented, "method ListReports not implemented")
}
func (UnimplementedAIOpsServer) GetMetricsSummary(context.Context, *GetMetricsSummaryRequest) (*GetMetricsSummaryReply, error) {
	return nil, status.Error(codes.Unimplemented, "method GetMetricsSummary not implemented")
}
func (UnimplementedAIOpsServer) AckReport(context.Context, *AckReportRequest) (*AckReportReply, error) {
	return nil, status.Error(codes.Unimplemented, "method AckReport not implemented")
}
func (UnimplementedAIOpsServer) mustEmbedUnimplementedAIOpsServer() {}
func (UnimplementedAIOpsServer) testEmbeddedByValue()               {}

// UnsafeAIOpsServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AIOpsServer will
// result in compilation errors.
type UnsafeAIOpsServer interface {
	mustEmbedUnimplementedAIOpsServer()
}

func RegisterAIOpsServer(s grpc.ServiceRegistrar, srv AIOpsServer) {
	// If the following call panics, it indicates UnimplementedAIOpsServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&AIOps_ServiceDesc, srv)
}

func _AIOps_TriggerAnalysis_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TriggerAnalysisRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AIOpsServer).TriggerAnalysis(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AIOps_TriggerAnalysis_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AIOpsServer).TriggerAnalysis(ctx, req.(*TriggerAnalysisRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AIOps_GetReport_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetReportRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AIOpsServer).GetReport(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AIOps_GetReport_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AIOpsServer).GetReport(ctx, req.(*GetReportRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AIOps_ListReports_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListReportsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AIOpsServer).ListReports(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AIOps_ListReports_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AIOpsServer).ListReports(ctx, req.(*ListReportsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AIOps_GetMetricsSummary_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetMetricsSummaryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AIOpsServer).GetMetricsSummary(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AIOps_GetMetricsSummary_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AIOpsServer).GetMetricsSummary(ctx, req.(*GetMetricsSummaryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AIOps_AckReport_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AckReportRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AIOpsServer).AckReport(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AIOps_AckReport_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AIOpsServer).AckReport(ctx, req.(*AckReportRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// AIOps_ServiceDesc is the grpc.ServiceDesc for AIOps service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AIOps_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "api.cascade.aiops.v1.AIOps",
	HandlerType: (*AIOpsServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "TriggerAnalysis",
			Handler:    _AIOps_TriggerAnalysis_Handler,
		},
		{
			MethodName: "GetReport",
			Handler:    _AIOps_GetReport_Handler,
		},
		{
			MethodName: "ListReports",
			Handler:    _AIOps_ListReports_Handler,
		},
		{
			MethodName: "GetMetricsSummary",
			Handler:    _AIOps_GetMetricsSummary_Handler,
		},
		{
			MethodName: "AckReport",
			Handler:    _AIOps_AckReport_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "aiops/v1/aiops.proto",
}
