server:
  http:
    addr: 0.0.0.0:8002
    timeout: 1s
  grpc:
    addr: 0.0.0.0:9002
    timeout: 1s
data:
  database:
    driver: mysql
    source: cascade_oj:123456@tcp(cascade_mysql:3306)/cascade_oj_db?charset=utf8&parseTime=True&loc=Local
  redis:
    addr: rd:6379
    read_timeout: 0.2s
    write_timeout: 0.2s
jwt:
  secret: cascade
  expiration: 24 # hours
  issuer: cascade