services:
  public:
    build:
      context: ./
      dockerfile: app/services/public/Dockerfile
      args: 
        VERSION : 0.1.0
    image: cascade-oj/public:latest
    restart: unless-stopped
    depends_on:
      - cascade_mysql
    ports:
      - "8100:8000"
    volumes:
      - ./config/public:/data/conf
      - ./data/logs:/data/logs
    container_name: cascade_oj_public
    deploy:
      resources:
        limits:
          cpus: '0.25'
          memory: 64M
        reservations:
          cpus: '0.125'
          memory: 32M
    networks:
      - backend-network

  user:
    build:
      context: ./
      dockerfile: app/services/user/Dockerfile
      args: 
        VERSION : 0.1.0
    image: cascade-oj/user:latest
    restart: unless-stopped
    depends_on:
      - cascade_mysql
      - cascade_rabbitmq
      - cascade_redis
    ports:
      - "8200:8000"
    volumes:
      - ./config/user:/data/conf
      - ./data/logs:/data/logs
    container_name: cascade_oj_user
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 256M
        reservations:
          cpus: '0.5'
          memory: 128M
    networks:
      - backend-network

  judge:
    build:
      context: ./
      dockerfile: app/services/judge/Dockerfile
      args: 
        VERSION : 0.1.0
    image: cascade-oj/judge:latest
    restart: unless-stopped
    depends_on:
      - cascade_mysql
      - cascade_rabbitmq
      - cascade_redis
      - cascade_go_judge
    volumes:
      - ./config/judge:/data/conf
      - ./cases:/cases
      - ./data/logs:/data/logs
    container_name: cascade_oj_judge
    deploy:
      resources:
        limits:
          cpus: '0.25'
          memory: 256M
        reservations:
          cpus: '0.125'
          memory: 64M
    networks:
      - backend-network

  admin:
    build:
      context: ./
      dockerfile: app/services/admin/Dockerfile
      args: 
        VERSION : 0.1.0
    image: cascade-oj/admin:latest
    restart: unless-stopped
    depends_on:
      - cascade_mysql
      - cascade_rabbitmq
      - cascade_redis
    ports:
      - "8300:8000"
    volumes:
      - ./config/admin:/data/conf
      - ./data/logs:/data/logs
    container_name: cascade_oj_admin
    deploy:
      resources:
        limits:
          cpus: '0.25'
          memory: 256M
        reservations:
          cpus: '0.125'
          memory: 128M
    networks:
      - backend-network

  aiops:
    build:
      context: ./
      dockerfile: app/services/aiops/Dockerfile
      args: 
        VERSION : 0.1.0
    image: cascade-oj/aiops:latest
    restart: unless-stopped
    depends_on:
      - cascade_mysql
      - cascade_prometheus
    ports:
      - "8400:8000"
    volumes:
      - ./config/aiops:/data/conf
      - ./data/logs:/data/logs
    container_name: cascade_oj_aiops
    deploy:
      resources:
        limits:
          cpus: '0.25'
          memory: 128M
        reservations:
          cpus: '0.125'
          memory: 64M
    networks:
      - backend-network

networks:
  backend-network:
    driver: bridge
    name: cascade-oj-backend-network
