services:
  cascade_mysql:
    image: mysql:8.4
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: cascade_oj_db
      MYSQL_USER: cascade_oj
      MYSQL_PASSWORD: 123456
    volumes:
      - ./data/mysql:/var/lib/mysql
      - ./data/mysql_conf:/etc/mysql/mysql.conf.d
    container_name: cascade_oj_mysql
    deploy:
      resources:
        limits:
          cpus: '0.2'
          memory: 1G
        reservations:
          cpus: '0.1'
          memory: 512M
    networks:
      - backend-network

  cascade_redis:
    image: redis:7.0
    restart: always
    ports:
      - "6379:6379"
    container_name: cascade_oj_redis
    deploy:
      resources:
        limits:
          cpus: '0.2'
          memory: 128M
        reservations:
          cpus: '0.1'
          memory: 32M
    networks:
      - backend-network

  cascade_rabbitmq:
    image: rabbitmq:3.11-management
    restart: always
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: cascade_oj
      RABBITMQ_DEFAULT_PASS: 123456
    container_name: cascade_oj_rabbitmq
    deploy:
      resources:
        limits:
          cpus: '0.25'
          memory: 512M
        reservations:
          cpus: '0.2'
          memory: 256M
    networks:
      - backend-network

  # https://docs.goj.ac/cn/configuration
  cascade_go_judge:
    build:
      context: ./
      dockerfile: ./Dockerfile
    image: cascade-oj/go-judge:latest
    restart: always
    ports:
      - "5051:5051"
    environment:
      - ES_ENABLE_GRPC=true
    privileged: true
    shm_size: 512m
    volumes:
      - ./cases:/cases
    container_name: cascade_oj_go_judge
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 512M
        reservations:
          cpus: '0.5'
          memory: 64M
    networks:
      - backend-network

  cascade_prometheus:
    image: prom/prometheus:v2.53.0
    restart: always
    ports:
      - "9090:9090"
    volumes:
      - ./config/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.retention.time=15d'
    container_name: cascade_oj_prometheus
    deploy:
      resources:
        limits:
          cpus: '0.25'
          memory: 128M
        reservations:
          cpus: '0.125'
          memory: 64M
    networks:
      - backend-network

networks:
  backend-network:
    driver: bridge
    name: cascade-oj-backend-network
